### ISSUE TITLE
Change ExecuteModel to model in Python docs

### ISSUE THREAD

**Issue by AndySomogyi** [sys-bio/roadrunner#10]
<a href="https://github.com/hsauro"><img src="https://avatars.githubusercontent.com/u/1054990?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hsauro](https://github.com/hsauro)**
_Tuesday Jul 08, 2014 at 23:31 GMT_
_Originally opened as https://github.com/AndySomogyi/roadrunner-backup/issues/10_

----

**Comment by kirichoi** [comment]
What is the current status of this method?

**Comment by hsauro** [comment]
Its not a method, which is what is confusing in the docs. Its a class but
when someone sees it in the docs they think that have to call
executemethod. etc.

Is there someway to remove this word from the docs?

H

**Comment by 0u812** [comment]
Well, ExecuutableModel is the class name, which you get an instance of by calling rr.model. Not sure what we can do, python docs are always in the format ClassName.MethodName

On August 31, 2015 5:46:07 PM PDT, Herbert Sauro <notifications@github.com> wrote:
>Its not a method, which is what is confusing in the docs. Its a class
>but
>when someone sees it in the docs they think that have to call
>executemethod. etc.
>
>Is there someway to remove this word from the docs?
>
>H
>
>On Mon, Aug 31, 2015 at 3:44 PM, Kiri Choi <notifications@github.com>
>wrote:
>
>> What is the current status of this method?
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/sys-bio/roadrunner/issues/10#issuecomment-136520155>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/10#issuecomment-136538597

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
I don't know either but its confusing to users. I've seen many people write
ExecutableModel.foo and get an error message. We need to think of someway
to deal with this. Maybe at the start of every page point out that when
someone sees ExecutableModel.foo it does not mean type that at the console.

Alternatively completely separate the API reference from the user manual.
So that user don't stumble on the docs with ExecutableModel in them.

H

**Comment by kirichoi** [comment]
I think the best way is to first put something like <ExecutableModel> instead of ExecutableModel and note that it should be changed for roadrunner instance to work. Otherwise, I can see some users actually trying model.foo as well. What do you think?

**Comment by hsauro** [comment]
Yes we can try that.

H

**Comment by kirichoi** [comment]
something like \* \<ExecuteModel\> instead of ExecuteModel *

**Comment by kirichoi** [comment]
Fixed via e98f85fc43daaf6bb61344948830ef8e16af1ee5
