### ISSUE TITLE
C API method getRatesOfChangeIds only returns independent ids

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#1009]
The C API method getRatesOfChangeIds only returns independent ids.

eg with the following model

A -> B; k1*A
B -> C; k2*B
k1 = 0.35; k2 = 0.2
A = 10

the C API method returns B', and A'  but not C'.

Secondly, are these rates of change of concentration or amounts?

**Comment by luciansmith** [comment]
Needs to match getRatesOfChange.
