### ISSUE TITLE
Change availability section to....

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#1039]
Change the text in the "Availability" section to just (or current one includes sf.net which we don't use anymore).

RoadRunner is licensed for free as an open source programmatic library for use in other applications and as a standalone command line driven application. Its C++ API, C API, and Python APIs have comprehensive documentation.

**Comment by hsauro** [comment]
Typo in:

Python bindings can additionall be downloaded via pip.

**Comment by luciansmith** [comment]
Fixed!  Thanks.
