### ISSUE TITLE
Similar to #1042, possibly the same bug

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#1043]
This might be the same issue as with #1042 

import tellurium as te
import roadrunner
from roadrunner import RoadRunner

r = te.loada ('''
     $Xo -> S1; k1*Xo;
      S1 -> S2; k2*S1;
      S2 ->; k3*S2; 
      Xo = 4; k1 = 0.5; k2 = 0.23; k3 = 0.56             
''')

sensSolver = r.getSensitivitySolver()
time, sens, rownames, colnames = r.timeSeriesSensitivities(0, 10, 11, params=['k1'])

# This doesn't work, probably due to specifying one parameter:
roadrunner.plotTimeSeriesSens(time, sens, rownames, colnames)

    roadrunner.plotTimeSeriesSens(time, sens, rownames, colnames)

  File "C:\Tellurium-Winpython-3.8\python-3.8.6.amd64\lib\site-packages\roadrunner\roadrunner.py", line 7354, in plotTimeSeriesSens
    ax[i, j].plot(time, df[(species, param)].to_numpy(), label=f"{species}:{param}")

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by luciansmith** [comment]
Fixed with https://github.com/sys-bio/roadrunner/pull/1049
