### ISSUE TITLE
Document how the Python API docs are constructed

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#105]
Add some documentation to the libroadruner.org site on how the python docs are updated.

**Comment by 0u812** [comment]
Documentation for building the Sphinx docs is up at http://libroadrunner.org/howto-update-the-libroadrunner-online-documentation/. Please let me know if it's clear and I'll close this.

**Comment by hsauro** [comment]
Looks ok, haven't tried but because it seems a bit complicated just to say fix a typo. But if it works, it works.
