### ISSUE TITLE
Anaconda x86 distro on Mac M1: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by rheiland** [sys-bio/roadrunner#1053]
```
M1P~/dev$ which python
/Users/heiland/anaconda3_x86/bin/python
M1P~/dev$ python --version
Python 3.9.12
M1P~/dev$ pip install libroadrunner
Requirement already satisfied: libroadrunner in /Users/heiland/anaconda3_x86/lib/python3.9/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.0 in /Users/heiland/anaconda3_x86/lib/python3.9/site-packages (from libroadrunner) (1.22.4)

M1P~/dev$ python
Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import roadrunner
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/heiland/anaconda3_x86/lib/python3.9/site-packages/roadrunner/__init__.py", line 10, in <module>
    from .roadrunner import *
  File "/Users/heiland/anaconda3_x86/lib/python3.9/site-packages/roadrunner/roadrunner.py", line 15, in <module>
    from . import _roadrunner
ImportError: numpy.core.multiarray failed to import

>>> import numpy
>>> numpy.__version__
'1.22.4'
```

**Comment by luciansmith** [comment]
Some internet sleuthing claims that this sort of thing can happen when there are multiple versions of numpy installed on your machine.  Numpy in particular will come with the system install, so the installation in /Users/heiland/ may be conflicting with it.  numpy.__path__ may be instructive?

Beyond that, perhaps try uninstalling numpy (multiple times, if there are actually multiple installs) and then reinstalling?

**Comment by rheiland** [comment]
Thanks for the prompt reply. Yes, I'd seen similar posts but am always a little reluctant to mess with something as critical as numpy. But I went ahead and did `pip install -U numpy` and now can `import roadrunner` without errors.

**Comment by luciansmith** [comment]
If it turns out you need to revert numpy for the main python installation on the mac, you might look into virtual environments for python, so you can safely have the two versions at once.  But if it's working for now, great!
