### ISSUE TITLE
building and linking in C++

### ISSUE THREAD

**Issue by steffenger** [sys-bio/roadrunner#1054]
Hello all,

I tried bulding and linking a recent version of libRoadRunner in C++.
I cam across two issues and would really appreciate help.

1. Could it be that the script ImportRoadrunnerAndDependencies.cmake has not yet been updated to the new dependency structure and naming convention of the other cmake scripts. In my opinion it could look like this:

```
# CMake module for importing roadrunner targets with dependencies
# into consuming libraries cmake system.
#
# Clients need roadrunner but must also import the dependencies
# with find_package. Its easy to bundle these together
# and document it.
#
find_package(Threads) # for libxml2, FindThreads.cmake is shipped with cmake
find_package(LibLZMA) # for libxml2, LibLZMA.cmake is shipped with cmake
find_package(zlib CONFIG REQUIRED)
find_package(bzip2 CONFIG REQUIRED)
#find_package(iconv CONFIG REQUIRED)
#find_package(LibXml2 CONFIG REQUIRED)
find_package(expat CONFIG REQUIRED)
find_package(sbml-static CONFIG REQUIRED)
find_package(rr-libstruct CONFIG REQUIRED)
find_package(clapack CONFIG REQUIRED)
find_package(nleq1 CONFIG REQUIRED)
find_package(nleq2 CONFIG REQUIRED)
find_package(PocoFoundation CONFIG REQUIRED)
find_package(PocoNet CONFIG REQUIRED)
find_package(PocoXML CONFIG REQUIRED)
find_package(SUNDIALS CONFIG REQUIRED)
find_package(LLVM REQUIRED)
```
2. I got the following issue when i tried linking the roadrunner library with the CMakeLists.txt from the docs. Do you have any clue?

<img width="605" alt="image" src="https://user-images.githubusercontent.com/95339856/197148243-10e1a124-196b-4591-ac7a-7cfe4c35eb4c.png">

with this setup and CMake 3.20 version:

The C compiler identification is GNU 8.5.0
 The CXX compiler identification is GNU 8.5.0
 Detecting C compiler ABI info
 Detecting C compiler ABI info - done
 Check for working C compiler: /usr/bin/cc - skipped
 Detecting C compile features
 Detecting C compile features - done
 Detecting CXX compiler ABI info
 Detecting CXX compiler ABI info - done
 Check for working CXX compiler: /usr/bin/c++ - skipped
 Detecting CXX compile features
 Detecting CXX compile features - done
 Looking for pthread.h
 Looking for pthread.h - found
 Performing Test CMAKE_HAVE_LIBC_PTHREAD
 Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
 Looking for pthread_create in pthreads
 Looking for pthread_create in pthreads - not found
 Looking for pthread_create in pthread
 Looking for pthread_create in pthread - found
 Found Threads: TRUE
 Looking for lzma_auto_decoder in /usr/lib64/liblzma.so
 Looking for lzma_auto_decoder in /usr/lib64/liblzma.so - found
 Looking for lzma_easy_encoder in /usr/lib64/liblzma.so
 Found LibLZMA: /usr/lib64/liblzma.so (found version "5.2.4")
 Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2")
 Found ZLIB: /lib64/libz.so (found version "1.2.11")
 Performing Test EXPAT_EXPAT_TEST
 Performing Test EXPAT_EXPAT_TEST - Success
 Found EXPAT: /lib64/libexpat.so (found version "2.2.5")

If you need more information please let me know.

best regards,

Steffen

**Comment by luciansmith** [comment]
Apologies for not getting back to you sooner!

For the first, the file in question is for when roadrunner is being used in other projects, correct?  If so, then yes, we haven't updated it in quite some time, and I don't think we test it anywhere, so your proposed changes are indeed likely to be correct. Do they work for you?

For the second, I'm not at all sure what's going on.  All I can think is that one thing is using cxx11 and another isn't?  Or that some cxx11 library isn't being linked in where it should?

I can say that we do build roadrunner on various platforms regularly, so it should at least work in those contexts, but it may be that you're using a configuration we haven't tested.  What OS/architecture are you trying this on?
