### ISSUE TITLE
How to access species values as defined via the hasOnlySubstanceUnit flag (amount/concentration)?

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#1090]
Hi all,
I have the following problem. 

I want to access species in a model as they are defined in the SBML. I.e. if a Species is defined in amounts I want the amount, if the species is defined in concentration I want the concentration.

Currently, this is not possible and I can either access concentration as `[S1]` or amount as `S1`,  but there is no `S1_as_defined`. This is important in the context of parameter fitting and reproducibility. 
Most tools provide on access of a species the values as defined. To compare the output of other tools I would need to access the `S1_as_defined` easily from a simulation.

Best Matthias

**Comment by hsauro** [comment]
This is something TJ or Adel could work on. Maybe TJ since Adel is working
in the other problem.

**Comment by matthiaskoenig** [comment]
Does not have to be handled in roadrunner. By parsing the SBML I could figure this out.
