### ISSUE TITLE
How does simulateOptions work?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#110]
Setting options in roadrunner is a bit confusing. There appear to be at least two ways to set options, and there may be others. The main problem is that the semantics are undefined in the docs and might be unnecessary restrictions on how options can be set for particular integrators.

One way to set options is to explicitly set the option in the method call itself, eg

r.simulate (0, 10, 100, stiff=True)

This approach can be tedious if many options need to be set each time a simulation is run. The docs are not clear whether changing an option like this is just for the one call or sets the options for all subsequent calls. 

The other way to set options is via SimulationOptions. However it is not clear how the options are set, are they set for every implemented simulator? In other words there doesn't appear to be a means to fine tune a particular simulation algorithm since it looks like a global change. 

Two questions: 

1) The semantic needs to be more clearly defined and the docs updated 
2) If there a better way to set options that is more friendly to users?

**Comment by 0u812** [comment]
See #173
