### ISSUE TITLE
Merge bifurcation-fix branch in to libRoadRunner Develop 

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#112]
Merge bifurcation-fix branch in to libRoadRunner Develop

**Comment by 0u812** [comment]
@wcopeland, can you confirm if these changes are in cmoieties-fix-1? If so, I will merge that branch instead. If not, does bifurcation-fix need to be merged as well?

**Comment by wcopeland** [comment]
Yes, the changes are in cmoieties-fix-1 and that is the only one that needs to be merged.
