### ISSUE TITLE
Incorrect argument in Python simulate call

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#119]
The Python simulate call takes three arguments, start time, end time and number of points. However it seems that the number of points is in fact the number of intervals. Where is this difference coming from, the Python interface or the underlying C++ API? The Python documentation indicates that the argument is the number of steps which sounds like the number of intervals. If this is the case then this is an error and the argument should be the number of points.

**Comment by 0u812** [comment]
Change only Python bindings
