### ISSUE TITLE
libroadrunner 2.7.0 python package not available for Mac OS with 22.5.0 Darwin Kernel

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#1220]
Hi all,
A student of mine has issues installing the latest roadrunner version.
Pretty new MacBook Air with python 3.11. Version 2.6.0 is available and can be installed.

```bash
(pkdb_models) nikemuller@MacBook-Air-von-Nike sbmlsim % pip install libroadrunner==2.7.0
ERROR: Could not find a version that satisfies the requirement libroadrunner==2.7.0 (from versions: 2.3.1, 2.3.2, 2.4.0, 2.5.0, 2.6.0)
ERROR: No matching distribution found for libroadrunner==2.7.0
```

```bash
(pkdb_models) nikemuller@MacBook-Air-von-Nike sbmlsim % uname -a
Darwin MacBook-Air-von-Nike.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:40:17 PDT 2023; root:xnu-8796.121.2~3/RELEASE_ARM64_T8112 arm64
```

System information:

  Modellname:	MacBook Air
  Modell-Identifizierung:	Mac14,15
  Modellnummer:	MQKP3D/A
  Chip:	Apple M2
  Gesamtanzahl der Kerne:	8 (4 Leistung und 4 Effizienz)
  Speicher:	8 GB
  Systemfirmwareversion:	8422.121.3
  OS-Ladeprogrammversion:	8422.121.3
  Seriennummer (System):	GJXGXVG9PK
  
Best Matthias

**Comment by luciansmith** [comment]
2.7 is the first version we've made entirely using github actions, instead of building it for the M1 by hand.  However, I would have thought it would work with this:

https://files.pythonhosted.org/packages/e0/28/e3a033a367a0c8337cdf68f5f2b3c26c87905a081ce65139208a7d363173/libroadrunner-2.7.0-cp311-cp311-macosx_14_0_arm64.whl

It did take us longer to get that file up at pypi than the others, but it's been up since the 8th.

I can't tell if "Mac14,15" means it's indeed running macosx14?  If so, I don't know why the above file wouldn't work!

**Comment by matthiaskoenig** [comment]
@nikenemitz Could you try the following two things in the virtual environment. I.e. do a 
`conda activate pkdb_models` and then execute the following
```
pip install --upgrade pip
pip install -v libroadrunner==2.7.0
```
This should provide a bit more information what is going wrong.

Could you then try if the following works
```
pip install --find-links=https://files.pythonhosted.org/packages/e0/28/e3a033a367a0c8337cdf68f5f2b3c26c87905a081ce65139208a7d363173/libroadrunner-2.7.0-cp311-cp311-macosx_14_0_arm64.whl libroadrunner
```
If this works we have to figure out why your architecture/platform is not resolved via pip.

**Comment by matthiaskoenig** [comment]
We tested this and when trying to install the wheel directly it results in a 
```
libroadrunner-2.7.0-cp311-cp311-macosx_14_0_arm64.whl is not supported on this platform
```
The reported platform tag is `sysconfig.get_platform()`: `macosx-11.1-arm64` and system is running macOS Ventura 13.4. The old libroadrunner libroadrunner-2.6.0-cp311-cp311-macosx_12_0_arm64.whl worked, probably it only required macosx_12.
So it seems that there is no release for this laptop (is only ~1 year old and should be supported).

Solution was to update MacOs from 13.4 to 14.5. So for users having this issue try to update MacOs via the system settings.

**Comment by matthiaskoenig** [comment]
Solved via updating MacOS
