### ISSUE TITLE
Warnings/Errors in Tellurium

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#125]
*Initializing non existing values to 0*
Via Matthias:
- if a model has no values for parameters or no initial concentrations for species roadrunner is initializing the values with 0.
For instance a parameter mu
`<parameter id="mu" constant="true"/>`
will be `mu=0` in roadrunner.

If values are undefined this should raise an error/warning => otherwise models which were wrongly specified have implied values. An implied 0 often lets the model integrate, but shuts down certain mathematics => very difficult to debug & find once the model is running.
I just looked today for 1h what is going on, because RoadRunner integrated the model without any problems, despite me forgetting to specify a numerical value for the parameter.

**Comment by hsauro** [comment]
Make sure error messages go to the ipython console. Currently the messages only goes to the normal python console.

**Comment by 0u812** [comment]
Migrated to tellurium
