### ISSUE TITLE
Handling time in steady state

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#128]
Via Matthias:
When calculating the steady state and 'time' is in the selection, the value for time is wrong/misleading. The example here is for  the example simulation above in mca.py.
```
# Steady States
# Performs a steady state calculation (evolves the system to a steady
#        state), then calculates and returns the set of values specified by
#        the steady state selections.
print rr.selections
print rr.getSteadyStateValues()

['time', '[A]', '[C]', '[B]', '[C_ext]', '[B_ext]', '[A_ext]']
[ 0.59210526  1.11842105  3.28947368  1.11842105  3.28947368  0.59210526]
```
It looks like the 'time' value is just the value of the last Selection item, but it should correspond to the time the steady state is reached in the evolve, or nan. Steady state is only reached around >10s, this should be reflected in the time value (or just set it to nan)

**Comment by hsauro** [comment]
There is no concept of time when computing the steadystate. Also selections refers to the time course selections, use steadyStateSelections instead.

**Comment by 0u812** [comment]
`rr.selections` should be renamed `rr.timeCourseSelections` for clarity.
