### ISSUE TITLE
Add test to Python tests for getCC()

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#139]
Add code to test the getCC function. Add the test to rrPython.py

Add the expected results to the data files stored in test_data

Get the expected results by running the models in COPASI.

**Comment by luciansmith** [comment]
The python tester is in wrappers\Python\roadrunner\testing

**Comment by kirichoi** [comment]
Reference #94

**Comment by 0u812** [comment]
Test failure in jacobian_1.rrtest conc CC. Dumping out **unscaled** conc CC's in RoadRunner::getScaledConcentrationControlCoefficientMatrix gives answer identical to COPASI
```
0.580842,-0.393912,-0.659803,-0.107968
1.32498,1.07431,-3.20054,-0.523724
1.55416,0.179051,0.29991,-3.58729
```

Dumping out the **scaled** CC's gives an answer that diverges from COPASI in lines 2 and 3:
```
0.85479,-0.289849,-0.485496,-0.0794448
1.70958,0.693073,-2.06478,-0.337873
1.70958,0.0984781,0.164951,-1.97301
```

Code:
```
DoubleMatrix RoadRunner::getScaledConcentrationControlCoefficientMatrix()
{
    get_self();

    check_model();

    DoubleMatrix ucc = getUnscaledConcentrationControlCoefficientMatrix();

    std::cerr << "Unscaled conc CC's:\n" <<  ucc << "\n\n\n";

    if (ucc.size() > 0 )
    {
        for (int i = 0; i < ucc.RSize(); i++)
        {
            for (int j = 0; j < ucc.CSize(); j++)
            {
                double conc = 0;
                self.model->getFloatingSpeciesConcentrations(1, &i, &conc);

                double rate = 0;
                self.model->getReactionRates(1, &j, &rate);
                ucc[i][j] = ucc[i][j] * rate / conc;
            }
        }
    }

    std::cerr << "Scaled conc CC's:\n" <<  ucc << "\n\n\n";

    return ucc;
}
```

**Comment by 0u812** [comment]
I don't understand where COPASI is getting the scaled conc CC values for jacobian1. I ran the model in COPASI and compared output side-by-side. We have all the same species concentrations, reaction rates, and unscaled CCs, yet the answers are different. Here is the analysis:
https://docs.google.com/document/d/19e8E_JXKQ3MRbORDm7Xgz7xjUg7OBmiKvQNSHTNxvFc/edit?usp=sharing

**Comment by luciansmith** [comment]
I can say that the tests used to pass, assuming that these aren't the new
ones.

Usually, when there are issues like this, the difference turns out to be
concentrations vs. amounts.

-Lucian

**Comment by 0u812** [comment]
There's a Heisenbug in the jacobian1 model. The same test passes for Kiri on his machine.

**Comment by 0u812** [comment]
On Windows, where the problem does not occur, roadrunner produces different values for the **unscaled** concentration CC's, and this is where the discrepancy is coming from. The reaction rates and species concentrations are the same.

**Unscaled ucc (Win32):**
```
0.580842,-0.393912,-0.659803,-0.107968
0.662489,0.537153,-1.60027,-0.261862
0.777081,0.0895255,0.149955,-1.79364
```

**Scaled ucc (Win32):**
```
0.85479	-0.289849	-0.485496	-0.0794448	
0.85479	0.346536	-1.03239	-0.168936	
0.85479	0.049239	0.0824754	-0.986504	
```

I'm not exactly sure which calculation to pin the blame on yet, however, because of COPASI's apparently self-contradictory behavior.

**Comment by 0u812** [comment]
I think @luciansmith was right. The model has two compartments, with comp1 having a size of 1 and comp2 having a size of 2. The species corresponding to the rows which are doubled in the conc CC are in comp2. Now, why does it behave differently on the two platforms? Grrrrr...

**Comment by 0u812** [comment]
The test right before the conc CC's is `SCALED_ELASTICITY_AMOUNT_MATRIX`, which calls
```
Config::setValue(Config::ROADRUNNER_JACOBIAN_MODE, (unsigned)Config::ROADRUNNER_JACOBIAN_MODE_AMOUNTS);
```
`SCALED_CONCENTRATION_CONTROL_MATRIX` never makes the call to reset the config to concentrations, so returning the concentration control matrix in terms of amounts is expected. The real question is why it gets set back to concentrations on Windows when there's nothing there calling the `setValue` method. It just mysteriously sets itself back to concentrations when the C API is called. I don't like this...

**Comment by 0u812** [comment]
I think this is due to the fact that processes on Windows have their own instances of DLL data. The config data is static, hence the test suite runner makes a copy. On Linux, the libraries share data with processes so no new instance is made. All of this is okay. I was mainly afraid of a memory bug somewhere.

**Comment by 0u812** [comment]
The fix is to call `Config::setValue` before computing the matrix, which I will take care of soon.

**Comment by 0u812** [comment]
Thanks for your help, @luciansmith!
