### ISSUE TITLE
Add File->LoadSBML Model to Tellurium

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#140]
Add a menu item to File to allow someone to easily load an SBML model and copy the antimony equivalent to the editor.

**Comment by luciansmith** [comment]
Might we also give them basic roadrunnner simulation commands?

**Comment by kirichoi** [comment]
Plugin located at:
https://github.com/kirichoi/spyderplugins/blob/master/p_opensbml.py

Will be incorporated into the next version of Tellurium.
