### ISSUE TITLE
Options methods should return bool not int

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#150]
To be consistent with the rest of the API, those methods that return success or failure should return a bool true or false. eg 

 int setIntegrator (...)

returns an int but according to the docs it should return a bool. All methods that return success or fail should return the bool type.

**Comment by 0u812** [comment]
`bool` isn't a valid data type in C89. There are bools all over the C API, which is unfortunate. I don't know why it seems to work, maybe a hack in there somewhere. I would suggest using an int, and convert the bool-returning functions to int in the future.

**Comment by hsauro** [comment]
ok, convert them all to int.

Herbert

**Comment by wcopeland** [comment]
They have been all moved back to int.
