### ISSUE TITLE
Check whether hints have the correct strings

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#152]
Check whether the hints are useful strings attached to them. For example the hint attached to 

char *rrcCallConv 	getIntegratorHint (RRHandle handle)

returns

CVODE hint

Check all the hints for the parameters to make sure they are filled out.

**Comment by 0u812** [comment]
Can you tell me what should go in a hint and how it's different from the description?

**Comment by 0u812** [comment]
Sampling of current hints and desc's:
```
Number of registered integrators:	 4
  0:
   Name: cvode
   Hint: Deterministic ODE solver
   Desc: CVODE is a deterministic ODE solver from the SUNDIALS suite
 of timecourse integrators. It implements an Adams-Moulton solver for non-stiff 
problems and a backward differentiation formula (BDF) solver for stiff problems.
  1:
   Name: gillespie
   Hint: Gillespie Direct Method SSA
   Desc: RoadRunner implementation of the standard Gillespie Direct 
Method SSA. The granularity of this simulator is individualmolecules 
and kinetic processes are stochastic. Results will, in general, be different 
in each run, but a sufficiently large ensemble should be statistically correct.
  2:
   Name: rk4
   Hint: Internal RK4 ODE solver
   Desc: Runge-Kutta methods are a family of algorithms for solving ODEs. 
They have considerably better accuracy than the Euler method. This 
integrator is a standard 4th order Runge-Kutta solver.
  3:
   Name: euler
   Hint: An elementary (my dear Watson) Euler integrator
   Desc: The Euler method is one of the simplest approaches to solving 
a first order ODE. Given the rate of change of function f at time t, it 
computes the new value of f as f(t+h) = f(t) + h*f'(t), where h is the time 
step. Euler's method is rarely used in practice due to poor numerical robustness.
```

**Comment by hsauro** [comment]
A hint is shorter. A description should be a fuller description. Just put
something in and I'll check them out, use common sense.
Herbert

Herbert

**Comment by wcopeland** [comment]
CVODE setting names, balue, hints, and descriptions kept getting dropped out of commits that I pushed so I am just placing them here for now...

addSetting("stiff", false, "Specifies whether the integrator attempts to solve stiff equations. (bool)", "(bool) Specifies whether the integrator attempts to solve stiff equations. Ensure the integrator can solver stiff differential equations by setting this value to true.");
		addSetting("variable_step_size", false, "Perform a variable time step simulation. (bool)", "(bool) Enabling this setting will allow the integrator to adapt the size of each time step. This will result in a non-uniform time column.");
		addSetting("multiple_steps", false, "Perform a multiple time step simulation. (bool)", "(bool) Perform a multiple time step simulation. ");
		addSetting("initial_time_step", 0.0, "Specifies the initial time step size. (double)", "(double) Specifies the initial time step size. If inappropriate, CVODE will attempt to estimate a better initial time step.");
		addSetting("minimum_time_step", 0.0, "Specifies the minimum absolute value of step size allowed. (double)", "(double) The minimum absolute value of step size allowed.");
		addSetting("maximum_time_step", 0.0, "Specifies the maximum absolute value of step size allowed. (double)", "(double) The maximum absolute value of step size allowed.");
		addSetting("maximum_num_steps", mDefaultMaxNumSteps, "Specifies the maximum number of steps to be taken by the CVODE solver in its attempt to reach tout. (int)", "(int) Maximum number of steps to be taken by the CVODE solver in its attempt to reach tout.");
		addSetting("maximum_adams_order", mDefaultMaxAdamsOrder, "Specifies the maximum order for Adams-Moulton intergration. (int)", "(int) Specifies the maximum order for Adams-Moulton intergration. This integration method is used for non-stiff problems. Default value is 12.");
		addSetting("maximum_bdf_order", mDefaultMaxBDFOrder, "Specifies the maximum order for Backward Differentiation Formula integration. (int)", "(int) Specifies the maximum order for Backward Differentiation Formula integration. This integration method is used for stiff problems. Default value is 5.");
		addSetting("relative_tolerance", 1e-6, "Specifies the scalar relative tolerance (double).", "CVODE calculates a vector of error weights which is used in all error and convergence tests. The weighted RMS norm for the relative tolerance should not become smaller than this value.");
		addSetting("absolute_tolerance", 1e-12, "Specifies the scalar absolute tolerance (double).", "CVODE calculates a vector of error weights which is used in all error and convergence tests. The weighted RMS norm for the absolute tolerance should not become smaller than this value.");

**Comment by wcopeland** [comment]
Gillespie settings: names, values, hints, and descriptions

addSetting("seed", defaultSeed(), "Set the seed into the random engine. (ulong)", "(ulong) Set the seed into the random engine.");
		addSetting("variable_step_size", false, "Perform a variable time step simulation. (bool)", "(bool) Enabling this setting will allow the integrator to adapt the size of each time step. This will result in a non-uniform time column.");
		addSetting("initial_time_step", 0.0, "Specifies the initial time step size. (double)", "(double) Specifies the initial time step size.");
		addSetting("minimum_time_step", 0.0, "Specifies the minimum absolute value of step size allowed. (double)", "(double) The minimum absolute value of step size allowed.");
		addSetting("maximum_time_step", 0.0, "Specifies the maximum absolute value of step size allowed. (double)", "(double) The maximum absolute value of step size allowed.");

**Comment by 0u812** [comment]
Settings and hints applied
