### ISSUE TITLE
How to get the names of supported integators?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#155]
How can a user obtain the names of the integrators currently supported by libRoadRunner. Without the names it is not possible to make calls to setIntegrator (name). This issue is also related to the bug where a call to getNumberOfIntegrator returns one, suggesting that libRoadRunner only supports one integrator.

**Comment by 0u812** [comment]
There are several lists of integrators now in RoadRunner:
* The number of registered (i.e. implemented) integrators
* The number of integrators currently instantiated for a RoadRunner instance
This issue refers to the former.

**Comment by 0u812** [comment]
I provided several functions to query the registered integrators in the C API:
* [getNumRegisteredIntegrators](http://sys-bio.github.io/roadrunner/c_api_docs/html/rrc__api_8h.html#a53617fbabff8088e10c8bc5deee40353)
* [getRegisteredIntegratorName](http://sys-bio.github.io/roadrunner/c_api_docs/html/rrc__api_8h.html#a5713f7cea279fc58aa497615ebb7ddbf)
* [getRegisteredIntegratorHint](http://sys-bio.github.io/roadrunner/c_api_docs/html/rrc__api_8h.html#a6d22f11e49e89336e5d795e620e55530)
* [getRegisteredIntegratorDesc](getNumInstantiatedIntegrators)

If, on the other hand, you want the number of *instantiated* integrators, then you call this (I don't know if it currently supports more than one):
* [getNumInstantiatedIntegrators](http://sys-bio.github.io/roadrunner/c_api_docs/html/rrc__api_8h.html#a492555873a0da5f8aa167eeafb7d7d21)

For clarity, I also changed the name of pretty much every integrator get/set function to refer to have the word "current" in the name, e.g. [getNumberOfCurrentIntegratorParameters](http://sys-bio.github.io/roadrunner/c_api_docs/html/rrc__api_8h.html#a7885d06904fc2cdceaa7e71448cde468).

All these links point to the latest C API docs, which I just updated.
