### ISSUE TITLE
setCurrentIntegrator with gillespie crashes system

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#162]
If setCurrentIntegrator is called with cvode, rk4 or euler, the method successfully returns. If it is called with the name gillespie, the call crashes the system with an access violation.

**Comment by 0u812** [comment]
Oh my, I thought that was tested. I'll take a look.

On August 3, 2015 12:44:03 PM PDT, Herbert Sauro <notifications@github.com> wrote:
>If setCurrentIntegrator is called with cvode, rk4 or euler, the method
>successfully returns. If it is called with the name gillespie, the call
>crashes the system with an access violation.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/162

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by 0u812** [comment]
I don't know where the segfault is coming from. There is a C test which calls `setCurrentIntegrator(_handle, "gillespie")` which doesn't crash:
https://github.com/sys-bio/roadrunner/blob/develop/wrappers/C/ApiTest/main.c#L121

Could you call setLogLevel("debug") at the beginning of your program get give me the log output? You can enable logging to a file by calling 
```
enableLoggingToFile()
char* t = getLogFileName();
printf("Enabling logging to %s\n", t);
```

Please use 1.3.8 binaries for this, I fixed some problems with logging etc:
http://sourceforge.net/projects/libroadrunner/files/libroadrunner-1.3.8/alpha/roadrunner-1.3.8-vs12-llvm-3.5-win32.zip/download

**Comment by hsauro** [comment]
Ok I'll give it a go. I checked that it didn't crash with a misspelt name,
that worked ok

H

**Comment by 0u812** [comment]
It's odd that it crashes, the only memory errors valgrind shows (other than leaks) are in LLVM, which isn't unexpected. I also tried instantiating all integrators beforehand, still no problems.

**Comment by hsauro** [comment]
Found the problem, I get a crash if I don't first load a model. This is
different behavior from the other three solvers which don't care. Should be
fixed.

Herbert
