### ISSUE TITLE
Add method to retrieve the nth parameter for an integrator

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#163]
Implement a method to retrieve the name of the nth integrator parameter:

char * getCurrentIntegratorParameterName (int n)

Also implement the associated methods:

char * getCurrentIntegratorParameterDescription (int n)
char * getCurrentIntegratorParameterHint (int n)

**Comment by 0u812** [comment]
I can implement this, but they're stored in an unordered container, so the order will (in general) be different each time.

**Comment by hsauro** [comment]
I've reduced its priority to just enhancement. More important are the show
stopper bugs identified this afternoon.

Herbert

**Comment by 0u812** [comment]
Okay, I already had started working on it (it's a pretty simple change).

**Comment by hsauro** [comment]
ok, I should have prioritized better. At the moment I can't usefully run
libRoadRunner because of the other problems we found this afternoon. It
either crashes or doesn't do what it is supposed to do.

He
