### ISSUE TITLE
Setting boolean parameters is ignored

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#165]
Setting the boolean parameters, multiple_steps, stiff and variable_step_size is ignored.

**Comment by 0u812** [comment]
I'm not seeing this behavior or the behavior in #164 in [my test program](https://github.com/sys-bio/roadrunner/blob/develop/wrappers/C/ApiTest/main.c). I made some new binaries, 1.3.9:
http://sourceforge.net/projects/libroadrunner/files/libroadrunner-1.3.9/alpha/roadrunner-1.3.9-vs12-llvm-3.5-win32.zip/download
In these binaries, I explicitly cast the Variant type to bool before setting it. Please let me know if you still experience the problem.

**Comment by hsauro** [comment]
Just found out its my problem, I wasn't passing a char* to the methods when setting.
