### ISSUE TITLE
Call to getCurrentIntegratorName crashes if a model hasn't been loaded.

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#166]
If a call to getCurrentIntegratorName is made and a model hasn't been previously loaded, the method generates an access violation. It should be possible to get the current integrator name even if a model hasn't been loaded.

**Comment by 0u812** [comment]
The initial CVODE integrator isn't instantiated until a model is loaded. I made `getCurrentIntegratorName` return an empty string in the case where no integrators have been instantiated, in roadrunner 1.3.10:
http://sourceforge.net/projects/libroadrunner/files/libroadrunner-1.3.10/alpha/roadrunner-1.3.10-vs12-llvm-3.5-win32.zip/download

I can also provisionally instantiate a CVODE integrator whenever a roadrunner instance is created if you like. Please let me know.

**Comment by hsauro** [comment]
ok, I'm going to try now. Note the Boolean issues have been resolve, it was
my fault, wrong parameter type at my end.

H

**Comment by hsauro** [comment]
I think we need an integrator (namely cvode) to be instantiated at startup.
I'm not sure who should do it, libRoadRunner or the application using
libRoadRunner. If I do it I need to know the name of it, ie 'cvode'. In
which case it is probably better if libroadrunner instantiates a default
(cvode) integrator at startup.

H

**Comment by 0u812** [comment]
Okay, I can do that.

On August 3, 2015 6:30:12 PM PDT, Herbert Sauro <notifications@github.com> wrote:
>I think we need an integrator (namely cvode) to be instantiated at
>startup.
>I'm not sure who should do it, libRoadRunner or the application using
>libRoadRunner. If I do it I need to know the name of it, ie 'cvode'. In
>which case it is probably better if libroadrunner instantiates a
>default
>(cvode) integrator at startup.
>
>H
>
>On Mon, Aug 3, 2015 at 6:08 PM, Kyle Medley <notifications@github.com>
>wrote:
>
>> The initial CVODE integrator isn't instantiated until a model is
>loaded. I
>> made getCurrentIntegratorName return an empty string in the case
>where no
>> integrators have been instantiated, in roadrunner 1.3.10:
>>
>>
>http://sourceforge.net/projects/libroadrunner/files/libroadrunner-1.3.10/alpha/roadrunner-1.3.10-vs12-llvm-3.5-win32.zip/download
>>
>> I can also provisionally instantiate a CVODE integrator whenever a
>> roadrunner instance is created if you like. Please let me know.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/sys-bio/roadrunner/issues/166#issuecomment-127445376>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/166#issuecomment-127447871

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
Fixed in latest release.
