### ISSUE TITLE
RK4 parameter errors?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#167]
A couple of questions on the RK4 parameter descriptions which don't look quite right..

1. multiple_steps: (bool) Perform a multiple time step simulation. - what does this mean?

2. initial_time_step: (double) Specifies the initial time step size. If inappropriate, CVODE will attempt to estimate a better initial time step.
  
This suggests that rk4 will switch to cvode if initial time step is 'inappropriate'. It shouldn't switch and what does inappropriate mean?

3. maximum_step_size: (double) The maximum absolute value of step size allowed - I assume zero means no max step size? But why have a max step size in the first place since rk4 isn't a variable step size method.

4. Maximium_num_steps: (int) Maximum number of steps to be taken by the CVODE solver in its attempt to reach tout.

This doesn't make sense, rk4 has nothing to do with cvode. Probably spurious parameter?

**Comment by 0u812** [comment]
Sorry, I copied over some CVODE parameters. It looks like none of these are needed, hence RK4 has no settings. In 1.3.13 binaries which I just sent you.

**Comment by hsauro** [comment]
Ok good, I'm going to look another look at the integrator switch bug.

H

**Comment by hsauro** [comment]
The rk4 switching bug seems to be something odd happening on my side. Not
quite sure but switching from a modal dialog box to a non-modal dialog box
solved the problem.

H
