### ISSUE TITLE
Bug in switching solvers

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#168]
There is a bug when switching solvers:

1. Load a model, eg feedback.xml
2. Switch to rk4
3. Run simulation 
4. Looks like no results are returned.

Workaround:

1. Load a model, eg feedback.xml
2. Switch to rk4
3. Call reset()
3. Run simulation 
4. Results look ok.

Summary, should not need to call reset to make the new integrator work. Not only that but the new integrator should be able to continue where the previous one left off in which case reset() is the wrong thing to do.

**Comment by 0u812** [comment]
Not currently able to reproduce this on my end. Will try making a simpler test harness later. Here's the current one (I commented out the reset before RK4 and it still passed):
https://github.com/sys-bio/roadrunner/blob/develop/wrappers/C/ApiTest/main.c

**Comment by hsauro** [comment]
I'll have to investigate more, there may be more calls being made that I'm
not accounting for.

H

**Comment by hsauro** [comment]
Problem at the Delphi end due to use of modal dialog box.
