### ISSUE TITLE
HudsonModel doesn't match what Copasi gets

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#174]
The HudsonbModel appears to behave differently in Copasi and libRoadRunner.The Copasi settings are:

Rel Tol: 1E-6
Rel Tol 1E-12
Max steps : 10000

Run the model in Matlab or Mathematica (UW has a free licence) to check if they can create a solution.

The model is given by:

r=te.loada('''
    i'=k2*x2-k1*i*e;
    e'=k2*x2-k1*i*e+k4*x1-k3*x2*e;
    x1'=k3*x2*e-k4*x1;
    x2'=k1*i*e-k2*x2+k4*x1-k3*x2*e;
    
    i=1e8; e=1e10; k1=3e4; x1=0; k2=4e-1; k3=3e5; k4=0.0002; x2=0
''')
result=r.simulate(0, 1, 100, ['time', 'x1', 'x2'], stiff=True)
r.plot(result)

**Comment by 0u812** [comment]
Resolved in 1.3.19
