### ISSUE TITLE
Docs for simulation options out of date

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#177]
The Python docs for libroadrunner and the new ways to get and set options is not avialble in the docs. update the new docs. Talk to Kylle about the new syntax.

**Comment by 0u812** [comment]
I effectively removed all simulateOptions references from the docs. I don't think we want people to use it at all.

**Comment by 0u812** [comment]
Added docs: http://sys-bio.github.io/roadrunner/python_docs/using_roadrunner.html#solvers
