### ISSUE TITLE
Possible bug in getAvailableTimeCourseSymbols C API

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#181]
Maybe a bug in teh C API getAvailableTimeCourseSymbols:

1. Load empty model, no species or reactions
2. Call getAvailableTimeCourseSymbols from C API
3. This returns a list, it claims that there are two elements in the list, first item is a string:
'Floating Species', but the second item is nil. Why is the second item a nil? What should this call
return for an empty model?

**Comment by 0u812** [comment]
Fixed so that we only return a list with a single element (i.e. a heading)
```
  Floating Species   
  Boundary Species   
  Floating Species (amount)   
  Boundary Species (amount)   
  Global Parameters   
  Fluxes   
  Rates of Change   
  Volumes   
  Elasticity Coefficients   
  Unscaled Elasticity Coefficients   
  Eigenvalues
```

Previously, each category had one heading and a null element.
