### ISSUE TITLE
Add empty model test to the C API Python test suite

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#182]
Add an empty model to the Python C API test suite. An empty model is one that has no species or reactions, just one compartment. Should be easy to make one using simpleSBML.

**Comment by kirichoi** [comment]
What are you trying to test here? Simulating empty model?

**Comment by hsauro** [comment]
Not simulating, but it should return sensible results when calling the API,
eg it should return no floating species.

**Comment by kirichoi** [comment]
Got it, will create a test testing values returned from i.e. getFloatingSpeciesIds()

**Comment by kirichoi** [comment]
Added simple test using model with a single compartment only in commit 3b234d9cc97df214cf6ff168cf3085de71d35351. Currently, it runs five tests. Will add more later.
