### ISSUE TITLE
Bug in char * getCurrentIntegratorNthParameterName (RRHandle handle, int n)

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#185]
The C API method char * getCurrentIntegratorNthParameterName (RRHandle handle, int n) appears to ignore the n value in the argument. No matter what value you pass in n, the method always returns the first 0th parameter name. It should of course return the nth parameter name.

**Comment by 0u812** [comment]
Fixed this in https://github.com/sys-bio/roadrunner/releases/tag/1.3.21a, didn't bump version.
