### ISSUE TITLE
Change order of parameters in integrator parameter list

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#187]
I noticed that the order of integrator parameters is not optimal for display. For example while relative tolerance is the first in the list, absolute tolerance is the last. So when displaying them the relative and absolute tolerances are not next to each other which for convenience they probably should be. The order should probably be:

relative
absolute
stiff
max bdf order
max adams order
max num steps
max time step
min time step
initial time step
multiple steps
variable step size

**Comment by 0u812** [comment]
There is no order, it can be different each time. If it's possible for you to sort alphabetically, that might be the best option. If you like I can implement that in rr.

On September 1, 2015 12:19:20 PM PDT, Herbert Sauro <notifications@github.com> wrote:
>I noticed that the order of integrator parameters is not optimal for
>display. For example while relative tolerance is the first in the list,
>absolute tolerance is the last. So when displaying them the relative
>and absolute tolerances are not next to each other which for
>convenience they probably should be. The order should probably be:
>
>relative
>absolute
>stiff
>max bdf order
>max adams order
>max num steps
>max time step
>min time step
>initial time step
>multiple steps
>variable step size
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/187

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
That's a pity, I can sort easily the list my end. How are the names stored
in rr?

H

**Comment by hsauro** [comment]
Changed my mind, I think rr should sort the list so that the both the list
and nth methods are consistent. I'll add to github.

H

**Comment by 0u812** [comment]
unordered_map, pretty standard these days, so good for maintainability.

On September 1, 2015 12:56:40 PM PDT, Herbert Sauro <notifications@github.com> wrote:
>That's a pity, I can sort easily the list my end. How are the names
>stored
>in rr?
>
>H
>
>On Tuesday, September 1, 2015, Kyle Medley <notifications@github.com>
>wrote:
>
>> There is no order, it can be different each time. If it's possible
>for you
>> to sort alphabetically, that might be the best option. If you like I
>can
>> implement that in rr.
>>
>> On September 1, 2015 12:19:20 PM PDT, Herbert Sauro <
>> notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>> >I noticed that the order of integrator parameters is not optimal for
>> >display. For example while relative tolerance is the first in the
>list,
>> >absolute tolerance is the last. So when displaying them the relative
>> >and absolute tolerances are not next to each other which for
>> >convenience they probably should be. The order should probably be:
>> >
>> >relative
>> >absolute
>> >stiff
>> >max bdf order
>> >max adams order
>> >max num steps
>> >max time step
>> >min time step
>> >initial time step
>> >multiple steps
>> >variable step size
>> >
>> >
>> >---
>> >Reply to this email directly or view it on GitHub:
>> >https://github.com/sys-bio/roadrunner/issues/187
>>
>> --
>> Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/sys-bio/roadrunner/issues/187#issuecomment-136839412>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/187#issuecomment-136841166

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
But I assume they are only used if you have large lists that need to be
searchable but not ordered? If its just a short list then one could use a
simple vector and keep order?

H
