### ISSUE TITLE
Sort solver parameter lists

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#188]
The parameter lists supported by the various solvers should be sorted alphabetically. This is to ensure that the order of parameters coming back is always the same. Sorting within rr will also make sure that the two methods:

getListOfIntegratorParameterNames

and

getCurrentIntegratorNthParameterName

are consistent.

**Comment by 0u812** [comment]
I have some new binaries that do this, I went ahead and refactored the solver API yet again so now it uses a single base class as we have discussed several times. Please let me know if these binaries work for you:
https://github.com/sys-bio/roadrunner/releases/tag/1.3.22

**Comment by hsauro** [comment]
ok will give it a go. See latest possible bug
in libGetCurrentSteadyStateSolverNthParameterName.

H

**Comment by 0u812** [comment]
Don't know what you mean by libGetCurrentSteadyStateSolverNthParameterName, but the lists are definitely sorted now so I will close this. Please submit a bug report for the other thing if it's still a problem.

**Comment by hsauro** [comment]
Ok.

H
