### ISSUE TITLE
Inconsistency in hint format

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#190]
The format for the hint strings in the integrator and steady state solver are different. The integrator hint strng has the structure:

message (type)

The structure of the steady state hint is (note type is at the front of the message):

(type) message

The steady state solver hints should be changed to be consistent with the integrator hints, the the (type) should be at the end of the hint.

**Comment by 0u812** [comment]
I just checked NLEQ vs. CVODE and they are consistent. In the description, however, the order is reversed.
Hint:
"text... (type)"
Desc:
"(type) text..."
