### ISSUE TITLE
Possible bug in getConservedMoietyIds()

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#192]
Run the following model:

import tellurium as te
import roadrunner

r = te.loada ('''

 A -> B; k1*A
 B -> A; k2*B;
 A = 1.000000;
 B = 1.000000;
 k1 = 1.616878;
 k2 = 3.549014;
 ''')
 
m = r.simulate (0, 100, 100)
print r.getConservedMoietyIds()
 
m = r.simulate (0, 100, 100)
print r.getConservedMoietyIds()

Output: []

I think the output should be the names of the moiety Ids, in this case B, C and D. The call however returns an empty string.

**Comment by 0u812** [comment]
"I think the output should be the names of the moiety Ids, in this case B, C and D"
Not sure I follow where C and D should be coming from.

**Comment by 0u812** [comment]
I think it would just be B in this model.

**Comment by 0u812** [comment]
If I understand what a conserved moiety is, we already have a function to do this, which I just added in #96: getDependentFloatingSpecies:
```
import tellurium as te
import roadrunner

r = te.loada ('''

A -> B; k1A
B -> A; k2B;
A = 1.000000;
B = 1.000000;
k1A = 1.616878;
k2B = 3.549014;
''')

m = r.simulate (0, 100, 100)

print('All species: {}'.format(r.getFloatingSpeciesIds()))
print('Independent species: {}'.format(r.getIndependentFloatingSpeciesIds()))
print('Dependent species: {}'.format(r.getDependentFloatingSpeciesIds()))
```

Output:
```
All species: ['A', 'B']
Independent species: ['A']
Dependent species: ['B']
```
