### ISSUE TITLE
Possible bug in r.getConservedMoietyValues()

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#193]
Run the following model:

import tellurium as te
import roadrunner

r = te.loada ('''

 A -> B; k1*A
 B -> A; k2*B;
 A = 1.000000;
 B = 1.000000;
 k1 = 1.616878;
 k2 = 3.549014;
 ''')
 
m = r.simulate (0, 100, 100)
print r.getConservedMoietyIds()
 
m = r.simulate (0, 100, 100)
print r.getConservedMoietyValues()

Output: Out[6]: array([], dtype=float64)

Don't understand output, thought it would be an array of values.

**Comment by 0u812** [comment]
It used to redirect to an implementation in ExecutableModel, which was apparently incomplete. I reverted it back to the original libstruct implementation which seems to work.
