### ISSUE TITLE
All current bugs upto #193 fixed by end of September for COMBINE

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#194]
All libRodRunner bugs labelled COMBINE should fixed by end of september for COMBINE and be ready for the 1.2.4 Telluirum release. This should include Windows and Mac versions.

**Comment by 0u812** [comment]
All COMBINE bugs are fixed. Sure feels good to say that!

**Comment by hsauro** [comment]
Excellent news.

Herbert
