### ISSUE TITLE
getAvailableTimeCourseSymbols does not return the elasticity symbols, it should

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#196]
getAvailableTimeCourseSymbols should return the elasticity symbols, currently it doesn't but it should. This is an enhancement.

**Comment by 0u812** [comment]
It looks like it returns "Elasticity Coefficients", are those not the right symbols?

**Comment by 0u812** [comment]
They appear to be zero. Is that the problem? Can you explain what the error is exactly?

**Comment by hsauro** [comment]
This isn't urgent, when I see you I'll explain.

H

**Comment by 0u812** [comment]
It returns symbols like `EE:J0,Node1`, but when you try to set them as `RoadRunner.steadyStateSelections` or `RoadRunner.timeCourseSelections` it says `invalid selection string EE:J0,Node1`.

**Comment by hsauro** [comment]
Make the elasticity ids consistent across setvalue/getvalue and get getAvailableTimeCourseSymbols 
Kyle with fix 15 Feb 2017

**Comment by kirichoi** [comment]
Deprecated function.
