### ISSUE TITLE
The following code does not produce expected result

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#197]
The following code should produce a square wave but it doesn't

import tellurium as te

r = te.loada('''
function squareWave(time_, period, center, amplitude)
  amplitude*(sin((2*3.1414926*time_)/period) > 0) + center;
end

  J0: $Node0 => $Node1; squareWave(time, 1, 5, 2);

  // Species initializations:
  Node0 = 0;
  Node1 = 0;
end
''')

m = r.simulate (0, 100, 500, ['time', 'J0'])
r.plot()

**Comment by hsauro** [comment]
This could simply be due to either out of date libroadrunner of libroadrunner not picking on the conf file. I'm reallocating it to Kiri.

**Comment by 0u812** [comment]
Given that, as @luciansmith already pointed out, this is not strictly valid SBML, can we please just allow Tellurium to reject it by default? It's going to be a major headache if I have to support people doing things which are not allowed in standard SBML.

I thought the original rationale behind accepting this behavior in some cases was to allow legacy JDesigner models. Please let's not make it the default, I don't want to encourage people to start writing non-standard SBML.

**Comment by hsauro** [comment]
Which is the bit that is not standard? I'm passing time as an argument so
that should be ok?

H

**Comment by 0u812** [comment]
It's using the greater than symbol in a scalar expression.

On September 25, 2015 12:37:02 PM PDT, Herbert Sauro <notifications@github.com> wrote:
>Which is the bit that is not standard? I'm passing time as an argument
>so
>that should be ok?
>
>H
>
>On Fri, Sep 25, 2015 at 12:22 PM, Kyle Medley
><notifications@github.com>
>wrote:
>
>> Given that, as @luciansmith <https://github.com/luciansmith> already
>> pointed out, this is not strictly valid SBML, can we please just
>allow
>> Tellurium to reject it by default? It's going to be a major headache
>if I
>> have to support people doing things which are not allowed in standard
>SBML.
>>
>> I thought the original rationale behind accepting this behavior in
>some
>> cases was to allow legacy JDesigner models. Please let's not make it
>the
>> default, I don't want to encourage people to start writing
>non-standard
>> SBML.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/sys-bio/roadrunner/issues/197#issuecomment-143330304>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/197#issuecomment-143333110

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
But that's used a lot  (not just by JDesigner) and the restriction is in
any case being relaxed in L3/2 I don't think there is anything you have to
do at this stage,  we just call setConfig in jdesigner and tellurium to
relax the restriction.

H

**Comment by 0u812** [comment]
If it's important to support such models, then we can certainly make do. For the record, my main concern is that it is tacitly assumed throughout the LLVM code generator that a ">" operator is a Boolean, and it will break whenever that assumption is violated. I patched the immediate problem, but there are probably other places in the code where it comes up.

There might be some future bugs related to this but it's nothing we can't handle. @kirichoi, I think to resolve this issue all you need to do is produce a new Tellurium release, which you were probably planning on doing anyway. I will set the "permissive" option to "on" by default so you don't need to include a config file.

**Comment by luciansmith** [comment]
My understanding was that you had some sort of patch to treat everything
everywhere as a double, and then needed to go back and patch the other side
of things, so that anything that expected a boolean would work with a
double.  Will that still work?

I wouldn't worry about the invalid SBML aspect of this, since it was not an
official validation error in l2v1 (through an oversight), and won't be an
error again in L3v2 (due to a deliberate design change).

**Comment by 0u812** [comment]
@luciansmith yes but I suspect I haven't located all the instances where the code generator expects a Boolean. I'm going to construct some tests for Boolean use, if you have any expressions that expect a Boolean as an argument please add them to #201. Thanks!

**Comment by 0u812** [comment]
Resolution to this issue is to produce a new Tellurium release, which we're planning on doing before COMBINE.
