### ISSUE TITLE
What is the error condition on double getConfigDouble (const char* key)	

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#199]
What is the error condition on:

double getConfigDouble	(const char* key)	

I assume you meant to define it as:

int getConfigDouble	(const char* key, double *value)	

Same for the other getConfig methods. OR should there an error condition?

**Comment by 0u812** [comment]
Sets error on failure, please see http://sys-bio.github.io/roadrunner/c_api_docs/html/group__config.html#ga22a14b4d4a38b8f70b181600eea85afb
