### ISSUE TITLE
Add method to get list of all config keys

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#200]
Add a method to get a list of all the names of the configuration keys.

eg

RRStringArrayPtr  getListOfConfigKeys (RRHandle handle);

Are configs instance specific or global? I noticed you don't pass rrHandle to set and getConfig methods.

**Comment by 0u812** [comment]
Configs are global, hence no rrHandle.

**Comment by 0u812** [comment]
See http://sys-bio.github.io/roadrunner/c_api_docs/html/group__config.html#ga1a1ed70f4b55da8fd36909dad2ad9477
