### ISSUE TITLE
Non-physical behavior near zero copy number for SSA

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#215]
The Gillespie simulator allows the copy numbers of molecules to go negative, which should not happen.

**Comment by luciansmith** [comment]
There's no reason to require species to not go negative in the simulator,
since some models are modelling things that can actually go negative like
charge or debt.  A warning is probably appropriate, though.

**Comment by 0u812** [comment]
True, but some models like the Mycoplasma whole-cell model apparently rely on the simulation algorithm stopping reactions before the copy number can go negative, so I'll put it behind a config flag.

**Comment by hsauro** [comment]
In that case its a bad model. The biophysics should be correct so that
concentration will naturally not go negative. It means the model is not a
good physical representation.

H

**Comment by 0u812** [comment]
Fixed. Python syntax is:
```
r.getIntegrator().setValue('nonnegative', True)
```

**Comment by luciansmith** [comment]
I have to agree that that is a crappy model, and not an issue with the
simulator.  And in fact, I'm not convinced that adding a special option
that makes the simulator behave incorrectly in response is a good solution,
as the model will continue to be unexchangeable, and exchangeability is
kind of the whole point of SBML, etc.

However, I could see a translator from that crappy model to a slightly
better (but still unrealistic) model that converted reaction rates from:

f(x,y)

to:

piecewise(0, S1<=0, f(x,y))

-Lucian
