### ISSUE TITLE
SBML rate rules not working correctly? (steady state)

### ISSUE THREAD

**Issue by andreadega** [sys-bio/roadrunner#217]
Dear all,

thank you very much for developing roadrunner, we find it very useful for our systems biology software. I would like to bring to your attention an issue that I met recently and that I hope you can help me with. I wrote a small example to reproduce my problem. I built a simple model with rate rules and assignment rules. Steady state should be pS = 0.25, but I simply get 0 or any initial value I set pS to be.

Thank you in advance for your help,
Andrea

![notebook1](https://cloud.githubusercontent.com/assets/15123971/10483090/38352de6-7275-11e5-8807-94c516ded508.jpg)
![notebook2](https://cloud.githubusercontent.com/assets/15123971/10483091/38354fec-7275-11e5-9e66-5f443fdc48a5.jpg)
![notebook3](https://cloud.githubusercontent.com/assets/15123971/10483093/3839f15a-7275-11e5-937d-6fa4c8697c1f.jpg)
![notebook4](https://cloud.githubusercontent.com/assets/15123971/10483092/38388aea-7275-11e5-8994-b05f1bdef7f0.jpg)

**Comment by 0u812** [comment]
Hi Andrea, steady state calculations currently don't include rate rules. I'll look into implementing it.

**Comment by andreadega** [comment]
Thanks a lot for your quick reply.
I was quickly looking at roadrunner code and I wonder what could be missing. The StateVectorRate seems to be set correctly, but maybe not the StateVector? That seem to to update.

**Comment by 0u812** [comment]
Jean-Marie is also waiting on this issue. I prioritized this and deprioritized some other issues.

**Comment by 0u812** [comment]
I made some progress. Roadrunner now gives values identical to COPASI for Jean-Marie's model. However, COPASI makes a good point in the warning message for rate-rule models. If the rate rules are explicitly time dependent, it's meaningless to try and calculate the steady state.

**Comment by 0u812** [comment]
See #302
