### ISSUE TITLE
Placeholder for single variable step integration

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#221]

**Comment by 0u812** [comment]
@matthiaskoenig, I implemented a fix, does this work for you?

**Comment by matthiaskoenig** [comment]
Works. Thanks so much.

On Wed, Oct 14, 2015 at 10:29 PM, Kyle Medley <notifications@github.com>
wrote:

> @matthiaskoenig <https://github.com/matthiaskoenig>, I implemented a fix,
> does this work for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/roadrunner/issues/221#issuecomment-148186462>.
>



-- 
--------------------------------------------------------------
Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450528449
Tel: + 49 176 81168480
--------------------------------------------------------------

**Comment by 0u812** [comment]
Great! Please re-open if you run into problems with this feature.
