### ISSUE TITLE
Automatically put current SBML model when RoadRunner.getParamPromotedSBML is called.

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#222]
In Python wrapper, there is a getParamPromotedSBML method under RoadRunner class. It might be sensible to try to automatically put currently loaded model as an argument and raise exception when the model is empty.

**Comment by 0u812** [comment]
Not sure I understand. The function currently takes one argument: an SBML string. Are you saying you want to overload the function so that if no args are passed it uses the current model?

**Comment by luciansmith** [comment]
Closing this--if nobody else has had an issue with the function, I think we're probably good.
