### ISSUE TITLE
Remove RoadRunner.start, RoadRunner.end

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#223]
These properties cause confusion with the correct way of setting start/end via simulateOptions:

```
# correct way:
r.simulateOptions.start = 0
r.simulateOptions.end = 20
# incorrect way:
r.start = 0
r.end = 20
```

Moreover, `RoadRunner.start` and `RoadRunner.end` appear to be non-functional, so they are slated for removal.

**Comment by CiaranWelsh** [comment]
Stale so I'm closing.
