### ISSUE TITLE
getValue doesn't recognize [X] syntax for concentration

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#226]
It may be the case the getValue in the C API doesn't recognize [X] for concentration.

**Comment by 0u812** [comment]
It just delegates to RoadRunner::getValue, so it should have the same behavior as all other APIs. Is it returning the wrong value for you? Can I see the model?

**Comment by hsauro** [comment]
It returns unrecognized variable. Haven't tried it in tellurium however.

H

**Comment by 0u812** [comment]
Could I have the model you're using it with?

On November 2, 2015 8:47:09 AM PST, Herbert Sauro <notifications@github.com> wrote:
>It returns unrecognized variable. Haven't tried it in tellurium
>however.
>
>H
>
>On Sunday, November 1, 2015, Kyle Medley <notifications@github.com>
>wrote:
>
>> It just delegates to RoadRunner::getValue, so it should have the same
>> behavior as all other APIs. Is it returning the wrong value for you?
>Can I
>> see the model?
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/sys-bio/roadrunner/issues/226#issuecomment-152920825>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/226#issuecomment-153079308

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
Not reproducibly at the python console. Will reinvestigate and create a new issue if I find somewith with better evidence. Closing this one.

**Comment by hsauro** [comment]
I can't reproduce it at the python console. I will revisit it it my Delphi
code. I just closed it as non-reproducible. I'll reopen a new one with more
details when I have them.

The main bug is the possible Jacobian bug I found yesterday.

Herbert
