### ISSUE TITLE
Bug in freeVector in C API when vector is empty

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#238]
Someone sent me a model (a biomodels model) that crashed pathwaydesigner. I checked it and noticed the model has no floating species. In pathwaydesigner I call the function getFloatingSpeciesConcentrations. This returns a RRVectorPtr which has a count and a pointer to an array of double. If there are no floating species then the count is 0 and the array is empty. When I call freeVector on an empty RRVectorPtr I get a hard crash (system exception from windows). Is this because it is trying to free an empty array of double? 

I can't even protect myself on the Delphi side by trying to catch the exception so its a bit of a show stopper. Also the exception handling within roadrunner doesn't seem to help. This is the freeVector code:

int rrcCallConv freeVector(RRVectorPtr vector)
{
    start_try
        if(vector)
        {
           delete [] vector->Data;
        }
        return true;
    catch_bool_macro
}

The model in question is from biomodels: 

 https://www.ebi.ac.uk/biomodels-main/MODEL1006230090

I also noticed libroadrunner is quite slow at loading this model.

**Comment by 0u812** [comment]
Should work now, binaries are available from http://sourceforge.net/projects/libroadrunner/files/alpha/roadrunner-alpha-112715.zip/download

**Comment by hsauro** [comment]
Thanks!

H
