### ISSUE TITLE
Incorrect simulation output

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#241]
From @matthiaskoenig:

Hi all,

something is really broken in roadrunner (version 1.4.1).
The attached model does not integrate at all, whereas Copasi & JWS online have no problem.
I rebuild roadrunner 1.4.1, all roadrunner tests are passing, but the ODE integration is still completely wrong.
```
import roadrunner
rr = roadrunner.RoadRunner("./galactose_28_annotated.xml")
s = rr.simulate(0, 50, 1000, plot=True)
```

![copasi_output](https://cloud.githubusercontent.com/assets/7672320/11612125/115738da-9ba2-11e5-9b2b-e3aaa92564fb.png)
![roadrunner_output](https://cloud.githubusercontent.com/assets/7672320/11612127/15adc1e2-9ba2-11e5-94ee-61e288612ccf.png)

**Comment by 0u812** [comment]
Fix via setting abs tolerance to 1e-17

**Comment by hsauro** [comment]
These tolerances seem a bit extreme even if they do work. Sounds like a
some suspicious is going on.
Herbert
