### ISSUE TITLE
Integrator::toString() not listing integrator Settings

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#248]
When printing roadrunner information, the integrator settings are not listed:
```
print(r.getIntegrator())
print('-'*80)
print(r)
```
This is important when printing the integrator, or also in printing the roadrunner object. Analogue to the simulationOptions also the integrationOptions have to be displayed.

```
< roadrunner.Integrator() >

--------------------------------------------------------------------------------
<roadrunner.RoadRunner() { 
'this' : 0x2bdc550
'modelLoaded' : true
'modelName' : galactose_29
'libSBMLVersion' : LibSBML Version: 5.11.0
'jacobianStepSize' : 1e-05
'conservedMoietyAnalysis' : false
'simulateOptions' : 
< roadrunner.SimulateOptions() 
{ 
'this' : 0x2a88500, 
'reset' : 0,
'structuredResult' : 0,
'copyResult' : 1,
'steps' : 50,
'start' : 0,
'duration' : 1000
}>, 
'integrator' : 
< roadrunner.Integrator() >

}>

```

**Comment by matthiaskoenig** [comment]
In addition a function integrator::toRepr is missing for the integrator function analog to SimulateOptions::toRepr() described here
```
		/**
		* get a description of this object, compatable with python __str__
		*/
		std::string toString() const;

		/**
		* get a short descriptions of this object, compatable with python __repr__.
		*/
		std::string toRepr() const;
```

The following code in SimulateOptions::toString() belongs into the base class BasicDictionary::toString() for reusibility and should be called from SimulateOptions::toString().
```
		std::vector<std::string> keys = getKeys();

		if (keys.size() > 0) {
			ss << "," << std::endl;
		}

		for (std::vector<std::string>::iterator i = keys.begin(); i != keys.end(); ++i)
		{
			ss << "'" << *i << "' : ";
			ss << getItem(*i).toString();

			if (std::distance(i, keys.end()) > 1) {
				ss << ", " << std::endl;
			}
		}
```

**Comment by matthiaskoenig** [comment]
It would be nice if all the commented out code is deleted from files. For instance in 
rrRoadRunnerOptions.cpp & rrRoadRunnerOptions.h
half of the options are obsolete. It is unclear what commented out means:
* is this not yet implemented?
* was this implemented and is now not any more?
* is this still important or will it be important again?
For someone reading the code it is just very confusing.

With the use of git if you have to go back to an earlier version, you always can make a diff against earlier versions, to see what was removed. Otherwise this is only distracting.

**Comment by hsauro** [comment]
Agreed.

Herbert

**Comment by hsauro** [comment]
Agreed.

Herbert

**Comment by hsauro** [comment]
Agreed

Herbert
