### ISSUE TITLE
Add test for default number of steps in simulate call == 50

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#252]

**Comment by 0u812** [comment]
Boom build is broken. Please see https://travis-ci.org/sys-bio/roadrunner/builds/103237638 for more info. If you could look at the build output and see what went wrong and make a new branch for this fix that would be great. When you're ready to merge this in, please create a pull request. Please don't commit to develop directly. Thanks!

**Comment by kirichoi** [comment]
It's not passing the default time step test. It seems like the default step is not set to 50?

**Comment by kirichoi** [comment]
I am guessing this is a Python issue since I do not see any indication that default step is set to 50 from Python. I will push a fix.

**Comment by matthiaskoenig** [comment]
Hi Kiri, you can see the default step in the integrator options.
Just print the roadrunner or integrator object

r = roadrunner.RoadRunner(model)
print(r)
print(r.getIntegrator())

On Tue, Jan 19, 2016 at 3:58 AM, Kiri Choi <notifications@github.com> wrote:

> I am guessing this is a Python issue since I do not see any indication
> that default step is set to 50 from Python. I will push a fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/roadrunner/issues/252#issuecomment-172723292>.
>



-- 
Matthias König
Email: konigmatt@googlemail.com
Tel: + 49 30 20938450
Tel: + 49 176 81168480
  https://www.livermetabolism.com/contact.html
Humboldt-University Berlin, Institute for Theoretical Biology, Junior Group
König
Charité Berlin, Institute of Biochemistry, Computational Systems
Biochemistry <http://www.charite.de/sysbio/people/koenig/>

**Comment by kirichoi** [comment]
Fixed through 14ead69356c877e1af90185495a044ec0887e6bd
