### ISSUE TITLE
Naming of integrator settings functions is not consistent

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#253]
One can get the possible settings of an integrator via
```
integrator.getSettings()
```
But the setting of the setting is done via
```
integrator.setValue()
```
Solution 1: setting via 
```
integrator.setSetting()
```
Solution 2: be able to get the values via
```
integrator.getValues()
```
The method names should be consistent. I just searched quit a lot for finding the possible values of an integrator until I realized that they are available via getSettings.
This is important if one forgets how the settings were called exactly.

**Comment by 0u812** [comment]
I'd like to keep the original methods because a lot of existing code depends on them, but I added `getSetting` and `setSetting` aliases to the Python solver API so code like `integrator.setSetting('...', 123)` will work.

**Comment by matthiaskoenig** [comment]
Perfect. Thanks.

On Tue, Jan 12, 2016 at 8:12 PM, Kyle Medley <notifications@github.com>
wrote:

> I'd like to keep the original methods because a lot of existing code
> depends on them, but I added getSetting and setSetting aliases to the
> Python solver API so code like integrator.setSetting('...', 123) will
> work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/roadrunner/issues/253#issuecomment-171019607>.
>



-- 
Matthias König
Email: konigmatt@googlemail.com
Tel: + 49 30 20938450
Tel: + 49 176 81168480
  https://www.livermetabolism.com/contact.html
Humboldt-University Berlin, Institute for Theoretical Biology, Junior Group
König
Charité Berlin, Institute of Biochemistry, Computational Systems
Biochemistry <http://www.charite.de/sysbio/people/koenig/>
