### ISSUE TITLE
Add test for variable time step end time == expected end time

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#255]
In the absence of passing `steps` to simulate, test the endpoint and make sure it corresponds to the expected end time.

Test the following methods of setting variable stepping:
* Via a keyword argument to `simulate`
* ~~Via a positional argument to `simulate`~~
* Via the integrator interface

**Comment by 0u812** [comment]
Actually it looks like there isn't a positional argument to `simulate` for setting variable stepping. Edited original post.

**Comment by kirichoi** [comment]
Fixed in 018542623685ae2bb2a33962aeac2e0f3ae02b4e
