### ISSUE TITLE
Return <type 'NamedArray'> instead of <type 'numpy.ndarray'> for most r.model functions

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#258]
For all numeric arrays which are available from roadrunner these should be returned with the corresponding names/ids, i.e. return the NamedArray instead of the blank numpy.ndarray. Like for instance done with simulationResult.

Currently, one always has to lookup the names for arrays/matrices.

For instance:

```
volumes = r.model.getCompartmentVolumes()
# requires subsequent call to
ids = r.model.getCompartmentIds()
```

which gives the separate information

```
['e', 'c', 'm']
[  1.00000000e-06   1.00000000e-06   1.00000000e+00]
```

Just return a named array which allow the extremely useful access via id

```
volumes['c']
```

Same for almost all functions in

```
r.model.get*Ids()
r.model.get*Something()
```

This will make the work with the returned matrices & arrays so much easier.

**Comment by matthiaskoenig** [comment]
Also applies to things like steadyStateValues which should be packed with r.selections
```
print(r.selections)
print(r.getSteadyStateValues())

['time', 'bA', 'bB', 'bC', 'v1', 'v2', 'v3', 'v4']
[ 0.59225087  1.11869105  3.29028969  1.11869732  3.29028623  0.59225152]
```

**Comment by matthiaskoenig** [comment]
I mean ``` r.steadyStateSelections ```.

**Comment by hsauro** [comment]
Agreed, this was on the list of things to do but appears to have been
missed. Same applies to all the other matrices that are returned.

H
