### ISSUE TITLE
Compute rates of change for all species when moiety conserved cycles active

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#26]
Compute rates of change for all species when moiety conserved cycles active

**Comment by hsauro** [comment]
Kyle, this needs checking if it is still an issue or not.

**Comment by 0u812** [comment]
Needs to be tested

**Comment by 0u812** [comment]
Looks like this is already working. Consider the following model:
```
import tellurium as te

myModel = '''

# Conversion of S1 to S2 at rate k1*S1

S1 -> S2; k1*S1;


# Initial values

S1 = 10; S2 = 0


# Parameter definition

k1 = 0.1;

'''

rr = te.loada(myModel)

result = rr.simulate(0, 40, 40)

#te.plot(rr, result)

print('All species: {}'.format(rr.getFloatingSpeciesIds()))
print('Independent species: {}'.format(rr.getIndependentFloatingSpeciesIds()))
print('All rates of change: {}'.format(rr.model.getFloatingSpeciesAmountRates()))
```

The output is:
```
All species: ['S1', 'S2']
Independent species: ['S1']
All rates of change: [-0.01831804  0.01831804]
```

Hence, we get all rates of change, even for the dependent species (and those rates are equal & opposite like we would expect). I added a convenience function to the RoadRunner class:
```
RoadRunner.getFloatingSpeciesAmountRates
```

Do you think you will need a function for concentrations too? Please reopen if yes.

**Comment by hsauro** [comment]
Switch on conservation analysis before loading the model, by default it is off. 

Herbert

**Comment by 0u812** [comment]
reopened wrong issue
