### ISSUE TITLE
Table of simulate options is wrong

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#263]
Test where steps option works correctly in simulate call. See Running Simulations in Basic Tutorial.

Do we have tests for all the options?

**Comment by kirichoi** [comment]
The positional argument works fine (i.e. rr.simulate(0,10, 100) will return exactly 100 time points). However, keyword argument `steps` does not follow the same convention.

**Comment by kirichoi** [comment]
Simulate option on `steps` works as intended.
