### ISSUE TITLE
Stiff problem with variable_step_size=True and stiff=False uses up all system memory

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#269]
I am simulating my large-scale models normally with variable_step_size=True & stiff=True. Out of curiosity I wanted to see if the stiff=False solver can handle the model and what the runtime difference would be. 
If using the combination variable_step_size=True & stiff=False, all system memory is used up.

Model:
`https://raw.githubusercontent.com/matthiaskoenig/multiscale-galactose/develop/python/multiscalepy/multiscale/examples/models/galactose/Galactose_v128_Nc20_dilution.xml`

```{Python}
import roadrunner
from roadrunner import SelectionRecord

def time_it(func, *args, **kwargs):
    """ Time the call to the function. """
    time_start = time.time()
    res = func(*args, **kwargs)
    print('Time: {}'.format(time.time() - time_start))
    return res

# import multiscale.examples.testdata as testdata
print(test_sbml)

# 31s, reload 2.7s (core), 
r = time_it(roadrunner.RoadRunner, test_sbml)
integrator = r.getIntegrator()

# set integrator settings
rel_tol = 1E-6
abs_tol = 1E-6 * min(r.model.getCompartmentVolumes())
integrator.setValue('absolute_tolerance', abs_tol)
integrator.setValue('relative_tolerance', rel_tol)
tend = 1000

# working
print('*** stiff=True, variable_step_size=False ***')
integrator.setValue('stiff', True)
integrator.setValue('variable_step_size', False)
print(integrator)
r.reset(SelectionRecord.ALL)
time_it(r.simulate, start=0, end=tend, steps=1000)

# working
print('*** stiff=True, variable_step_size=True ***')
integrator.setValue('stiff', True)
integrator.setValue('variable_step_size', True)
print(integrator)
r.reset(SelectionRecord.ALL)
time_it(r.simulate, start=0, end=tend, steps=1000)

# uses up all the available memory & brings the server down!
print('*** stiff=False, variable_step_size=True ***')
integrator.setValue('stiff', False)
integrator.setValue('variable_step_size', True)
print(integrator)
r.reset(SelectionRecord.ALL)
time_it(r.simulate, start=0, end=tend);

```

**Comment by 0u812** [comment]
It's just a case of the solver using a very fine timestep due to the extremely tight absolute tolerances you're setting. I could add a config setting to make it bail when memory usage gets beyond a certain threshold.

```
...

# set integrator settings
rel_tol = 1E-6
abs_tol = 1E-6 # Note the "* min(r.model.getCompartmentVolumes())" was removed
integrator.setValue('absolute_tolerance', abs_tol)
integrator.setValue('relative_tolerance', rel_tol)
tend = 1000

...

*** stiff=False, variable_step_size=True ***
< roadrunner.Integrator() >
  settings:
      relative_tolerance: 0.000001
      absolute_tolerance: 0.000001
                   stiff: false
       maximum_bdf_order: 5
     maximum_adams_order: 12
       maximum_num_steps: 20000
       maximum_time_step: 0
       minimum_time_step: 0
       initial_time_step: 0
          multiple_steps: false
      variable_step_size: true

Time: 9.15483999252
```

**Comment by matthiaskoenig** [comment]
The maximum step should handle this. After 20000 steps it should abort with
max steps reached.
The memory should than be 20000 × number of r.selections which is around
20-100mb. I think the num step bounds upper limited is not tested.

It's just a case of the solver using a very fine timestep due to the
extremely tight absolute tolerances you're setting. I could add a config
setting to make it bail when memory usage gets beyond a certain threshold.

...

# set integrator settings
rel_tol = 1E-6
abs_tol = 1E-6 # Note the "* min(r.model.getCompartmentVolumes())" was removed
integrator.setValue('absolute_tolerance', abs_tol)
integrator.setValue('relative_tolerance', rel_tol)
tend = 1000

...

*** stiff=False, variable_step_size=True ***
< roadrunner.Integrator() >
  settings:
      relative_tolerance: 0.000001
      absolute_tolerance: 0.000001
                   stiff: false
       maximum_bdf_order: 5
     maximum_adams_order: 12
       maximum_num_steps: 20000
       maximum_time_step: 0
       minimum_time_step: 0
       initial_time_step: 0
          multiple_steps: false
      variable_step_size: true

Time: 9.15483999252

—
Reply to this email directly or view it on GitHub
<https://github.com/sys-bio/roadrunner/issues/269#issuecomment-177029840>.

**Comment by 0u812** [comment]
The `maximum_num_steps` setting is actually used to limit the maximum internal number of steps that the CVODE solver can take to reach `tout`, as opposed to the maximum total rows in roadrunner's output matrix. However, I do agree that something needs to be added to protect against this situation. It seems like a global setting (as opposed to a solver-specific setting) would be appropriate, since the limit would apply to the number of rows in the output matrix, so the best location for the setting would probably be the [configuration system](http://sys-bio.github.io/roadrunner/python_docs/api_reference.html#configuration) (the docs talk about using a config file, but we also support setting config values within the script itself for better reproducibility).

**Comment by matthiaskoenig** [comment]
Yes there should be a maximum total internal steps setting. Is probably what COPASI is testing with `Max Internal Steps`. If these steps are reached an error/exception should be thrown with the exact time when the maximum number was reached. 
This will allow to set the maximum number of total steps according to selection/model size and available ram. If the error occurs I can catch it and rerun the simulation in parts, i.e. integrate up to the point where the ram is not sufficient, store the results and continue from there.

**Comment by 0u812** [comment]
I added a config key MAX_OUTPUT_ROWS with a default value of 20000 to prevent this from happening. If you ever want to disable it, you can set MAX_OUTPUT_ROWS=0 which will give you unlimited rows.
