### ISSUE TITLE
Setting r.simulateOptions analogue to r.integrator

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#275]
The mechanism to set and retrieve simulateOptions from a roadrunner object should be analogue to setting/getting integrator options, i.e.
```
r.simulateOptions.setValue('steps', 500)
r.simulateOptions.getValue('steps')
```
This should check against the allowed keys analog to integrator and raise exceptions if one tries to set simulateOptions which are not there

The following 
```
r.simulateOptions.keys()
```
should give the allowed keys.

This will simplify setting the simulationOptions and avoid problems with typos like
```
r.simulateOptions.stesp = 100
```
Currently this will just not do anything, but is very hard to find the problem. With the setValue mechanism this immidiatly shows the problem.

**Comment by 0u812** [comment]
`r.simulateOptions` no longer exists and has been renamed to `r.__simulateOptions` to signify that it is internal. Please do not use it.
