### ISSUE TITLE
Regressions: no simulation to end point & time points in events

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#276]
Some regression issues (and new issues) in the latest development version

## [1] not simulating to end point
RoadRunner is not simulating to end point in variable step simulation with event. Please add tests so that does not happen. (see also #240)

## [2] absolute tolerance not set in integrator
Handling of simulationOptions has problems. Some of the options are written in simulateOptions, but not set in the integrator (you see different values in `r.integrator.absolute_tolerance != r.simulateOptions.absolute`). Other arguments are not in simulateOptions, but in integrator (why `stiff` in both, but `variable_step_size` only in integrator)

=> arguments to roadrunner which are integrator settings should **ONLY** be set in the integrator, but not in simulateOptions, i.e. stiff, variableStep, ...
simulateOptions are only: steps, start & duration

The named arguments to `simulate` have to be **IDENTICAL** to the keys in simulateOptions and integrator!
At this point I do not trust the `r.simulate()` arguments at all. There are so many issues with it (see also #275, #264, #242). Please simplify this and make it right once. Half of the issues and discussion here is about simulate options and its problems.

## [3] event points identical
When running with `variable_step_size=False` the event time points are identical (see below). There should be one time point exactly before the event (event_time-eps) and one timepoint at the event (event_time) with all the triggered changes applied (see also #126)
Please write tests for solved issues! This should never come up again, but already did 3 times.
```
  [           2,    0, 0.5,  1,  0],
  [           2,    0,   5, 10,  0],
```

```
from __future__ import print_function, division

import roadrunner
from roadrunner import SelectionRecord
print(roadrunner.__version__)

# Model definition via antimony.
# The model contains an Event triggered at t=2 [s].
r = te.loada("""
    model event_time()
    // Reactions
    J0: $PP_S -> 2 S3; K1 * PP_S;

    // Species initializations:
    var species S3;
    var species S4;
    S3 = 0.5;
    PP_S = 0.0;
    S4 := 2*S3;

    // Rule for S1
    K1 = 0.5;    
    
    // Additional events for triggering re-integration
    E1: at(time>=2):  S3=5;  
    end
""")

r.selections = ['time'] + r.model.getBoundarySpeciesIds() + r.model.getFloatingSpeciesIds() + r.model.getReactionIds()
print(r.selections)

absTol = 1E-6 * min(r.model.getCompartmentVolumes())
relTol = 1E-6

s = r.simulate(0, 7, absolute=absTol, relative=relTol, variableStep=False, stiff=False, plot=True)
print(r)
print(s)
s = r.simulate(0, 7, absolute=absTol, relative=relTol, variableStep=True, stiff=False, plot=True)
print(s)
```

```
1.4.2; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler: LLVM-3.4; Date: Feb  1 2016, 15:48:52; LibSBML Version: 5.12.0
['time', 'PP_S', 'S3', 'S4', 'J0']

<roadrunner.RoadRunner() { 
'this' : 0x3bbcc50
'modelLoaded' : true
'modelName' : event_time
'libSBMLVersion' : LibSBML Version: 5.12.0
'jacobianStepSize' : 1e-05
'conservedMoietyAnalysis' : false
'simulateOptions' : 
< roadrunner.SimulateOptions() 
{ 
'this' : 0x3945750, 
'reset' : 0,
'structuredResult' : 0,
'copyResult' : 1,
'steps' : 50,
'start' : 0,
'duration' : 7,
'stiff' : false, 
'absolute' : 0.000001, 
'relative' : 0.000001
}>, 
'integrator' : 
< roadrunner.Integrator() >
  settings:
      relative_tolerance: 0.00001
      absolute_tolerance: 0.0000000001
                   stiff: false
       maximum_bdf_order: 5
     maximum_adams_order: 12
       maximum_num_steps: 20000
       maximum_time_step: 0
       minimum_time_step: 0
       initial_time_step: 0
          multiple_steps: false
      variable_step_size: false

}>
    time, PP_S,  S3, S4, J0
 [[    0,    0, 0.5,  1,  0]]

           time, PP_S,  S3, S4, J0
 [[           0,    0, 0.5,  1,  0],
  [ 0.000240258,    0, 0.5,  1,  0],
  [           2,    0, 0.5,  1,  0],
  [           2,    0,   5, 10,  0],
  [     2.00026,    0,   5, 10,  0],
  [     4.55863,    0,   5, 10,  0],
  [           7,    0,   5, 10,  0]]


```

**Comment by hsauro** [comment]
How on earth do these errors keep coming back?

**Comment by 0u812** [comment]
[1] This is not broken and Kiri has already implemented a regression test for it. If you're referring to your model above not simulating when variableStep=False is true is passed to simulate, that has been filed under #277. We are not going to support overloading of simulate in the future (which is one of the points you raised in your post so it sounds like you agree). The variable step feature can be enabled via the solver API, which is the only way we will support in the future. We will update the documentation on the usage of simulate.
[2] SimulateOptions is deprecated and only for internal use, please do not use it. We have already removed the majority of references to it in the documentation, but I see a few still remain. I will remove those.
[3] This does not appear to be broken. The output values you posted are rounded. The actual floating point values are not the same. We cannot guarantee that one value will be (event_time-eps) and one will be (event_time) as we discussed in #126, but we can guarantee monotonicity. This satisfies your requirements from #126:

1) no duplicate timepoints 2) at least: a) one time point exactly when the event is triggered: the numerical values of the model for this timepoint are the values after evaluating the event, i.e. all the event assignments. b) one time point as short as possible before the event is triggered with the numerical values corresponding to before the event was evaluated.

I have added regression tests for the event timepoints.
