### ISSUE TITLE
Discourage use of simulateOptions

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#278]
simulateOptions has been deprecated in favor of the solver API for a long time. We need to have more documentation and warning messages to prevent people from using it.

We cannot remove it completely because it is used pervasively throughout the codebase.

**Comment by matthiaskoenig** [comment]
Yes, please provide deprecated warnings, with a clear message what to use instead and when this will be no longer supported.

Than everybody has one version time to update the code base based on the deprecated warnings. 
If the python swig interface you should do this via the following snippet.
```
def sedml_to_python(inputstring):
    import warnings
    warnings.warn('Use sedmlToPython instead, will be removed in v1.4',
                  DeprecationWarning, stacklevel=2)
    return sedmlToPython(inputstring)
```
i.e. use `warnings.warn` with `DeprecationWarning`. Than the IDEs provide support via strikethrough of the methods and simplify the update.

What do you mean with **pervasively throughout the codebase**? The c++ codebase? In tellurium I only saw a handful of occurences which can be easily fixed. 
If it is mainly the c++ codebase you could just not export the simulateOptions via the python swig (and the methods manipulating it). Than there is no option to set simulateOptions through python.

**Comment by 0u812** [comment]
The comment about it being used pervasively throughout the codebase refers to the fact that it is used internally within the Python bindings and also in the C++ source to pass around non solver-specific simulation options like start/duration. We want to keep it around for that reason but it shouldn't be used to pass solver-specific settings. I thought we had removed all of those but apparently not.
