### ISSUE TITLE
Test 4-arg simulate

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#279]
Simulate should only support four arguments: 
* start
* stop
* number of points
* selections
Check that these four work via positional and keyword arguments.

**Comment by matthiaskoenig** [comment]
Yes. Everything else should be forbidden (generate deprecated warnings or in my opinion even Exceptions to get rid of the other arguments as soon as possible in the code base) 

The only way to set `variable_step_size`, `stiff`, `relative_tolerance`, `absolute_tolerance` is via
```
r.integrator.setSetting(key, value)
```
The only way to reset things is via
```
r.reset(roadrunner.SelectionRecord.*)
```
The only way to set the seed is 
```
r.setSeed(seed)
```
What is unclear is:
* How to set `steps` and `start`, `end`, `number_of_points` if not provided to simulate? I.e. what is currently done via `r.simulateOptions.* =`
* How to set `integrator`, i.e. cvode / gillespi?

**Comment by luciansmith** [comment]
http://sys-bio.github.io/roadrunner/python_docs/using_roadrunner.html#solvers lists other ways to do this--are they also being deprecated?  For example, another way to set the seed would be with:

r.getIntegrator().setValue('seed', 1001)

The way to set the integrator, according to the documentation there, is:

r.setIntegrator('integrator_name')
i.e.
r.setIntegrator('rk4')
r.setIntegrator('gillespie')

**Comment by matthiaskoenig** [comment]
Updated comment above with @luciansmith info

**Comment by 0u812** [comment]
No the solver API is the one we want to keep. We're trying to do away 
with all other methods of specifying solver parameters.

**Comment by matthiaskoenig** [comment]
@0u812 
So what is the correct way to set `steps`, `start`, `end`, `number_of_points` if NOT provided as argument to simulate?

**Comment by 0u812** [comment]
The arguments for start, end, and number of points should be passed to the call to simulate. There should be no other way to set them.

On February 2, 2016 2:58:26 PM PST, "Matthias König" <notifications@github.com> wrote:
>@0u812 
>So what is the correct way to set `steps`, `start`, `end`,
>`number_of_points` if NOT provided as argument to simulate? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/279#issuecomment-178874499

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
The C API provides specific methods to set them so one can either call
simulate (start, end, points) or simulate() which picks up the values from
a set of methods that set the values, eg setStartTime (0)

What is the reason for not allowing users in Python to independently set
the start, end and points?

h

**Comment by 0u812** [comment]
It was my understanding that you wanted to do away with multiple ways to specify the same thing.

On February 2, 2016 3:34:37 PM PST, Herbert Sauro <notifications@github.com> wrote:
>The C API provides specific methods to set them so one can either call
>simulate (start, end, points) or simulate() which picks up the values
>from
>a set of methods that set the values, eg setStartTime (0)
>
>What is the reason for not allowing users in Python to independently
>set
>the start, end and points?
>
>h
>
>On Tue, Feb 2, 2016 at 3:28 PM, Kyle Medley <notifications@github.com>
>wrote:
>
>> The arguments for start, end, and number of points should be passed
>to the
>> call to simulate. There should be no other way to set them.
>>
>> On February 2, 2016 2:58:26 PM PST, "Matthias König" <
>> notifications@github.com> wrote:
>> >@0u812
>> >So what is the correct way to set `steps`, `start`, `end`,
>> >`number_of_points` if NOT provided as argument to simulate?
>> >
>> >---
>> >Reply to this email directly or view it on GitHub:
>>
>>https://github.com/sys-bio/roadrunner/issues/279#issuecomment-178874499
>>
>> --
>> Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/sys-bio/roadrunner/issues/279#issuecomment-178884412>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/279#issuecomment-178885904

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by matthiaskoenig** [comment]
> The arguments for start, end, and number of points should be passed to the call to simulate.

This works for me. No need to have the setStartTime and set ... methods.

Two things are important in addition
* I need to set `steps` somehow, and don't want to go via `r.simulate(0,0,steps+1)`, so add `steps` to the list of 4 arguments (makes it 5).
* all arguments to simulate must be available as keyword version, i.e.

Below the list of things I would expect to work and give the identical results
```
# sim 0-100, points=51
r.simulate(0, 100, 51)
r.simulate(0, 100, points=51)
r.simulate(start=0, end=100, points=51)
r.simulate(0, 100, steps=50)
r.simulate(start=0, end=100, steps=50)
```
And the variants with selections, also all same results
```
# sim 0-100, points=51, selections=['time', 'S1']
r.simulate(0, 100, 51, ['time', 'S1'])
r.simulate(0, 100, points=51, selections=['time', 'S1'])
r.simulate(start=0, end=100, points=51, selections=['time', 'S1'])
r.simulate(0, 100, steps=50, selections=['time', 'S1'])
r.simulate(start=0, end=100, steps=50, selections=['time', 'S1'])
```

**Comment by hsauro** [comment]
That's true unless there is a specific use case that could benefit from it.
The one case I have used the ability to specify start, end and points in
separate methods is in a long loop that calls simulate many many times.

set start, end, points
start loop
   simulate()
   process data
end loop

I wanted to reduce the overhead in repeatedly supplying arguments to
simulate. At the end of the day I am not sure how much time it really saved
in cpu cycles. This might not be a compelling case but if Matthias doesn't
come up with something or you don't have a specific use case that could
benefit then don't have separate methods to set start, end and points (at
least in python). Using python to run a complex script may not get you the
best performance any way, hence to maximize performance use the C or C++
APIs or something like Julia with bindings to libRoadRunner (which I have
somewhere).

One thing that should be allowed and is something I do sometimes is allow
people to specify only the start and end time (no points) or just the end
time.

simulate () <- use default values for all potential arguments
simulate (50)  <- just time end, assumes time start and points have their
default values
simulate (0, 50) <- just time start and end, points has default value

Comments?

Herbert

**Comment by hsauro** [comment]
*I think Matthias's examples should be good enough:*

Below the list of things I would expect to work and give the identical
results

# sim 0-100, points=51
r.simulate(0, 100, 51)
r.simulate(0, 100, points=51)
r.simulate(start=0, end=100, points=51)
r.simulate(0, 100, steps=50)
r.simulate(start=0, end=100, steps=50)

And the variants with selections, also all same results

# sim 0-100, points=51, selections=['time', 'S1']
r.simulate(0, 100, 51, ['time', 'S1'])
r.simulate(0, 100, points=51, selections=['time', 'S1'])
r.simulate(start=0, end=100, points=51, selections=['time', 'S1'])
r.simulate(0, 100, steps=50, selections=['time', 'S1'])
r.simulate(start=0, end=100, steps=50, selections=['time', 'S1'])
