### ISSUE TITLE
Event handling/triggering at exact time points undefined

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#281]
Triggering events on exact time points results in inconsistent/undefined behavior of roadrunner (see example below). The events

```
    at time==10: p1=10;
    at time==20: p1=0;
```

should create a peak from 10-20. The results of roadrunner depend actually on the selected number of points (?), i.e. if the trigger is hit or not by a time step.
COPASI handles this correctly and is robust no matter what steps are selected (creates peak as long as at least one time point in peak).

The correct way to encode this in a model is via inequalities (so that the triggers are working)

```
    at time>=10: p1=10;
    at time>=20: p1=0;
```

but most people will encode this via equalities and as a consequence will have undefined model behavior in roadrunner. Perhaps there should be a warning in the case of time==value triggeres in roadrunner, or it should be handeled in a more robust way.

```
from __future__ import print_function
import tellurium as te

print('-' * 80)
te.printVersionInfo()
print('-' * 80)

r = te.loada('''
model example
    p1 = 0;
    at time==10: p1=10;
    at time==20: p1=0;
end
''')

# look at model
ant_str = r.getCurrentAntimony()
sbml_str = r.getCurrentSBML()
print(ant_str)
print(sbml_str)
# r.exportToSBML('/home/mkoenig/Desktop/test.xml')

# set selections
r.selections=['time', 'p1']
r.integrator.setValue("variable_step_size", False)
s1 = r.simulate(0, 40, 40)
r.plot()
print(s1)
# hitting the trigger point directly works
s2 = r.simulate(0, 40, 21)
r.plot()
print(s2)

# variable step size also does not work
r.integrator.setValue("variable_step_size", True)
s3 = r.simulate(0, 40)
r.plot()
print(s3)
```

```
--------------------------------------------------------------------------------
tellurium : 1.3.0
roadrunner : 1.4.2; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler: LLVM-3.4; Date: Feb  3 2016, 08:19:01; LibSBML Version: 5.12.0
antimony : v2.8.0
snbw_viewer : No information for sbnw viewer
libsbml : 5.12.1
libsedml : 401
phrasedml : v0.5 beta
--------------------------------------------------------------------------------
// Created by libAntimony v2.8.1
model *example()

  // Events:
  _E0: at time == 10: p1 = 10;
  _E1: at time == 20: p1 = 0;

  // Variable initializations:
  p1 = 0;

  // Other declarations:
  var p1;
end

       time, p1
 [[       0,  0],
  [ 1.02564,  0],
  [ 2.05128,  0],
  [ 3.07692,  0],
  [ 4.10256,  0],
  [ 5.12821,  0],
  [ 6.15385,  0],
  [ 7.17949,  0],
  [ 8.20513,  0],
  [ 9.23077,  0],
  [ 10.2564,  0],
  [ 11.2821,  0],
  [ 12.3077,  0],
  [ 13.3333,  0],
  [  14.359,  0],
  [ 15.3846,  0],
  [ 16.4103,  0],
  [ 17.4359,  0],
  [ 18.4615,  0],
  [ 19.4872,  0],
  [ 20.5128,  0],
  [ 21.5385,  0],
  [ 22.5641,  0],
  [ 23.5897,  0],
  [ 24.6154,  0],
  [  25.641,  0],
  [ 26.6667,  0],
  [ 27.6923,  0],
  [ 28.7179,  0],
  [ 29.7436,  0],
  [ 30.7692,  0],
  [ 31.7949,  0],
  [ 32.8205,  0],
  [ 33.8462,  0],
  [ 34.8718,  0],
  [ 35.8974,  0],
  [ 36.9231,  0],
  [ 37.9487,  0],
  [ 38.9744,  0],
  [      40,  0]]

    time, p1
 [[    0,  0],
  [    2,  0],
  [    4,  0],
  [    6,  0],
  [    8,  0],
  [   10, 10],
  [   12, 10],
  [   14, 10],
  [   16, 10],
  [   18, 10],
  [   20,  0],
  [   22,  0],
  [   24,  0],
  [   26,  0],
  [   28,  0],
  [   30,  0],
  [   32,  0],
  [   34,  0],
  [   36,  0],
  [   38,  0],
  [   40,  0]]

         time, p1
 [[         0,  0],
  [ 0.0013729,  0],
  [   13.7304,  0],
  [        40,  0]]
```

![roadrunner_output](https://cloud.githubusercontent.com/assets/900538/12775774/e8d8baa4-ca50-11e5-8250-0a6387f9043d.png)
![copasi_output](https://cloud.githubusercontent.com/assets/900538/12775776/edf595a2-ca50-11e5-94a1-ba90119cd269.png)

**Comment by 0u812** [comment]
Gated on #284.

**Comment by hsauro** [comment]
I also forward it to Lucian.

H

**Comment by luciansmith** [comment]
Exact-value triggers for continually-changing values can indeed be problematic, but I'm not sure I see a good way to respond to it in the simulator.  We don't have any such problematic triggers in the SBML test suite for the simple reason that they're bad models in the first place.  And exact-value triggers for step-changing values are fine:  you see this all the time when you want one event to trigger another (when x>y, z=1; when z==1, do something else).

The only way to properly warn users that their models are bad would be to be able to categorize all values as varying smoothly or stepwise, and then to analyze the boolean functions in the triggers to see if you had an exact-value/continuous-change combination that was problematic.  Maybe there's a simpler thing that could be done to catch the most obvious cases?  I'm not sure.  I guess it would be relatively straightforward to catch the exact case where a trigger was "[id] == [number]", and [id] was a non-boundary species that appeared in a reaction, or any ID that appeared as the target of a rate rule?

**Comment by luciansmith** [comment]
Another option to solve this entirely internally:  for any Trigger whose mathematical root was '==', create two dummy Triggers with the same math, but one whose root is ">=" and another whose root is "<=".  Whenever either of those fire, check to see if the reason they fired was because '==' was also achieved, and, if so, fire the original event.

**Comment by luciansmith** [comment]
I think this is probably best handled as a model checking step, which is not really roadrunner's purview, but instead belongs to something like km_test.  I've filed an issue over there (https://github.com/sys-bio/km_test/issues/9) and am closing this for now, but do re-open if you disagree.
