### ISSUE TITLE
Document new simulate function

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#283]
The signature for the new simulate function is:

```
def simulate(self, start=None, end=None, points=None, selections=None, steps=None):
```

Notice that all of the arguments are optional. Users can use a combination of keyword and positional arguments as with all Python functions, but cannot use any keywords other than what is listed above. Also, it is an error to specify both points and steps.

The old simulate function was renamed to simulateOld. It is deprecated and will be removed in a future release.

Kiri, please update the documentation to reflect the new signature and go through all the .rst files in wrappers/Python/docs and make sure all references to simulate are compatible with the new signature. This doesn't need to be done immediately - it can wait until after the paper is submitted. (Fyi I already added the tests from #279 so all you need to do is update the docs).

**Comment by hsauro** [comment]
You should probably let the ComputeCell3d (Maciej) know, they might use the
plot=true option.

H

**Comment by 0u812** [comment]
It occurred to me that we should give people one release to update their code. I could code up a proxy simulate which first tries to call the new simulate and then falls back to the old one if there's an unrecognized keyword, issuing a warning. What do you think?

**Comment by hsauro** [comment]
I would find out what Maceij and co do with simulate.

H

**Comment by matthiaskoenig** [comment]
I prefer the hard switch. Remove as much code balast as possible. Is not so
much to update.

One small improvement: Could you provide defaults for points (or steps),
i.e.

```
def simulate(self, start=None, end=None, points=51, selections=None,
steps=None):
```

There are many calls without points in the examples.
```

r.simulate(0, 40)

```

If selections==None, it should default to self.selections, i.e. the
selections of the roadrunner object.





On Wed, Feb 3, 2016 at 10:32 PM, Herbert Sauro <notifications@github.com>
wrote:

> I would find out what Maceij and co do with simulate.
>
> H
>
> On Wed, Feb 3, 2016 at 1:26 PM, Kyle Medley <notifications@github.com>
> wrote:
>
> > It occurred to me that we should give people one release to update their
> > code. I could code up a proxy simulate which first tries to call the new
> > simulate and then falls back to the old one if there's an unrecognized
> > keyword, issuing a warning. What do you think?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sys-bio/roadrunner/issues/283#issuecomment-179478219
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/roadrunner/issues/283#issuecomment-179481408>.
>



-- 
Matthias König
Email: konigmatt@googlemail.com
Tel: + 49 30 20938450
Tel: + 49 176 81168480
  https://www.livermetabolism.com/contact.html
Humboldt-University Berlin, Institute for Theoretical Biology, Junior Group
König
Charité Berlin, Institute of Biochemistry, Computational Systems
Biochemistry <http://www.charite.de/sysbio/people/koenig/>

**Comment by matthiaskoenig** [comment]
And please raise an exception !

I get a message on stdout:
'error: simulate() got an unexpected keyword argument 'integrator''
with  Process finished with exit code 0

Without the stacktrace it is very cumbersome to find the code lines were
simulate was called wrong.


On Wed, Feb 3, 2016 at 10:51 PM, Matthias König <konigmatt@googlemail.com>
wrote:

> I prefer the hard switch. Remove as much code balast as possible. Is not
> so much to update.
>
> One small improvement: Could you provide defaults for points (or steps),
> i.e.
>
> ```
> def simulate(self, start=None, end=None, points=51, selections=None, steps=None):
> ```
>
> There are many calls without points in the examples.
> ```
>
> r.simulate(0, 40)
>
> ```
>
> If selections==None, it should default to self.selections, i.e. the selections of the roadrunner object.
>
>
>
>
>
> On Wed, Feb 3, 2016 at 10:32 PM, Herbert Sauro <notifications@github.com>
> wrote:
>
>> I would find out what Maceij and co do with simulate.
>>
>> H
>>
>> On Wed, Feb 3, 2016 at 1:26 PM, Kyle Medley <notifications@github.com>
>> wrote:
>>
>> > It occurred to me that we should give people one release to update their
>> > code. I could code up a proxy simulate which first tries to call the new
>> > simulate and then falls back to the old one if there's an unrecognized
>> > keyword, issuing a warning. What do you think?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/sys-bio/roadrunner/issues/283#issuecomment-179478219>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sys-bio/roadrunner/issues/283#issuecomment-179481408>
>> .
>>
>
>
>
> --
> Matthias König
> Email: konigmatt@googlemail.com
> Tel: + 49 30 20938450
> Tel: + 49 176 81168480
>   https://www.livermetabolism.com/contact.html
> Humboldt-University Berlin, Institute for Theoretical Biology, Junior
> Group König
> Charité Berlin, Institute of Biochemistry, Computational Systems
> Biochemistry <http://www.charite.de/sysbio/people/koenig/>
>



-- 
Matthias König
Email: konigmatt@googlemail.com
Tel: + 49 30 20938450
Tel: + 49 176 81168480
  https://www.livermetabolism.com/contact.html
Humboldt-University Berlin, Institute for Theoretical Biology, Junior Group
König
Charité Berlin, Institute of Biochemistry, Computational Systems
Biochemistry <http://www.charite.de/sysbio/people/koenig/>

**Comment by 0u812** [comment]
In regards to the default arguments, in making the switch to the new simulate function I tried to keep the old way of initializing the number of steps. It comes from the config value for SIMULATEOPTIONS_STEPS, but I don't know if anyone other than Andy who actually used that value so if Herbert wants we could remove it and specify the default right in the function signature, for example:
```
def simulate(self, start=0., end=10., points=51., selections=None, steps=None):
```
as opposed to the current signature:
```
def simulate(self, start=None, end=None, points=None, selections=None, steps=None):
```
(steps will be set before the actual simulation is run but it will be set from the config value).

**Comment by 0u812** [comment]
Calling the simulate function with the wrong arguments should raise a TypeError. When I call with the wrong arguments I get:
```
Traceback (most recent call last):
  File "run.py", line 40, in <module>
    s = r.simulate(0, 7, 50, variableStep=True)
TypeError: simulate() got an unexpected keyword argument 'variableStep'
```

**Comment by luciansmith** [comment]
I don't think you can set the default steps/points in the function signature.  If you do as above and set the points, if the user sets the steps, both points and steps will then be set, which is incorrect (and the reverse will be true if you have default points in the signature).

This is probably why SIMULATEOPTIONS_STEPS was used in the first place:  it would check if both points and steps were None, and, if so, set steps to 50.
