### ISSUE TITLE
Need more test models with events

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#284]
I looked through the .rrtest files and we only have one model with events: the model from #276. We need more models with events so that I can fix #281 without breaking existing models. (We also have the SBML test suite and any event tests it contains, but I think we need more.)

**Comment by kirichoi** [comment]
Add model from https://github.com/sys-bio/roadrunner/issues/439.

**Comment by luciansmith** [comment]
I am going to claim that the event tests in the SBML test suite itself are sufficient.
