### ISSUE TITLE
Runtime Error at certain number of time points

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#286]
Following script causes runtime error at certain number of steps:
`RuntimeError: CVODE Error: CV_ERR_FAILURE: Error test failures occurred too many times (= MXNEF = 7) during one internal time step oroccurred with |h| = hmin.; In ?integrate@CVODEIntegrator@rr@@UAENNN@Z`

The same set of parameters works perfectly fine IF the simulation is run with different number of time points.

```
import roadrunner as rr
import tellurium as te
import numpy as np

r = te.loada("""
M + M -> E; k_a*M*M - k_d*E;
E + S -> ES; k_on*E*S - k_s*ES;
ES -> E + P; k_r*ES;
P + E -> EP; k_on*P*E - k_p*EP;
I + E -> EI; k_on*I*E - k_i*EI;
EI -> EJ; k_de*EI;

I = 0.004; E = 0.004; S = 25;
M = 0; ES = 0; P = 0; EP = 0; EI = 0; EJ = 0;
k_on = 100; k_d = 0.001; k_a = 0.1; 
k_s = 300; k_r = 10; k_p = 500; k_i = 0.1; k_de = 0.1;
""")

r.k_s = 0.23787277793746453
r.k_r = 5.238898986966928
r.k_p = 1202.350122502493
r.k_i = 0.06944082157369025
r.k_de = 6.613947445014566

r.timeCourseSelections = ["time","P"]

s1 = r.simulate(0, 3600, 300)
r.plot(s1)
r.reset()

# This does not work for some reason
s2 = r.simulate(0, 3600, 301)
```

**Comment by matthiaskoenig** [comment]
all your dots are missing in the example, could you paste code with dots

On Fri, Feb 5, 2016 at 3:09 AM, Kiri Choi <notifications@github.com> wrote:

> Following script causes runtime error at certain number of steps:
> RuntimeError: CVODE Error: CV_ERR_FAILURE: Error test failures occurred
> too many times (= MXNEF = 7) during one internal time step oroccurred with
> |h| = hmin; In ?integrate@CVODEIntegrator@rr@@UAENNN@Z
>
> The same set of parameters works perfectly fine IF the simulation is run
> with different number of time points
>
> import roadrunner as rr
> import tellurium as te
> import numpy as np
>
> r = teloada("""
> M + M -> E; k_a*M*M - k_d*E;
> E + S -> ES; k_on*E*S - k_s*ES;
> ES -> E + P; k_r*ES;
> P + E -> EP; k_on*P*E - k_p*EP;
> I + E -> EI; k_on*I*E - k_i*EI;
> EI -> EJ; k_de*EI;
>
> I = 0004; E = 0004; S = 25;
> M = 0; ES = 0; P = 0; EP = 0; EI = 0; EJ = 0;
> k_on = 100; k_d = 0001; k_a = 01;
> k_s = 300; k_r = 10; k_p = 500; k_i = 01; k_de = 01;
> """)
>
> rk_s = 023787277793746453
> rk_r = 5238898986966928
> rk_p = 1202350122502493
> rk_i = 006944082157369025
> rk_de = 6613947445014566
>
> rtimeCourseSelections = ["time","P"]
>
> s1 = rsimulate(0, 3600, 300)
> rplot(s1)
> rreset()
>
> # This does not work for some reason
> s2 = rsimulate(0, 3600, 301)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/roadrunner/issues/286>.
>



-- 
Matthias König
Email: konigmatt@googlemail.com
Tel: + 49 30 20938450
Tel: + 49 176 81168480
  https://www.livermetabolism.com/contact.html
Humboldt-University Berlin, Institute for Theoretical Biology, Junior Group
König
Charité Berlin, Institute of Biochemistry, Computational Systems
Biochemistry <http://www.charite.de/sysbio/people/koenig/>

**Comment by kirichoi** [comment]
Hmm that is weird, it looks fine on my screen. I will put it up as a  text file. How does it look like now?

[HIVproteinease.txt](https://github.com/sys-bio/roadrunner/files/118777/HIVproteinease.txt)

**Comment by matthiaskoenig** [comment]
Thanks. Yes looks good here on github. 
So probably a bug in github when creating the mail for the issue. Are you sure your dots are really dots and not some ASCII character which only look like?

See below what I got in my in email
![screenshot from 2016-02-05 13 34 31](https://cloud.githubusercontent.com/assets/900538/12846519/59681db0-cc0d-11e5-9c0d-21b769fa4a49.png)

**Comment by hsauro** [comment]
I presume the more points you ask for the more likely the simulation
succeeds? Is there a pattern?

Herbert

**Comment by kirichoi** [comment]
@matthiaskoenig: That's interesting. I think it's more likely to be a bug.

@hsauro: One thing I noticed is that this seems to happen when you are trying to simulate at the exact time step. For example, simulate(0, 3600, 302), with time step slightly smaller than 12, works, but if you try simulate(0, 3612, 302), with time step of 12, fails. In this particular example, the simulation seems to fail at the time point between t = 2248 and t = 2460.

**Comment by kirichoi** [comment]
Cannot reproduce anymore - closing the issue.
