### ISSUE TITLE
SBML Test Suite: update results in database on sbml.org

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#288]
The roadrunner entries in the SBML database are outdated for roadrunner
see
http://sbml.org/Facilities/Database/
http://sbml.org/Facilities/Database/Submission/Details/91

```
Results were submitted by lpsmith on Monday, December 29, 2014.
Results were generated for the following SBML Level+Version: Highest.
libRoadRunner 1.3 supports the following package(s): comp. 
```

These results should be updated to latest version. 

All SBML Test suite tests should be individual tests included in the roadrunner test suite. Only by this it can be guaranteed that every commit still supports the full test suite.
There are around 1200 test cases in the suite, currently there are only ~ 400 tests in the roadrunner test suite.

**Comment by luciansmith** [comment]
All the SBML test suite models are indeed run by roadrunner, but they're only run by the C test suite, not the Python test suite.

**Comment by matthiaskoenig** [comment]
Perfect. That is the important part.

How can I run the C test suite?

**Comment by 0u812** [comment]
Provided that you have `-DBUILD_TEST_TOOLS=ON -DBUILD_TESTS=ON` in your CMake cache, the C tests run automatically (along with the Python tests) when you run `ctest -VV` from the CMake build directory (there should be 3 total tests in your CTest output). CTest is run automatically by Travis so if the build is passing then the SBML test suite is also passing.

**Comment by matthiaskoenig** [comment]
Works. The testing issue is solved for me. 
Only the results on sbml.org should be updated with the next release version.

**Comment by matthiaskoenig** [comment]
It would be great to upload the latest results of libroadrunner to the SBML Test database
http://sbml.org/Facilities/Database/Submission/Details/91
The last results of libroadrunner are from 2014 of version 1.3 !?

**Comment by luciansmith** [comment]
I agree!  I finally tracked down a bunch of small errors here and there that prevented roadrunner from passing the latest tests, so we have results we could upload.  The only issue is that the web site itself doesn't have the latest tests, either.  I'll ping the SBML team to see what can be done on that front.

**Comment by luciansmith** [comment]
This is now (finally) done!  With the new tests and everything!

http://raterule.caltech.edu/Facilities/Database/Submission/Details/281

**Comment by matthiaskoenig** [comment]
Congrats. This is great news.
