### ISSUE TITLE
Bad error message and incorrect output when calling getFullJaobian

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#292]
The following model reports an incorrect error:

"RuntimeError: Metabolic control analysis only valid for primitive reaction kinetics models. This model has events"

These are the issues:
1. Computing the Jacobian is not just confined to metabolic control analysis but can be computed independently of MCA and often is. Remove the phrase Metabolic Control Analysis
2. Although the model has events, befoire and after the even the does exist. For example at t = 15 its value is:

[-0.8, 0; 0.8 0]

There is no issue in computing the Jacobian if there are events, the user simply has to be aware of when the Jacobian was computed and this should be apparent based on the context. Before and after an eventsthe Jacobian is defined. In any case getReducedJacobian returns the correct Jacobian so there is an issue with getFullJacobian.

import tellurium as te
import roadrunner

r = te.loada("""
   J1: A -> B; k1*A;

   at time > 4:  k1 = k1*8

   A = 10; B = 0;
   k1 = 0.1;
""")

m = r.simulate(0, 15, 100)
r.plot()
print r.getFullJacobian()

**Comment by hsauro** [comment]
Kyle will fix this 15 Feb 2017

**Comment by luciansmith** [comment]
Fixed with https://github.com/sys-bio/roadrunner/pull/668
