### ISSUE TITLE
r.getScaledElasticityMatrix() gives error if model has events

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#294]
Calling

r.getScaledElasticityMatrix()

gives the error message:

Metabolic control analysis only valid for primitive reaction kinetics models. This model has events

However at steady state or in fact any state of the pathway it should be possible to compute the matrix of elasticities. In fact getEE does allow the elasticities to be computed. 

r = te.loada("""
   J1: $A -> B; k1_A;
   J2: B -> $C; k2_B;

   at time > 4:  k1 = k1*8

   A = 10; B = 0; C = 0;
   k1 = 0.1; k2 = 0.14;
""")

m = r.simulate(0, 25, 100)
r.plot()

print "Closeness to steady state: ", r.steadyState()

print r.getFullStoichiometryMatrix()
print r.getConservationMatrix();
print r.getReducedJacobian()

print r.getEE ("J1", "A")

r.r.getScaledElasticityMatrix() # <-- Doesn't work

**Comment by hsauro** [comment]
Kyle will fix 15 Feb 2017

**Comment by luciansmith** [comment]
Fixed with https://github.com/sys-bio/roadrunner/pull/668
