### ISSUE TITLE
No doc string for getExistingIntegratorNames

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#295]
Tried to get help for r.getExistingIntegratorNames but it reported no doc string

Are there any other methods without a doc string?

What does r.getExistingIntegratorNames do? Its plural so it could return more than one name? What is an existing name?

**Comment by hsauro** [comment]
Kyle will add r.integrators to docs 15 Feb 2017

**Comment by 0u812** [comment]
Added
