### ISSUE TITLE
r.getAvailableIntegrators() returns one name, is that ok?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#296]
A call to r.getAvailableIntegrators() returns just one name, is that ok since the call implies it returns many names? What does it actually do?

Doc string is very terse and uninformative:

"get a list of available integrator names."

Also capitalize get to Get

**Comment by hsauro** [comment]
Kyle will fix 15 feb 2017

**Comment by 0u812** [comment]
I think what we want to use is `r.integrators`, which returns `['cvode', 'gillespie', 'rk4', 'rk45']`. Is it okay if I resolve this by removing the getAvailableIntegrators method?

**Comment by 0u812** [comment]
Add `r.integrators` to doc
