### ISSUE TITLE
One of Matthias's examples won't run, don't understand error, bug?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#300]
I tried running Matthias's stochastic model but I'm getting a Python error. I cut the model down to a minimum and it seems that the error occurs when the setSeed is called.

This is the script:

import tellurium as te
r = te.loada('''
    J1: S1 -> S2;  k1*S1;

    k1 = 0.1; 
    S1 = 100;
''')
r.setIntegrator('gillespie')
r.setSeed(1234)

telluirum Version:  1.3.0
RoadRunner version: 1.4.2; Compiler: Microsoft Visual Studio 2013, C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Jan 19 2016, 17:47:44
Antimony version: v2.8.0
No information on sbnw viewer

And error message:

  File "C:/Users/hsauro/Documents/Tellurium/stochastic1.py", line 13, in <module>
    r.setSeed(1234)

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\tellurium\tellurium.py", line 365, in setSeed
    intg = r.getIntegrator('gillespie')

TypeError: getIntegrator() takes exactly 1 argument (2 given)

**Comment by kirichoi** [comment]
This is a tellurium issue which should be fixed when the newest version of tellurium.py is used. However, the updated version also has a problem, since `getSeed` and `setSeed` use old roadrunner method `getIntegratorByName` and `setIntegratorSetting`.

**Comment by matthiaskoenig** [comment]
Update to latest Mac/Win version fixes this. see #300

**Comment by hsauro** [comment]
We need to have a regression test for setSeed and the new r.plot syntax.

Herbert

**Comment by 0u812** [comment]
Moved to tellurium
