### ISSUE TITLE
Error in docs getuEE and getuCC

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#304]
A student just spotted an error in getuEE in the docs which caused some problems. 

In the following docs copied from libroadrunner.org, the line:

RoadRunner.getEE(reactionId, parameterId, steadyState=True)
Retrieve a single elasticity coefficient with respect to a global parameter.

For example:

x = rr.getEE ('J1', 'Vmax')

Parameters: 
variable (str) – The dependent variable of the coefficient, for example a flux or species concentration.
parameter (str) – The independent parameter, for example a kinetic constant or boundary species
steadyState (Boolean) – should the steady state value be computed.

RoadRunner.getuEE(reactionId, parameterId)
Get unscaled elasticity coefficient with respect to a global parameter or species.

Fix the following:
1. variable (str) – The dependent variable of the coefficient, for example a flux or species concentration.

should read

variable (str) – A reaction Id
.
2, The line:

parameter (str) – The independent parameter, for example a kinetic constant or boundary species

should be:

parameter (str) – The independent parameter, for example a kinetic constant, floating or boundary species

The help on getuEE should be expanded, currently it is only:

Get unscaled elasticity coefficient with respect to a global parameter or species.

Likewise the docs on getuCC are also insufficient, currently it is only:

Get unscaled control coefficient with respect to a global parameter.

**Comment by matthiaskoenig** [comment]
I definitely want to update the python docstrings for roadrunner (see discussion in #290). I also have issues with many of the docstrings.

But as long as it is unclear for me which files/code is really the source of the documentation which is attached as docstring I do not want to touch this. I could not figure out where the simulate documentation comes from so far.

**Comment by kirichoi** [comment]
The doc source is located at: https://github.com/sys-bio/roadrunner/tree/develop/wrappers/Python/doc
What's actually presented online is from gh-pages branch: https://github.com/sys-bio/roadrunner/tree/gh-pages/python_docs
General procedure is to update docs in source, run sphinx, and put the output in gh-pages branch.
More information is located here: http://libroadrunner.org/howto-update-the-libroadrunner-online-documentation/

**Comment by kirichoi** [comment]
Error is resolved in 7a555dcbcd6ac9894de4b3323eec5d90b41757ae but doc needs more content
