### ISSUE TITLE
Load model in multiple roadrunner instances not possible

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#305]
The hashing of SBML models within RoadRunner is very useful to reduce load times. But there has to be an option to load the same model into two separate instances.

This is crucial for the libsedml implementation. In the following I need two instances of the same model. As soon as I change something in mod2 it changes also mod1. 
```
# --------------------------------------------------------
# Models
# --------------------------------------------------------
# Model <mod1>
mod1 = te.loadSBMLModel(os.path.join(workingDir, 'testcase_08.xml'))
# Model <mod2>
mod2 = te.loadSBMLModel(os.path.join(workingDir, 'testcase_08.xml'))
mod2['init([S1])'] = 5
```
How can I get 2 instances of the same SBML?

**Comment by matthiaskoenig** [comment]
@0u812 
this is the the only thing I need fixed urgently to finish the sedml support
Is there any way to clone RoadRunner instances, something like
```
mod2 = r.clone(mod1)
```
The only way I see right now is to write some additional info in the SBML so that the hash changes. 
But this is a very bad solution I don't really want to implement. Would be much better to either
- be able to clone roadrunner instances
- force the model loading to return a new instance (via flag, argument to RoadRunner()) even if model with hash exists
M

**Comment by 0u812** [comment]
It turns out this is already possible with the LOADSBMLOPTIONS_RECOMPILE config option:
```
import roadrunner
from roadrunner import RoadRunner, Config
Config.LOADSBMLOPTIONS_RECOMPILE = True
r1 = RoadRunner('feedback.xml')
r2 = RoadRunner('feedback.xml')
query = 'init([S1])'
r1[query] = 1.
print('{} vs {}'.format(r1[query], r2[query]))
```
```
1.0 vs 2.0
```

**Comment by matthiaskoenig** [comment]
Perfect. Closed. 
Did not know about this option.
