### ISSUE TITLE
Update steadyState information in tutorial

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#311]
Some additional information in the steady state documentation would be useful:
http://sys-bio.github.io/roadrunner/python_docs/steady_state.html

It should mention/demonstrate
- `r.conservedMoietyAnalysis` (how to set, why to set)
- How to set/get steadyState solver and settings on the solver

```
r.setSteadyStateSolver('nleq')
solver = r.getSteadyStateSolver()
print(solver.settingsPyDictRepr())
```
- How to see the available steady state solvers

```
print(r.getRegisteredSteadyStateSolverNames())
```

**Comment by matthiaskoenig** [comment]
The name of the steady state solver should be `nleq1` instead of `nleq` to be exact which version is used. There is also an `nleq2` which has very similar function signatures to `nleq1`. The nleq1 seems to be the newer version.
http://elib.zib.de/pub/elib/codelib/en/nonlin.html

**Comment by hsauro** [comment]
Agreed.

Herbert
