### ISSUE TITLE
Variable Step size simulation not simulating to end time

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#316]
see also #254 
Again this issue. There should be a multitude of tests for this. Probably the boundary case of 1 step/2 points.

With roadrunner just compiled from source.
`1.4.4; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler: LLVM-3.4; Date: Mar 30 2016, 15:48:38;`
[example.zip](https://github.com/sys-bio/roadrunner/files/195706/example.zip)

```
"""
Single integration step with roadrunner.

For the dynamical adaption of the step size a single step must be integrated
with the ODE solver.
"""
from __future__ import print_function, division
import roadrunner
print(roadrunner.__version__)
 LibSBML Version: 5.12.0

# Load model results in warnings about fbc v2
ode_bounds_file = "toy_ode_bounds.xml"
rr = roadrunner.RoadRunner(ode_bounds_file)

# simulate multiple steps
result = rr.simulate(start=0, end=10, steps=5)
print(result)

# simulate multiple steps with variable steps
# ERROR: Does not integrate until 1
rr.integrator.setSetting("variable_step_size", True)
result = rr.simulate(start=0, end=1, points=2)
print(result)

# ERROR: Does not integrate until 1
result = rr.simulate(start=0, end=1, steps=1)
print(result)
```

The two single step simulations do not integate until 1
```
/usr/bin/python2.7 /home/mkoenig/git/wholecell-metabolism/mkoenig/python/metabolism/toymodel/notebooks/test.py
1.4.4; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler: LLVM-3.4; Date: Mar 30 2016, 15:48:38; LibSBML Version: 5.12.0
    time,    ub_R1
 [[    0,        1],
  [    2, 0.670313],
  [    4,  0.44935],
  [    6, 0.301225],
  [    8, 0.201928],
  [   10, 0.135364]]

         time,    ub_R1
 [[         0, 0.135364],
  [ 0.0111808, 0.135062]]

         time,    ub_R1
 [[         0, 0.135062],
  [ 0.0111808,  0.13476]]
```

**Comment by 0u812** [comment]
Strictly speaking, you can't mix end time and steps for variable stepping. If you specify end time, it will integrate until the time you specify. If you specify steps, it will give you that exact number of steps, but you don't get to control where the steps are. The delta t of the steps is determined by the integrator.

I think you can achieve the effect you want by just turning variable steps off.

On March 30, 2016 7:22:58 AM PDT, "Matthias König" <notifications@github.com> wrote:
>see also #254 
>Again this issue. There should be a multitude of tests for this.
>Probably the boundary case of 1 step/2 points.
>
>With roadrunner just compiled from source.
>`1.4.4; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler:
>LLVM-3.4; Date: Mar 30 2016, 15:48:38;`
>[example.zip](https://github.com/sys-bio/roadrunner/files/195706/example.zip)
>
>```
>"""
>Single integration step with roadrunner.
>
>For the dynamical adaption of the step size a single step must be
>integrated
>with the ODE solver.
>"""
>from __future__ import print_function, division
>import roadrunner
>print(roadrunner.__version__)
> LibSBML Version: 5.12.0
>
># Load model results in warnings about fbc v2
>ode_bounds_file = "toy_ode_bounds.xml"
>rr = roadrunner.RoadRunner(ode_bounds_file)
>
># simulate multiple steps
>result = rr.simulate(start=0, end=10, steps=5)
>print(result)
>
># simulate multiple steps with variable steps
># ERROR: Does not integrate until 1
>rr.integrator.setSetting("variable_step_size", True)
>result = rr.simulate(start=0, end=1, points=2)
>print(result)
>
># ERROR: Does not integrate until 1
>result = rr.simulate(start=0, end=1, steps=1)
>print(result)
>```
>
>The two single step simulations do not integate until 1
>```
>/usr/bin/python2.7
>/home/mkoenig/git/wholecell-metabolism/mkoenig/python/metabolism/toymodel/notebooks/test.py
>1.4.4; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler:
>LLVM-3.4; Date: Mar 30 2016, 15:48:38; LibSBML Version: 5.12.0
>    time,    ub_R1
> [[    0,        1],
>  [    2, 0.670313],
>  [    4,  0.44935],
>  [    6, 0.301225],
>  [    8, 0.201928],
>  [   10, 0.135364]]
>
>         time,    ub_R1
> [[         0, 0.135364],
>  [ 0.0111808, 0.135062]]
>
>         time,    ub_R1
> [[         0, 0.135062],
>  [ 0.0111808,  0.13476]]
>```
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/316

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by matthiaskoenig** [comment]
Perfect. Closed than.
Before the behavior was different, but I prefer the new behavior.
Thanks.

On Wed, Mar 30, 2016 at 8:33 PM, Kyle Medley <notifications@github.com>
wrote:

> Strictly speaking, you can't mix end time and steps for variable stepping.
> If you specify end time, it will integrate until the time you specify. If
> you specify steps, it will give you that exact number of steps, but you
> don't get to control where the steps are. The delta t of the steps is
> determined by the integrator.
>
> I think you can achieve the effect you want by just turning variable steps
> off.
>
> On March 30, 2016 7:22:58 AM PDT, "Matthias König" <
> notifications@github.com> wrote:
> >see also #254
> >Again this issue. There should be a multitude of tests for this.
> >Probably the boundary case of 1 step/2 points.
> >
> >With roadrunner just compiled from source.
> >`1.4.4; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler:
> >LLVM-3.4; Date: Mar 30 2016, 15:48:38;`
> >[example.zip](
> https://github.com/sys-bio/roadrunner/files/195706/example.zip)
> >
> >```
> >"""
> >Single integration step with roadrunner.
> >
> >For the dynamical adaption of the step size a single step must be
> >integrated
> >with the ODE solver.
> >"""
> >from __future__ import print_function, division
> >import roadrunner
> >print(roadrunner.__version__)
> > LibSBML Version: 5.12.0
> >
> ># Load model results in warnings about fbc v2
> >ode_bounds_file = "toy_ode_bounds.xml"
> >rr = roadrunner.RoadRunner(ode_bounds_file)
> >
> ># simulate multiple steps
> >result = rr.simulate(start=0, end=10, steps=5)
> >print(result)
> >
> ># simulate multiple steps with variable steps
> ># ERROR: Does not integrate until 1
> >rr.integrator.setSetting("variable_step_size", True)
> >result = rr.simulate(start=0, end=1, points=2)
> >print(result)
> >
> ># ERROR: Does not integrate until 1
> >result = rr.simulate(start=0, end=1, steps=1)
> >print(result)
> >```
> >
> >The two single step simulations do not integate until 1
> >```
> >/usr/bin/python2.7
>
> >/home/mkoenig/git/wholecell-metabolism/mkoenig/python/metabolism/toymodel/notebooks/test.py
> >1.4.4; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler:
> >LLVM-3.4; Date: Mar 30 2016, 15:48:38; LibSBML Version: 5.12.0
> > time, ub_R1
> > [[ 0, 1],
> > [ 2, 0.670313],
> > [ 4, 0.44935],
> > [ 6, 0.301225],
> > [ 8, 0.201928],
> > [ 10, 0.135364]]
> >
> > time, ub_R1
> > [[ 0, 0.135364],
> > [ 0.0111808, 0.135062]]
> >
> > time, ub_R1
> > [[ 0, 0.135062],
> > [ 0.0111808, 0.13476]]
> >```
> >
> >
> >---
> >You are receiving this because you are subscribed to this thread.
> >Reply to this email directly or view it on GitHub:
> >https://github.com/sys-bio/roadrunner/issues/316
>
> --
> Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sys-bio/roadrunner/issues/316#issuecomment-203569871>
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480
