### ISSUE TITLE
What is the difference between oneStep and Integrate?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#319]
I noticed in the docs we have oneStep and integrate, what's the difference?

**Comment by kirichoi** [comment]
There's not much of a difference between these two. There seems to be an attempt to deprecate onestep at some point. Now, was `integrate` designed to take two time points instead of a timepoint and step size? Because I don't think it's working that way right now.

**Comment by hsauro** [comment]
Deprecate integrate. DO NOT DEPRECATE oneSTEP

**Comment by Peter-J** [comment]
@kirichoi absoluely, `integrate` does not work the way the variable-names let you believe. Deprecate `integrate`

**Comment by hsauro** [comment]
Agree deprecate integrate, keep onestep, that's been there since the dawn
of time, plus it says what it does.

Herbert

**Comment by kirichoi** [comment]
Commit 384c176ffa1f5f5445342ebd28b9c59b44827938 deprecates the integrate function from documents. However, code is not removed just in case other functions depend on it. One this is sorted, remove:

ln 176 - 179 in rrRoadRunner.h
ln 1547 - 1562 in rrRoadRunner.cpp
