### ISSUE TITLE
Equations not rendered in current Python docs

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#324]
When I go to the Python Sphinx docs, I get the raw Latex equations instead of the rendered formulae. Kiri, can you confirm if you see the same thing? If yes, I think something went wrong with building the docs. Example: the MCA page:
http://sys-bio.github.io/roadrunner/python_docs/metabolic.html

**Comment by hsauro** [comment]
I'm seeing that too.

Herbert

**Comment by kirichoi** [comment]
Sphinx 1.4 and upwards breaks current setup. Something to keep in mind.
