### ISSUE TITLE
Is there a way to get the current state of the conservation moiety flag in the C API?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#327]
The following method can be used to set the conservation moiety flag from the C API. Is there a way to get the current value of the flag in the C API?

bool rrcCallConv setComputeAndAssignConservationLaws(RRHandle handle, const bool On_Or_Off);

**Comment by 0u812** [comment]
It looks like there was not. I added it:
```
C_DECL_SPEC int rrcCallConv getComputeAndAssignConservationLaws(RRHandle handle, int* value)
```
You pass in an int to store the value. It's 32-bit on a 32-bit compiler. There are no bools in this version of C. Totte didn't know that so the API is littered with them.
