### ISSUE TITLE
Docs unavailable on libroadrunner

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#329]
Python, C, C++ docs are unavailable on libroadruner.org.

Requires immediate attention.

![image](https://cloud.githubusercontent.com/assets/1054990/15198181/9ece888a-178a-11e6-8b73-7e7d95c4b9e9.png)

**Comment by kirichoi** [comment]
Highly doubt this is a problem from doc side. Probably problem on wordpress. I do not have access to roadrunner website. @0u812 Can you check what's going on?

**Comment by hsauro** [comment]
Must be a problem on the github side: the python link it is trying to
access is:

http://sys-bio.github.io/roadrunner/python_docs/index.html

Is that the right path?

H

**Comment by 0u812** [comment]
Who owns the libroadrunner.org domain?

**Comment by 0u812** [comment]
This problem appears to be caused by whoever owns the 
docs.libroadrunner.org domain. It doesn't appear to work anymore. I 
changed the GH pages domain, but it could take a day to update.

**Comment by hsauro** [comment]
We do.

H

**Comment by hsauro** [comment]
Documentation still inaccessible (5.38pm).

**Comment by 0u812** [comment]
As I said it may take a day for the dns change to take effect.

On May 11, 2016 5:39:10 PM PDT, Herbert Sauro <notifications@github.com> wrote:
>Documentation still inaccessible (5.38pm).
>
>On Wed, May 11, 2016 at 4:27 PM, Herbert Sauro <uw.hsauro@gmail.com>
>wrote:
>
>> We do.
>>
>> H
>>
>> On Wed, May 11, 2016 at 4:09 PM, Kyle Medley
><notifications@github.com>
>> wrote:
>>
>>> Who owns the libroadrunner.org domain?
>>>
>>> On 5/11/16 3:59 PM, Herbert Sauro wrote:
>>> > Must be a problem on the github side: the python link it is trying
>to
>>> > access is:
>>> >
>>> > http://sys-bio.github.io/roadrunner/python_docs/index.html
>>> >
>>> > Is that the right path?
>>> >
>>> > H
>>> >
>>> > On Wed, May 11, 2016 at 3:52 PM, Kiri Choi
><notifications@github.com>
>>> > wrote:
>>> >
>>> > > Highly doubt this is a problem from doc side. Probably problem
>on
>>> > > wordpress. I do not have access to roadrunner website. @0u812
>>> > > <https://github.com/0u812> Can you check what's going on?
>>> > >
>>> > > —
>>> > > You are receiving this because you authored the thread.
>>> > > Reply to this email directly or view it on GitHub
>>> > >
>>> > <
>>>
>https://github.com/sys-bio/roadrunner/issues/329#issuecomment-218613691>
>>> > >
>>> >
>>> > —
>>> > You are receiving this because you were mentioned.
>>> > Reply to this email directly or view it on GitHub
>>> > <
>>>
>https://github.com/sys-bio/roadrunner/issues/329#issuecomment-218615019>
>>>
>>> >
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly or view it on GitHub
>>>
><https://github.com/sys-bio/roadrunner/issues/329#issuecomment-218616755>
>>>
>>
>>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/329#issuecomment-218630020

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by kirichoi** [comment]
Docs are accessible for me now.

**Comment by hsauro** [comment]
Not for me yet. What changed?

H

**Comment by 0u812** [comment]
I changed the site to stop using docs.libroadrinner.org. I don't know why it suddenly stopped working but subdomains usually cost extra.

On May 11, 2016 5:51:09 PM PDT, Herbert Sauro <notifications@github.com> wrote:
>Not for me yet. What changed?
>
>H
>
>On Wed, May 11, 2016 at 5:45 PM, Kiri Choi <notifications@github.com>
>wrote:
>
>> Docs are accessible for me now.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/sys-bio/roadrunner/issues/329#issuecomment-218630791>
>>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/roadrunner/issues/329#issuecomment-218631564

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by 0u812** [comment]
Btw the WordPress site is fine. The links are correct, so please do not change them.

On May 11, 2016 5:57:19 PM MST, Kyle Medley <medjk@comcast.net> wrote:
>I changed the site to stop using docs.libroadrinner.org. I don't know
>why it suddenly stopped working but subdomains usually cost extra.
>
>On May 11, 2016 5:51:09 PM PDT, Herbert Sauro
><notifications@github.com> wrote:
>>Not for me yet. What changed?
>>
>>H
>>
>>On Wed, May 11, 2016 at 5:45 PM, Kiri Choi <notifications@github.com>
>>wrote:
>>
>>> Docs are accessible for me now.
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly or view it on GitHub
>>>
>><https://github.com/sys-bio/roadrunner/issues/329#issuecomment-218630791>
>>>
>>
>>
>>---
>>You are receiving this because you were mentioned.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/sys-bio/roadrunner/issues/329#issuecomment-218631564
>
>-- 
>Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
Still not working at my end, taking time to propagate I guess.

H

**Comment by 0u812** [comment]
They seem to be working now.

**Comment by hsauro** [comment]
Yes they started working at home at around 9pm.

I haven't checked but did someone update the docs with the new consevation
get method?

HErbert
