### ISSUE TITLE
Bug in C API getStoichiometryMatrix

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#330]
Calling getStoichiometryMatirx in the C API returns the reduced stoichiometry matrix. I am assuming expected behavior is that it should return the full stoichiometry matrix because we already have a method to get the reduced stoichiometry matrix (getNrMAtrix).

One thing I noticed, if I set setComputeAndAssignConservationLaws (false); then it returns the full matrix.

**Comment by 0u812** [comment]
Yes it looks like it was calling the wrong function internally. Will fix it. Do you want to keep the name getStoichiometryMatrix or change it to getFullStoichiometryMatrix?

**Comment by hsauro** [comment]
Better keep the same name.

H

**Comment by 0u812** [comment]
Okay I think I fixed it. Please let me know if you have any trouble with this method since I don't have a quick way to test the C API. I will send you the binaries momentarily.

**Comment by 0u812** [comment]
Binaries here:
https://github.com/sys-bio/roadrunner/releases/download/1.4.5/roadrunner-1.4.5-vs12-llvm-3.5-win32.zip

**Comment by hsauro** [comment]
Yes that seems to work, thanks.

Herbert
