### ISSUE TITLE
Add test case to test C API method: getStoichiometrytMatrix()

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#331]
Add a test case to test the getStoichiometryMatrix in the C API.  Currently this method returns the reduced stoichiometry matrix but I think it should return the full matrix because we already have a method to return the reduced matrix. 

Use the following model as a test model:

A -> B

The full stoichiometry matrix is [-1, 1], currently the method returns [-1], it should return [-1,1]

**Comment by 0u812** [comment]
Gated on #330

**Comment by 0u812** [comment]
Btw gated means don't proceed until #330 is resolved :)

**Comment by 0u812** [comment]
#330 has been resolved. Okay to proceed.

**Comment by kirichoi** [comment]
Added test case
