### ISSUE TITLE
python undefined symbol

### ISSUE THREAD

**Issue by ivomaintz** [sys-bio/roadrunner#332]
My system: ubuntu 16.04 amd64
self-compiled: numl 1.0.1, nleq 2.4.0.1, libsbml 5.13.0, rr-libstruct 1.3, sundials  2.6.2, poco 1.7.2,
libsedml 0.4.1
[cmake_options.txt](https://github.com/sys-bio/roadrunner/files/261491/cmake_options.txt)
[cmake_log.txt](https://github.com/sys-bio/roadrunner/files/261502/cmake_log.txt)
[buildlog.txt](https://github.com/sys-bio/roadrunner/files/261504/buildlog.txt)

Other tools and libs are nativ, and I used llvm 3.5 (llvm 3.6 didn't work)

Building and installing roadrunner worked, but if I try  load the python module, I get

ImportError: /usr/lib/x86_64-linux-gnu/libf2c.so.2: undefined symbol: MAIN__

I added -u MAIN__ before -lf2c in $BUILDDIR/wrappers/Python/roadrunner/CMakeFiles/_roadrunner.dir/link.txt,, but this didn't help.

How could I fix this?

Thanks,

Ivo

**Comment by 0u812** [comment]
It looks like a problem with the build setup. We have conda packages, which is a much easier alternative to building from source. Here are the instructions for installing via `conda`:
http://libroadrunner.org/install/

**Comment by 0u812** [comment]
Fyi if you're still stuck on this, Matthias shared his build script here: https://github.com/sys-bio/roadrunner/issues/334
