### ISSUE TITLE
steadyState call not following documentation

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#333]
The call steadyState() should return the sums of squares of the dx/dt vector to indicate how close the solution is to the steady state. This functionality was recently changed so that now it returns the vector of steady state concentrations. 

The current functionality shown below should be changed to the original behavior

r.steadyState()
Out[36]: 
       [S1]   <-- Current behavior, change to old way to doing it (as described in docs)
 [[ 1.33333]]

Note getSteadyStateVector() already returns a vector of steady state concentrations. Rather than modify the existing API, **add a new method** getNameSteadyStateVector() that includes the column headings.

**Comment by hsauro** [comment]
We're having mroe issues crop up from users because of this issue. I've upgraded the issue to urgent.

**Comment by 0u812** [comment]
Binaries https://github.com/sys-bio/roadrunner/releases/tag/1.4.7
