### ISSUE TITLE
Is it possible to get the list of generated ODEs from libroadrunner

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#335]
Is it possible to get the list of generated ODEs from libroadrunner so that a user can inspect them?

**Comment by 0u812** [comment]
I don't think so - they go straight from SBML to LLVM IR. Do you have a model where you suspect it is generating the wrong ODEs?

**Comment by hsauro** [comment]
No, it's just a means to double check something for a user. Might be worth
adding something in the future.

Herbert

**Comment by yarden** [comment]
This would be a useful feature. There isn't a simple way to get a list of readable ODEs from SBML as far as I know; SBML2LaTeX is closest I've seen, but its output is overkill for most purposes.

**Comment by hsauro** [comment]
I agree, I needed this feature the other week. We've had it on previous
tools but it didn't end up in libRoadRunner. I'll add to github issue. I
thikn it should be part of libroadrunner rather than say an external
function.

Herbert
