### ISSUE TITLE
GillespieIntegrator not producing RCLL-Paths with variable_step_size=FALSE

### ISSUE THREAD

**Issue by Peter-J** [sys-bio/roadrunner#336]
Hi,

with `variable_step_size=FALSE` the GillespieIntegrator does not produce RCLL-Paths as in GillespieIntegrator.cpp
Line 236 `while (t < tf)`
allows the code to update the chemical-species even if
Line 277 `t = t + tau `
is greater than tf. It then returns the first value after time tf instead of last value before.

Therefore no RCLL-Path but instead something similar to a LCRL-Path is produced.

For `variable_step_size=TRUE` you already adressed this problem for the last time-point in
https://github.com/sys-bio/roadrunner/issues/318#issuecomment-214811991
"flat interpolation instead of linear interpolation"
but this error is still unsolved for `variable_step_size=FALSE`

as can be seen for any point in time in:

```
x = 2345 #or any other
r.getIntegrator().setValue('variable_step_size', True)
r.reset()
r.getIntegrator().setValue('seed', x)
s = r.simulate(0, 1) 
print(s)
r.getIntegrator().setValue('variable_step_size', False)
r.reset()
r.getIntegrator().setValue('seed', x)
s = r.simulate(0, 1,points=5) 
print(s)
```

A simple `if (t + tau > tf) return tf;' in Line 276 should do the job.
Update 2016-07-08: Almost ... look further down.

**Comment by Peter-J** [comment]
I updated the above issue

Here is sample output for model
```
antStr = '''
model feedback()
	// Reactions:
	R1: E + R -> H; N^(k1)*E*R/200;
	R2: H -> E + R; N^(k2)*H/200;
	R3: H -> E + P; N^(k3)*H/200;
	// Species initializations:
	k1 = 1; k2 = 3; k3 = 2; N = 500;
	E = 100; R = N; H = 0; P = 0;
	Rn := R/N; Pn := P/N; Hn := H/100;
end'''
```
and `variable_step_size = TRUE`
```
  [ 500,    0.249998, 0.878,  0.12, 0.01],
  [ 500,    0.250002,  0.88,  0.12,    0],
  [ 500,    0.499981,  0.77,  0.23,    0],
  [ 500,    0.500002, 0.768,  0.23, 0.01],
  [ 500,    0.749988, 0.668, 0.332,    0],
  [ 500,    0.750007, 0.666, 0.332, 0.01],
  [ 500,    0.999999, 0.596, 0.404,    0],
  [ 500,     1.00001, 0.594, 0.404, 0.01],
```

same points of time for `variable_step_size = FALSE`
```
      N, time,    Rn,    Pn,   Hn
 [[ 500,    0,     1,     0,    0],
  [ 500, 0.25,  0.88,  0.12,    0],
  [ 500,  0.5, 0.768,  0.23, 0.01],
  [ 500, 0.75, 0.666, 0.332, 0.01],
  [ 500,    1, 0.594, 0.404, 0.01]]
```

You can see `variable_step_size = FALSE` always returns the values AFTER the first reaction after the specified point of time.

**Comment by 0u812** [comment]
As pointed out in #318 the Gillespie solver doesn't even produce correct trajectories for `variable_step_size=false`. Can you explain why you are trying to use it?

**Comment by Peter-J** [comment]
As far as I observed the only error in `variable_step_size=false` is that the wrong point in time is choosen.
The error matthiaskoenig observes in #318 is easily explained with my Claim: His simulation returns the time point x but the values after the first reaction after time x even if x is verry verry small and the next reaction takes place at around 4-10 sekonds. As he has only one reaction at all GillespieIntegrator.cpp will always return the values after this one and only reaction and claim it belongs to the first point of time as GillespieIntegrator.cpp produces LCRL-Paths instead of RCLL-Paths.

As part of my diploma thesis I claim FDD-Convergence (in certain settings) and I want to illustrate that by plotting some distributions for fixed points of time.
My example reaction network is scaled with N and the number of expected reactions is 2*N^2. Using `variable_step_size=true` and extracting the points of time I am interested in after the simulation run (t= [0,3.01]) yields memory-errors for N=1800 on Windows (as roadrunner is 32bit on Windows) and N=10.000 on Linux 64bit fills about 24GB of Memory.
I have not found an option to discard any unwanted point of time during simulation except `variable_step_size=false` and I see no need to fill up my Memory with unnecessary data as the Gillespie-Algorithm itself only uses the last point of time to calculate the next one.
I now hav access to the computation-pool of my university but memory installed is only 8GB per machine so max around N=5000 before getting memory errors ... which is not much for N to infinity ...

**Comment by Peter-J** [comment]
Just assume you have a single reaction that takes place exactly at time 8 and you ask GillespieIntegrator whats the value at time 2 you will get the following problem as the values AFTER the first reaction AFTER time 2 is are returned
![gillespie-error](https://cloud.githubusercontent.com/assets/20210370/16578477/0b3e314c-429b-11e6-9069-f5acd50cfcf6.PNG)
what it should be:
![rcll-path](https://cloud.githubusercontent.com/assets/20210370/16578423/c0a1ea2a-429a-11e6-8b2d-aa2831eeb55a.PNG)

**Comment by hsauro** [comment]
Would a one step Gillespie method be of help? ie it just computes the next
time point from the current state?. This would avoid the precollection of
huge amount of data. With a one step method you could chose whether to keep
the point or not. You'd have to write a small piece of code to set up a
loop (either in python, C or C++) but that's about it.

Herbert Sauro

**Comment by Peter-J** [comment]
I really have no clue why both of you suggest a workaround instead of fixing the problem itself. One of you or your predecessors implemented 'variable_step_size=FALSE' for a good reason, is there no ambition in fixing a useful option? 

I try to express the problem I found in other words:
You only check the `while (t < tf)` condition at the beginning of each loop but since `tau` is random you can not predict if `t + tau <= tf` or if 't + tau > tf' (violating the while condition and moving out of the timeframe you expect your algorithm to stay within) therefore you have to check your condition again before updating the species-amounts and before putting 't = t + tau'.
If you want to produce RCLL-Paths (just like jarnac / coapsi does and any mathematician would expect the algorithm to do) you have to stop before you violate the while condition and not after.

This is a simple bug that, I am sure, any one of you would easily spot if one of your students would ask you for help with their code. This is a problem all of us have after a while, we get used to our own code / to-be-publications and are no longer able to spot the most obvious mistakes. Please take a step back and look at your while loop (in GillespieIntegrator.cpp) as a simple while loop without predictable step-sizes.

_Why I do not intend to settle for a workaround instead of a fix:_
I noticed that most of the bio-systems / stochastics staff at my university still use R (some use MATLAB) to simulate biochemical-reaction-networks and I really would like to introduce libRoadRunner to them. 
I went to great lengths (administration) to implement libRoadRunner in the computation-pool of my department and at this very moment I am running simulations of the above mentioned SRN with growing N, not to gain interesting data or to fit anything, but to find the computational speeds and limits / boundaries of those software, to show them why / in what settings libRoadRunner should be the first choice.

Best regards
Peter

**Comment by hsauro** [comment]
In that case let's fix it. A predecessor wrote the Gillespie code so I'm
not too familiar with it's design hence my alternate suggestion. However
Kyle is now the current maintainer.

Kyle could you work with Peter to fix the issue?

Kyle is working on another project temporarily but maybe this weekend his
can sort it out?

Herbert

**Comment by Peter-J** [comment]
My suggestion:
Add
if (getValue("variable_step_size").convert<bool>() && (t + tau > tf))
{
 return t;
}

**Comment by Peter-J** [comment]
My suggestion:
Add
```
if (!(getValue("variable_step_size").convert<bool>()) && (t + tau > tf))
{
    return t;
}
```
to line 276 of `GillespieIntegrator.cpp`.
The first condition is to guarantee `variable_step_size==True` is not affected.

Compile it & test it.
If it works: Great. (99.9% sure)
If it doesn't ... forget it.

**Comment by Peter-J** [comment]
`variable_step_size==TRUE` + `minimum_time_step > 0` ==> another bug.
With the above example SRN:
```
r.getIntegrator().setValue('variable_step_size', True)
r.getIntegrator().setValue('minimum_time_step', 0.1)
r.reset()
r.getIntegrator().setValue('seed', 2345)
s = r.simulate(0, 1)
print(s)
```
True values:
```
[ 500,    0.900127, 0.616, 0.382, 0.01],
[ 500,    0.999999, 0.596, 0.404,    0],
[ 500,     1.00001, 0.594, 0.404, 0.01],
```
and with `variable_step_size==TRUE` + `minimum_time_step = 0.1' you get
```
[ 500, 0.900127, 0.616, 0.382, 0.01],
[ 500,        1, 0.616, 0.382, 0.01]]
```
It is pretty obvious what happens ... no update because 0.900127 + 0.1 > 1.
Give me an hour to think about it. I think it is possible to fix both problems at once.

**Comment by Peter-J** [comment]
Ok, I think I got it. Stay with me, this will be lengthy.
I used `Logger.enableFileLogging('log.txt',Logger.LOG_DEBUG)` and found for `variable_step_size=TRUE && minimum_time_step = 0.1`
```
Debug: variable step, start: 0.902407, end: 1
Debug: ssa(0.902407, 1.00241)
```
i therefore assume the integrate call comes from `rrRoadRunner.cpp` Line 1346-1348. **Especially: In this Case hstep (in GillespieIntegrator.cpp) equals timeEnd (in rrRoadRunner.cpp).**

For `variable_step_size=TRUE && minimum_time_step = 0` i got 
```
Debug: variable step, start: 0.999986, end: 1
Debug: ssa(0.999986, 1.99999)
```
**which proofs the hypothesis that in case of `variable_step_size=TRUE` we have `hstep == endTime`.**

For `variable_step_size=FALSE` i got
```
Debug: Step 4
Debug: ssa(0.75, 1)
```
I therefore assume this call is from rrRoadRunner.cpp Line 1520-1521.

The solution to all problems is (i marked the lines I changed / added with `// -------------`)

```
double GillespieIntegrator::integrate(double t, double hstep)
	{
		double tf = 0;
		bool singleStep;
		double timeEnd = 1; // -------------------------------------------

		assert(hstep > 0 && "hstep must be > 0");

		if (getValue("variable_step_size").convert<bool>())
		{
			timeEnd = hstep; //------------------------------------
			if (getValue("minimum_time_step").convert<double>() > 0.0)
			{
				tf = t + getValue("minimum_time_step").convert<double>();
				singleStep = false;
			}
			else
			{
				tf = hstep; // -----------------------------------
				singleStep = true;
			}
		}
		else
		{
			tf = t + hstep;
			timeEnd = t + hstep; // ---------------------------------
			singleStep = false;
		}

		Log(Logger::LOG_DEBUG) << "ssa(" << t << ", " << tf << ")";

		// get the initial state vector
		model->setTime(t);
		model->getStateVector(stateVector);

		while (t < tf)
		{
			// random uniform numbers
			double r1 = urand();
			double r2 = urand();

			assert(r1 > 0 && r1 <= 1 && r2 >= 0 && r2 <= 1);

			// sum of propensities
			double s = 0;

			// next time
			double tau = 0;

			// get the 'propensity' -- reaction rates
			model->getReactionRates(nReactions, 0, reactionRates);

			// sum the propensity
			for (int k = 0; k < nReactions; k++)
			{
				Log(Logger::LOG_DEBUG) << "reac rate: " << k << ": "
					<< reactionRates[k];

				// if reaction rate is negative, that means reaction goes in reverse,
				// this is fine, we just have to reverse the stoichiometry,
				// but still need to sum the absolute value of the propensities
				// to get tau.
				s += std::abs(reactionRates[k]);
			}

			// sample tau
			if (s > 0)
			{
				tau = -log(r1) / s;
			}
			else
			{
				// no reaction occurs
				return std::numeric_limits<double>::infinity();
			}
			if (t + tau > timeEnd) // ------------------
			{                              // -------------------
				return t;  // -----------------
			}                     // ----------------------
			t = t + tau;

			// select reaction
```
and by the way, with this fix Lines 1369-1384 in rrRoadRunner.cpp will never ever fire again.

**Comment by hsauro** [comment]
Kyle, hope you can work on this over the weekend.

Herbert

**Comment by Peter-J** [comment]
Just noticed my proposal would / could damage integrate() and oneStep().
Reason: hstep really hase to be a timeStep and "timeEnd" is just a big timeStep to give enough time. We therefore have to extract timeEnd using another Method.

```
double timeStart = Config::getDouble(Config::SIMULATEOPTIONS_START);
double duration = Config::getDouble(Config::SIMULATEOPTIONS_DURATION);
double timeEnd = timeStart + duration;
```
I will update the above code and GillespieIntegrator.txt

Here some thoughts I had inbetween:
> Ok the Problems go on:
> 
> There is inconsistency in `rrRoadRunner.cpp`
> 
> Second Argument is End-Time:
> Line 1348 rr.simulate - variable time step `tout = self.integrator->integrate(tout, timeEnd);`
> Line 1555 rr.integrate `return impl->integrator->integrate(t0, tf);`
> 
> Second Argument is StepSize:
> Line 1463 rr.simulate - stochastic fixed step: tout = `self.integrator->integrate(tout, next - tout);` (not used .. according to LOG_DEBUG from above)
> Line 1521 rr.simulate - deterministic fixed step: `double itime = self.integrator->integrate(tout, hstep);`
> Line 1574 rr.oneStep: `return self.integrator->integrate(currentTime, stepSize);`
> 
> 
> Therefore: `variable_step_size=FALSE` --> `hstep` is probably a real step except a call came from `integrate()`
> but `variable_step_size=TRUE` --> `hstep` is probably timeEnd but might be stepSize from `oneStep()`
> 
> The behaviour of `oneStep(currentTime, stepSize)`, Cases:
> 
> 1. 
> 
>  `variable_step_size = TRUE` and `minimum_time_step = 0` ==> until now we got exactly one Reaction, `stepSize` didn't matter at all as long as it was positive  ... but from now on?
> 2. `variable_step_size = TRUE` and `minimum_time_step > 0` ==> until now we got all reactions in the time frame `[currentTime , currentTime + minimum_time_step]`. Again `stepSize` didn't matter at all. ... but from now on?
> 3. `variable_step_size = FALSE` ==> we get the reactions in the time frame `[currentTime , currentTime + stepSize]`
> 
> The behaviour of `integrate(t_start, t_end)`, Cases:
> 
> 1. 
> `variable_step_size = TRUE` and `minimum_time_step = 0` ==> until now we got exactly one Reaction, `t_end` didn't matter at all as long as it was positive  ... but from now on?
> 2. `variable_step_size = TRUE` and `minimum_time_step > 0` ==> until now we got all reactions in the time frame `[currentTime , currentTime + minimum_time_step]`. Again `t_end` didn't matter at all. ... but from now on?
> 3. `variable_step_size = FALSE` ==> we get the reactions in the time frame `[currentTime , currentTime + t_end]`
> 
> As `variable_step_size=TRUE` is now standart both functions would primarily produce one Reactions and `integrate()` will continue to work (somewhat) as before ... but `oneStep()` now really needs a big `hstep` to produce one Reaction. For example `oneStep(10,1)` would defenitely not produce a Reaction as 1 is treated as `timeEnd`
> 
> `GillespieIntegrator.cpp` is build so that the second argument `hstep` is only used if `variable_step_size = FALSE` ....

**Comment by kirichoi** [comment]
Hi,
Sorry that this issue is taking longer than anticipated. We are currently very understaffed, with many people out of town. We will try to fix this issue asap.

Kiri

**Comment by 0u812** [comment]
@Peter-J I merged in some changes (#338) that I think should fix this, please let me know if not. I based the changes on your patch, but we can't use `SIMULATE_OPTIONS` anymore so I had to make some tweaks to your code. I don't fully understand what you're talking about regarding the `minimum_time_step` problem, so again please let me know if this doesn't fix everything.

**Comment by Peter-J** [comment]
**Short:** 
Best way would be to deprecate `integrate` and fix
https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/rrRoadRunner.cpp#L1348
to i.e. `tout = self.integrator->integrate(tout, timeEnd - tout);`
After this fix every call to the integrator will have `hstep` as step for sure and `tf = t + hstep` will always be `timeEnd` in any scenario.

**------------------Long: -------------- TL;DR -----------------------**

I will have a look if there is a way to get the build from Travis CI or compile it myself ... as soon as i got some spare time. I whish this https://github.com/sys-bio/roadrunner/wiki/Building-from-Source was a little bit more in depth ... but hey we all have the same problem ... lack of time.

Ok I see I should not have removed my ideas that I discarded.
Referencing
https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/GillespieIntegrator.cpp#L227
`tf = t + hstep; // FIXME: I think this should be tf = hstep -JKM`
no it should not BUT thats exactly what
https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/rrRoadRunner.cpp#L1348
makes you think it should be ... I had the same problem. 
The trick is line 1348 uses `timeEnd = hstep` as a really big step just to make sure the Integrator has enough time ... as `variableStep = true` the Integrator himself will choose what time it will return and the rest of the simulate method will check
https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/rrRoadRunner.cpp#L1362
if the Integrator has gone too far and fix it if necessary.

Every remaining call to the integrator really uses hstep as hstep and those other calls do not distinguish if `variableStep` or not. See:

https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/rrRoadRunner.cpp#L1463
https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/rrRoadRunner.cpp#L1521
https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/rrRoadRunner.cpp#L1574
With one more exception:
https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/rrRoadRunner.cpp#L1555 and docu: https://sys-bio.github.io/roadrunner/python_docs/api_reference.html?highlight=integrate#RoadRunner.RoadRunner.integrate

Looking at every Integrator you will see `hstep` is always treated as stepsize and thats what the variable name makes you think it should be ... I suggest to keep it that way

**Best way would be to deprecate `integrate` and fix** 
https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/rrRoadRunner.cpp#L1348
to i.e. `tout = self.integrator->integrate(tout, timeEnd - tout);` just like it already is in:
https://github.com/sys-bio/roadrunner/blob/9367e01b7eca02a99d16eae596454f2c31f40d2c/source/rrRoadRunner.cpp#L1463

**After this fix every call to the integrator will have `hstep` as step for sure and `tf = t + hstep` will always be `timeEnd` in any scenario.**

Regards
Peter

P.S.: If you now think of a work around to distinguish if `hstep` is a stepsize or timeEnd ...
I thought one could check if `hstep < t` so one could be sure `hstep` is a step and not `timeEnd` but what if  `t < hstep` ??? Now we don't know where the call came from and if the Integrator should run up to `t+hstep` or up to `hstep`. ... there really is no way to find out if `hstep` is a stepsize or timeEnd ... better make sure it always is what it says ...

**Comment by Peter-J** [comment]
Just discovered how to make changes on my own and let Travis-CI check if there are problems.
Made the changes and the pull request. Travis says my changes are fine :-)

Still have no clue how to compile it myself ... so waiting for anaconda/sys-bio/roadrunner update

**Comment by 0u812** [comment]
Thanks for your changes @Peter-J . It looks like they preserve the current behavior for variable step simulations (except, of course, for the last time point), so I am fine with merging these in. Working on the conda builds right now. Will be version 1.4.8.

**Comment by Peter-J** [comment]
Checked it whith all due diligence, I consider this fixed.
(Didn't have a chance to test it using compiled code).
