### ISSUE TITLE
setting a variable to have constant value?

### ISSUE THREAD

**Issue by yarden** [sys-bio/roadrunner#339]
I'm loading an SBML model for simulation in roadrunner and I'd like to set one of the species in the model to have a constant value (i.e. without editing the SBML file). 

For example if my species is called `A`, I know I can programmatically set its value using roadrunner as follows:

```
rr = roadrunner.RoadRunner("mymodel.xml")
rr.A = 20
```

However, I'd like to make it so A is held constant during the simulation, so that when I call:

```
rr.simulate(start=t_start, end=t_end, steps=1000)
```

the value of A remains constant through the simulation. Is this possible?
Thanks very much.

**Comment by hsauro** [comment]
This is an interesting question, sadly at the moment the short answer is
no. I have a grant proposal under review where The intent is to add the
ability to change a model at runtime including the ability to set a species
variable constant but also f example things like deleting or adding
reactions.

For the moment, you'll might have to take the long route, save the state of
the model, modify the sbml via libsbml and reload the model and saved
state. If I or anyone else can think of another strategy I'll let you know.
There are however numerous applications I can think of where changing a
model at runtime could be useful.

**Comment by yarden** [comment]
Thank you for your response. I found a workaround for my purposes and it's similar to what you described: I simulate the model starting with the configuration of the variables I want for a short duration, take the output, reset the variables, simulate again, and so on. This is how I implement "dosing". It's not identical to setting it as constant but it works for my purposes and doesn't require changing the SBML dynamically.

Hope your grant works out - roadrunner is an incredibly useful library, and allowed me to totally bypass MATLAB for this type of work. I wish our community appreciated software development more.

Yarden

**Comment by matthiaskoenig** [comment]
This is a recurring issue. 
Attached some example code on how to do this with tellurium and libsbml. Ipython notebook, python file, and HTML output in the attached zip.

```
from __future__ import print_function, division
import tellurium as te

# A is converted to B and consumed in the process
m1 = """
model m1()
    R1: A -> B; k1*A;
    k1 = 0.5; 
    A=10.0; B=0.0;
end
"""
r1 = te.loada(m1)
r1.simulate(start=0, end=10, steps=50)
r1.plot()

sbml_m1 = r1.getSBML()
# print(sbml_m1)

import libsbml
# get document and model
doc = libsbml.readSBMLFromString(sbml_m1)
model = doc.getModel()

# update model id
model.setId('m2')

# change boundaryCondition attribute
A = model.getSpecies("A")
A.setBoundaryCondition(True)

sbml_m2 = libsbml.writeSBMLToString(doc)
# print(sbml_m2)

# load the new model & simulate
r2 = te.loads(sbml_m2)
r2.timeCourseSelections = r2.timeCourseSelections + ['[{}]'.format(sid) for sid in r2.getBoundarySpeciesIds()]
r2.simulate(start=0, end=10, steps=50)
r2.plot()
```

[constant-species.zip](https://github.com/sys-bio/roadrunner/files/367828/constant-species.zip)

**Comment by matthiaskoenig** [comment]
In addition about strategies how to do this.

What I am doing in this cases is creating a comp model which includes the initial model with variable species as a submodel. I drive the model via the comp master model replacing the variable species with a defined constant species in the master comp model. 

This `feels` a bit cleaner than modifying the original SBML, because it is clearly defined what is changed via an outer comp model.
You could use antimony to create the outer comp model. When I find time I will post an example.

**Comment by hsauro** [comment]
If you dong dosing perhaps you can use events? Or use a spline to represent
the dosing regime?

**Comment by matthiaskoenig** [comment]
Yes, interpolation works.
I implemented this mainly as constant interpolation.
See the examples in

https://github.com/matthiaskoenig/sbmlutils/blob/master/sbmlutils/examples/notebooks/docs/Interpolation.ipynb

The constant interpolation just sets the value from the given timepoint until the next given timepoint. One would define the dosing regime in a table
```
time value
t1 y1
t2 y2
...
```
Create a constant interpolation from the dataset and drive a model parameter/species with it. I will write down the examples when I find time, i.e. the interpolation and the comp approach.

**Comment by hsauro** [comment]
Interesting, I'll keep your code in mind for future projects.

**Comment by yarden** [comment]
Thanks for the pointer to the example, @matthiaskoenig - it looks great and I'd love to use it. I managed to install tellurium on Mac OS X via the installer. However, I'd like to call tellurium as a library from a script without going through the whole Spyder IDE. Is there a way to install tellurium as a package directly (it's not on pypi as far as I can tell) without Spyder?

**Comment by hsauro** [comment]
I don't think tellurium is tied to spyder, it might be just a case of
moving the scripts from site-packages to your own distribution.

**Comment by matthiaskoenig** [comment]
It is not tied to spyder at all.

I am using tellurium on linux without spyder, but you are responsible to build/fullfill all the dependencies for tellurium.

I am building and installing mainly the following libraries with their respective python bindings in the given order (ignore the sh and tee things).
Other core python scientific packages should be in the environment, i.e numpy, scipy, matplotlib,

```
./libsbml.sh 2>&1 | tee ./logs/libsbml.log
./libcellml.sh 2>&1 | tee ./logs/libcellml.log
./libsedml.sh 2>&1 | tee ./logs/libsedml.log
./roadrunner.sh 2>&1 | tee ./logs/roadrunner.log
./antimony.sh 2>&1 | tee ./logs/antimony.log
./phrasedml.sh 2>&1 | tee ./logs/phrasedml.log
./sbml2matlab.sh 2>&1 | tee ./logs/sbml2matlab.log
./tellurium.sh 2>&1 | tee ./logs/tellurium.log
```

I have build scripts for linux but not for mac.
https://github.com/matthiaskoenig/linux-setup
