### ISSUE TITLE
Update build instructions for linux

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#343]
Hi all,
I just tried to build on linux from latest source and run into some problems (will report this separately).
I looked if something changed in the build instructions on http://libroadrunner.org/build-roarunner-from-source/ and noticed that these are very outdated. In the following some issues

Typo:
http://libroadrunner.org/build-roarunner-from-source/
=> typo: /build-roadrunner-from-source

Old repository links
git clone https://github.com/AndySomogyi/roadrunner.git
=> https://github.com/sys-bio/roadrunner.git
https://github.com/AndySomogyi/roadrunner/releases
=> https://github.com/sys-bio/roadrunner/releases

Third part libraries wrong
git clone https://github.com/AndySomogyi/roadrunner_thirdparty
=> git clone https://github.com/sys-bio/libroadrunner-deps.git

and than there is no real information on the build process:
It should list something like
## How to build the third party libraries

```
echo "--------------------------------------"
echo "build roadrunner third party deps"
echo "--------------------------------------"
ROADRUNNER_BUILD_THIRDPARTY=$TMP_DIR/roadrunner_build_thirdparty
ROADRUNNER_BUILD=$TMP_DIR/roadrunner_build
ROADRUNNER_INSTALL=$TMP_DIR/roadrunner_install
sudo rm -rf $ROADRUNNER_INSTALL
mkdir $ROADRUNNER_INSTALL

rm -rf $ROADRUNNER_BUILD_THIRDPARTY
mkdir $ROADRUNNER_BUILD_THIRDPARTY
cd $ROADRUNNER_BUILD_THIRDPARTY
cmake -DCMAKE_INSTALL_PREFIX=$ROADRUNNER_INSTALL ${GIT_DIR}/$ROADRUNNER_DEPS && make -j4 install
```
## How to build roadrunner

```
echo "--------------------------------------"
echo "build roadrunner"
echo "--------------------------------------"
rm -rf $ROADRUNNER_BUILD
mkdir $ROADRUNNER_BUILD
cd $ROADRUNNER_BUILD
cmake -DCMAKE_INSTALL_PREFIX=$ROADRUNNER_INSTALL -DTHIRD_PARTY_INSTALL_FOLDER=$ROADRUNNER_INSTALL -DBUILD_LLVM=ON -DBUILD_PYTHON=ON -DUSE_TR1_CXX_NS=ON -DBUILD_TESTS=ON -DBUILD_TEST_TOOLS=ON -DLIBSBML_INCLUDE_DIR=$ROADRUNNER_INSTALL/include -DLIBSBML_LIBRARY=$ROADRUNNER_INSTALL/lib/libsbml.so -DLIBSBML_STATIC_LIBRARY=$ROADRUNNER_INSTALL/lib/libsbml-static.a ${GIT_DIR}/$ROADRUNNER

make
make install
```

Matthias

**Comment by 0u812** [comment]
I've started moving the build instructions over to the [Wiki](https://github.com/sys-bio/roadrunner/wiki/Building-from-Source). I don't have access to the WP site right now, so I can't change that page at the moment. When I get back I will change it to point to the new instructions.

**Comment by 0u812** [comment]
I think this is resolved.
