### ISSUE TITLE
RR Logging System: Use PyErr_WarnEx

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#345]
The idea of this proposed enhancement is to detect whether we are running as a Python extension module and, if so, issue logger warnings via the Python API function [PyErr_WarnEx](https://docs.python.org/2/c-api/exceptions.html#c.PyErr_WarnEx) instead of stderr.

**Comment by 0u812** [comment]
Not sure how to handle the lower-level log message like debug. In Python we have the [logging](https://docs.python.org/2/library/logging.html) module but I don't know if we can access it cleanly from C++.

**Comment by luciansmith** [comment]
The current system is newer than 2016, so I'm closing this.
