### ISSUE TITLE
"Bad Allocation" error in getFullStoichiometryMatrix for large models

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#346]
Download the recon1.xml model from: http://bigg.ucsd.edu:8888/models/RECON1

Recon1 has 2766 metabolites and 3742 reactions.

Run the scaript
r = roadrunner.RoadRunner ('recon1.xml')
stStr = r.getFullStoichiometryMatrix()

Error:
  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\roadrunner\roadrunner.py", line 2903, in getFullStoichiometryMatrix
    return _roadrunner.RoadRunner_getFullStoichiometryMatrix(self)

RuntimeError: bad allocation

The smaller model. iAF1260 works fine (1668 metabolites, and 2382 reactions)

Running:

Out[2]: '1.4.8; Compiler: Microsoft Visual Studio 2013, C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Aug 10 2016, 15:56:47; LibSBML Version: 5.13.0'

**Comment by 0u812** [comment]
I think this is basically Windows telling you that you have exhausted the available memory for the process. I presume you are using the 32-bit distribution of Tellurium. Like all 32-bit processes, Tellurium is limited to 4 GB of addressable memory. Every Python module that you import counts against this limit.

I just tried this on my 64-bit Windows Anaconda distribution of RoadRunner and it does not have any allocation errors.

**Comment by hsauro** [comment]
That's good to know and we can load it.

Herbert

**Comment by 0u812** [comment]
I think the resolution is to use a 64-bit build, so I am closing this.
