### ISSUE TITLE
Please tag latest release

### ISSUE THREAD

**Issue by tillea** [sys-bio/roadrunner#352]
Hi,
I intend to package libroadrunner for official Debian.  When checking how to download source code tarballs I noticed that on sourceforge the versioned releases are only binaries for either Windows or OS/X.  When comparing with the tags here on Github the lastest one available on Sourceforge (1.5.0) is missing.  It would be great if you could get this in sync.
Kind regards, Andreas.

**Comment by 0u812** [comment]
To save time, it might help to use the pre-existing Debian packaging scripts in the packaging/deb directory. As for versioning, the release cycle was interrupted before 1.5.0 could be officially released. I will probably release it in about a month or so when all the PyPI packages have been tested.

**Comment by tillea** [comment]
Hi Kyle,
On Tue, Jan 31, 2017 at 11:26:27AM -0800, Kyle Medley wrote:
> To save time, it might help to use the pre-existing Debian packaging scripts in the packaging/deb directory.
I noticed this but there are several things to adjust since this packaging does not build in an offline minimal chroot environment as per policy needs to be possible.  I'd appreciate if I could discuss some stumbling stones with you on Debian Med mailing list soon.

> As for versioning, the release cycle was interrupted before 1.5.0 could be officially released. I will probably release it in about a month or so when all the PyPI packages have been tested.
Ahh, thanks for the clarification.  In this case the issue can be closed.
Thanks for your quick response, Andreas.

-- 
http://fam-tille.de

**Comment by 0u812** [comment]
Happy to help 😃 
I subscribed to the Debian Med mailing list, and I will try to help with any questions you might have.
