### ISSUE TITLE
RuntimeError: Jacobian matrix singular in NLEQ

### ISSUE THREAD

**Issue by Niels86** [sys-bio/roadrunner#356]
Whenever I use any function that calculates the steady state  I get the error message

> RuntimeError: Jacobian matrix singular in NLEQ

It might be a problem with the solver since COPASI does find a Steady State using a combination of newtons method with forward integration. Any sugestions on what the problem is or how to use an alternative SS solvers. I have over 100 Steady State simulations I want to calculate and it was my impression roadrunner was exactly the software needed for these kind of jobs where Copasi and other software fail because of the lack of a good API to allow batch jobs? I am not sure these kind of problems are best discussed on github but I could not find for example a google group on Roadrunner to discuss these kind of issues, maybe a good addition?

**Comment by hsauro** [comment]
It would be a good time to start a google group, Kyle weren't you meant to
set one up?

As for the Jacobian, this has bothered be for ages. It does compute the
jacobian but if there are conserved cycles in the model then it will fail.
The way to get round this is to tell roadrunenr to take into acount any
conserved cycles by using the following statement after you load your model:

r.conservedMoietyAnalysis = True

I can't remember now why Andy (who wrote the ARM backend) insisted on doing
it this way, but its annoyed me ever since.

Herbert

**Comment by 0u812** [comment]
I think where we left it is that I can set one up as long as I don't have to moderate it (I'm currently spread pretty thin). Here is the group, anyone who wants to can join: https://groups.google.com/forum/#!forum/tellurium-discuss

**Comment by hsauro** [comment]
We should advertise it on the libroadrunner and tellurium pages.

H

**Comment by matthiaskoenig** [comment]
@Niels86 The error is most probably because you have dependencies in your Stoichiometric Matrix, i.e. your stoichiometric matrix has dependent rows

You should set the following before calculating steady states
```
r.conservedMoietyAnalysis = True
```
which will probably solve your issue.

This is related to #311, where the information about `r.conservedMoietyAnalysis` in steady state analysis should be updated.

**Comment by Niels86** [comment]
@matthiaskoenig Unfortunately not solved yet. When I print r.conservedMoietyAnalysis it is indeed set to False, when I tried to set it to True I get a RuntimeError. Any suggestion on what might be the cause?

`RuntimeError                              Traceback (most recent call last)
<ipython-input-18-228d7e501152> in <module>()
     38     print(solver.settingsPyDictRepr())
     39     print(rr.conservedMoietyAnalysis)
---> 40     rr.conservedMoietyAnalysis =True
     41 
     42     rr.model.setBoundarySpeciesConcentrations(newParameterList)

/home/niels/Applications/anaconda2/envs/default2.7/lib/python2.7/site-packages/roadrunner/roadrunner.pyc in <lambda>(self, name, value)
   2473     """
   2474     __swig_setmethods__ = {}
-> 2475     __setattr__ = lambda self, name, value: _swig_setattr(self, RoadRunner, name, value)
   2476     __swig_getmethods__ = {}
   2477     __getattr__ = lambda self, name: _swig_getattr(self, RoadRunner, name)

/home/niels/Applications/anaconda2/envs/default2.7/lib/python2.7/site-packages/roadrunner/roadrunner.pyc in _swig_setattr(self, class_type, name, value)
     61 
     62 def _swig_setattr(self, class_type, name, value):
---> 63     return _swig_setattr_nondynamic(self, class_type, name, value, 0)
     64 
     65 

/home/niels/Applications/anaconda2/envs/default2.7/lib/python2.7/site-packages/roadrunner/roadrunner.pyc in _swig_setattr_nondynamic(self, class_type, name, value, static)
     50     method = class_type.__swig_setmethods__.get(name, None)
     51     if method:
---> 52         return method(self, value)
     53     if (not static):
     54         if _newclass:

/home/niels/Applications/anaconda2/envs/default2.7/lib/python2.7/site-packages/roadrunner/roadrunner.pyc in _setConservedMoietyAnalysis(self, value)
   3013 
   3014     def _setConservedMoietyAnalysis(self, value):
-> 3015         return _roadrunner.RoadRunner__setConservedMoietyAnalysis(self, value)
   3016 
   3017     def _getConservedMoietyAnalysis(self):

RuntimeError: error converting document to conserved moieties, at rrllvm::ModelGeneratorContext::ModelGeneratorContext(const std::string&, unsigned int)`

**Comment by matthiaskoenig** [comment]
Hi @Niels86,
could you attach/send me the model so I can have a look if I can reproduce the issue and have a look at the SBML. Is difficult to answer without having the actual file.
M

**Comment by hsauro** [comment]
Just to check, I ran this model with out any issues:

import tellurium as te
import roadrunner

r = te.loada("""
    A -> B; k1*A;
    B -> A; k2*B;
    
    A = 10; B = 0
    k1 = 0.45;  k2 = 0.67
""")

r.conservedMoietyAnalysis = True
print r.steadyState()

I'm running:

[('tellurium', '1.3.4'),
 ('roadrunner',
  '1.4.8; Compiler: Microsoft Visual Studio 2013, C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Aug 10 2016, 15:56:47; LibSBML Version: 5.13.0'),
 ('antimony', 'v2.8.0'),
 ('snbw_viewer', 'No information for sbnw viewer'),
 ('libsbml', '5.12.0'),
 ('libsedml', '301'),
 ('phrasedml', 'v1.0.3')]

**Comment by Niels86** [comment]
Thx for trying, the issue must be with my model either because of an error in the code (, or a property in my model that gives the solver a hard time. The first option is unlikely as Copasi can find a SS solution, the second option is likely since Copasi used a number of methods combined to find the SS as can be seen from the log file

> Try Newton's method.
   Starting Newton Iterations...
    Newton step failed. Negative volume or concentration found.


>Try forward integration.
  Integration with duration 0.1. Criterium not matched by 0.826126.

  >Try Newton's method from this starting point.
   Starting Newton Iterations...
    Regular Newton step.      New value: 0.274659
    Regular Newton step.      New value: 0.0490599
    Regular Newton step.      New value: 0.00269574
    Regular Newton step.      New value: 0.000386107
    Regular Newton step.      New value: 9.8015e-006
    Regular Newton step.      New value: 2.56767e-010
   Success: Target criterium matched by 2.56767e-010.
   Do additional step to refine result...
    Regular Newton step.      New value: 1.59387e-015

**Comment by matthiaskoenig** [comment]
@Niels86 
I had a look at your model and everything looks fine. Is valid SBML and runs to identical steady state (via time course integration) in COPASI and roadrunner.

![niels_ss_copasi](https://cloud.githubusercontent.com/assets/900538/22646788/6f7d3162-ec6e-11e6-9ad5-9d8944cd6b28.png)
![niels_ss_roadrunner](https://cloud.githubusercontent.com/assets/900538/22646789/6f7e318e-ec6e-11e6-89ee-2de0a52f0345.png)

In addition I can calculate a steady state with COPASI
```
A steady state with given resolution was found.

Species	Concentration (mol/l)	Concentration Rate (mol/(l*s))	Particle Number	Particle Number Rate (1/s)	Transition Time (s)
AcCoA	0.0149912	-5.57184e-17	9.0279e+21	-3.35544e+07	0.0360508
ACE	0.87378	0	5.26203e+23	0	nan
ADP	0.578337	-1.5824e-14	3.48282e+23	-9.52946e+09	0.464647
ATP	0.000799503	1.5824e-14	4.81472e+20	9.52946e+09	0.000642337
CoA	0.00423892	0	2.55274e+21	0	nan
DGP	1.65154e-05	-1.37067e-14	9.94581e+18	-8.25439e+09	2.98888e-05
F6P	0.0209584	8.04909e-13	1.26215e+22	4.84727e+11	0.0758591
FBP	0.0591568	-1.11437e-16	3.56251e+22	-6.71089e+07	0.214118
G6P	0.0487432	-8.04797e-13	2.93538e+22	-4.8466e+11	0.176426
GAP	0.0134673	0	8.11022e+21	0	0.0243725
LAC	3.8294	0	2.30612e+24	0	nan
NAD	0.12081	0	7.27535e+22	0	nan
NADH	0.068224	0	4.10855e+22	0	nan
PEP	0.322106	1.37067e-14	1.93977e+23	8.25439e+09	0.582932
Pi_Int	6.9463	0	4.18316e+24	0	nan
PYR	1.921	-5.57184e-17	1.15686e+24	-3.35544e+07	3.47654
GLC_Ext	59.603	0	3.58938e+25	0	nan
```

There seems to be an issue with the roadrunner calculation for conserved moieties . I can reproduce the error you got with the model. As a consequence of the failed reduction of conserved moieties no steady state can be calculated. 
Your model ATP and ADP are dependent, also your NAD and NADH, so you need the reduction.
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-9ad9e9d7217c> in <module>()
      4 s = r.simulate(0, 100, steps=1000)
      5 r.plot()
----> 6 r.conservedMoietyAnalysis = True
      7 print r.steadyState()

/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.14-py2.7.egg/roadrunner/roadrunner.pyc in <lambda>(self, name, value)
   2552 
   2553     __swig_setmethods__ = {}
-> 2554     __setattr__ = lambda self, name, value: _swig_setattr(self, RoadRunner, name, value)
   2555     __swig_getmethods__ = {}
   2556     __getattr__ = lambda self, name: _swig_getattr(self, RoadRunner, name)

/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.14-py2.7.egg/roadrunner/roadrunner.pyc in _swig_setattr(self, class_type, name, value)
     59 
     60 def _swig_setattr(self, class_type, name, value):
---> 61     return _swig_setattr_nondynamic(self, class_type, name, value, 0)
     62 
     63 

/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.14-py2.7.egg/roadrunner/roadrunner.pyc in _swig_setattr_nondynamic(self, class_type, name, value, static)
     48     method = class_type.__swig_setmethods__.get(name, None)
     49     if method:
---> 50         return method(self, value)
     51     if (not static):
     52         if _newclass:

/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.14-py2.7.egg/roadrunner/roadrunner.pyc in _setConservedMoietyAnalysis(self, value)
   3126 
   3127     def _setConservedMoietyAnalysis(self, value):
-> 3128         return _roadrunner.RoadRunner__setConservedMoietyAnalysis(self, value)
   3129 
   3130     def _getConservedMoietyAnalysis(self):

RuntimeError: error converting document to conserved moieties, at rrllvm::ModelGeneratorContext::ModelGeneratorContext(const string&, unsigned int)
```

Can I forward the model to Kyle & Herbert, so they can have a look?
The best 
Matthias

**Comment by Niels86** [comment]
Hi Matthias, thanks for the quick and systematic checking of the model. No problem, you can share the model with Kyle & Herbert as longs as they will not share it with any third party. For the mean time I plan to circumvent the SS solver issue by running time series simulations with increasing time step to approximate the SS. Since I plan to simulate only 100-150 parameter set/mutants-perturbation for the time being, this is feasible. However, I hope a solution can be found in the long run since it would be nice to also run combinations of these parameter sets to simulate combinatorial mutants and perturbations which would result in too long simulation time.

**Comment by matthiaskoenig** [comment]
You could also try as a workaround to remove the dependencies. I.e. you include constant parameters in your NADH_tot and ATP_tot and create two assignment rules to parameters
ADP = ATP_tot - ATP
NAD = NADH_tot - NADH
and remove the respective species ADP and NAD. 

Than all your rows for the steady state calculation should be indepenent and you don't need the reduction of the system.
Than you should be able to run the steady state calculation directly.

**Comment by hsauro** [comment]
I can confirm as well that there is a problem with computing the moieties. I checked with jarnac and COPASI and they give the same answer but Roadrunner is doing something else, if could be a misordering of the labels on the Jacobian. I'll ask Kyle to investigate.

**Comment by hsauro** [comment]
I tried the model and I am not seeing the problem, I ran this script, computes the ss ok. 

What script do you use?

 I am running: 

'1.4.8; Compiler: Microsoft Visual Studio 2013, C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Aug 10 2016, 15:56:47; LibSBML Version: 5.13.0'

**Comment by matthiaskoenig** [comment]
I am running minimal example. Just loading the model and trying to set the property results in the error
```
import tellurium as te
r = te.loads('model_niels.xml')
r.conservedMoietyAnalysis = True
```

'1.4.8; Compiler: gcc 4.8.4, C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Oct 22 2016, 13:54:08; LibSBML Version: 5.13.0'

I build from a recent commit on Ubuntu Linux on Kernel 3.13.0-101-generic
Here the commit hash I used to build
610b3e7019decbd421a1cb90190f79ba4c0fbbed

**Comment by hsauro** [comment]
ok now I am seeing the error. Kyle, I think you'll have to debug this.

**Comment by matthiaskoenig** [comment]
@Niels86 This should work now. Kyle fixed the issue. 
Could you try with the latest version of roadrunner if this is resolved for you.

**Comment by matthiaskoenig** [comment]
Just to give the full solution:
```
import tellurium as te
r = te.loads('niels_model.xml')

# steady state analysis
import pandas as pd
r.conservedMoietyAnalysis = True
r.steadyState()
ss = r.getSteadyStateValues()
df_ss = pd.DataFrame(ss, columns=['steady_state'], index=r.steadyStateSelections)
df_ss.sort_index(inplace=True)

df_ss
```
results in
```
 	steady_state
[ADP] 	0.578337
[ATP] 	0.000800
[AcCoA] 	0.014991
[DGP] 	0.000017
[F6P] 	0.020958
[FBP] 	0.059157
[G6P] 	0.048743
[GAP] 	0.013467
[PEP] 	0.322106
[PYR] 	1.921003
```
Compared to Copasi
```
AcCoA	0.0149912	
ACE	0.87378	
ADP	0.578337	
ATP	0.000799503	
CoA	0.00423892	
DGP	1.65154e-05	
F6P	0.0209584	
FBP	0.0591568	
G6P	0.0487432	
GAP	0.0134673	
LAC	3.8294	
NAD	0.12081	
NADH	0.068224	
PEP	0.322106	
Pi_Int	6.9463	
PYR	1.921	
GLC_Ext	59.603	
```
Which are identical (values in pandas DataFrame are displayed rounded). By default roadrunner only has the independent state variables in the initial selections (that is why there are less entries in roadrunner than in the COPASI output).
If you want additional parameters/variables/compartments in the steady state solution you have to add the respective ids to 
```
r.steadyStateSelections
```
before you run the steady state calculation (only the minimal set of variables is in the r.steadyStateSelections by default.

**Comment by Niels86** [comment]
Great, works like a charm now! Thx for resolving it so quickly

**Comment by Niels86** [comment]
I made a stupid error, I run the old version of the script that used my own approximate SS solver, not the one where I entered the new code. I updated all packages via Conda but I get the same error from conservedMoietyAnalysis(), libroadrunner is not updated. Any advise on how to update the package in Conda? Sorry if it is stupid question but I have little experience with github and Conda and assumed updating all packages would pull me the latest release.

**Comment by Niels86** [comment]
I tried cloning the ss-solver-refactor branch but could not find any installer. Making my own build using the [build instruction](https://github.com/sys-bio/roadrunner/issues/343) is unfortunately beyond me. Matthias, do you have a pre-compiled version or installer I can use?

**Comment by hsauro** [comment]
Sorry I have zero expereince with conda. Kyle has developed the conda
installs, he should have instructions on line on how to do this.

Kyle, where are the instructions to install Conda packages for
libroadrunner!

Herbert

**Comment by 0u812** [comment]
The conda instructions are at http://libroadrunner.org/install/, but conda is no longer necessary. You can actually just run "pip install libroadrunner" without the quotes if you are on Python 2.7 64 bit.

**Comment by 0u812** [comment]
@Niels86 I updated the version for pip on Linux to 1.4.15 so you can install it as follows:
```
pip install libroadrunner
```
If you are using an OS other than 64-bit Linux please let me know.

**Comment by Niels86** [comment]
Thx, I installed the updated version successfully using pip. 
One other question, How to change parameters form the loaded SBML model? I expected them to be accessible like r.parametername (like in the tellurium examples, r.model.k1), or via some setParameter function, however this appears not to be the case.

**Comment by hsauro** [comment]
That's odd, r.X should work.

What happens when you try to print or assign a parameter using r.parameter?

Herbert

**Comment by 0u812** [comment]
@Niels86 can you post an example?

**Comment by Niels86** [comment]
II get an Attribute Error. Kinetic parameters are not there when I get all options using tab or when I retrieve them using r.model.items() or r.model.keys(). Species and initial species concentrations and compartments are shown but not kinetic parameters from equations. Maybe I can access them using the roadrunner.RoadRunner_getParamPromotedSBML(*args) function to get them as Global parameters?, not sure yet how this function works.

Example, accessing the PYK parameter from the equation for re07 as
print(rr.model.PYK) will give me an AttributeError

**Comment by 0u812** [comment]
Here is an example of how to get/set model parameters. If this doesn't work for you, could you please post a code example?

```python
from roadrunner import RoadRunner

r = RoadRunner('sbml.xml')
print('r.k before = {}'.format(r.k))
r.k = 2
print('r.k after = {}'.format(r.k))
```

**sbml.xml**:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created by libAntimony version v2.9.1 with libSBML version 5.14.1. -->
<sbml xmlns="http://www.sbml.org/sbml/level3/version2/core" level="3" version="2">
  <model id="__main" name="__main">
    <listOfCompartments>
      <compartment sboTerm="SBO:0000410" id="default_compartment" spatialDimensions="3" size="1" constant="true"/>
    </listOfCompartments>
    <listOfSpecies>
      <species id="A" compartment="default_compartment" initialConcentration="10" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
      <species id="B" compartment="default_compartment" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
    </listOfSpecies>
    <listOfParameters>
      <parameter id="k" value="1" constant="true"/>
    </listOfParameters>
    <listOfReactions>
      <reaction id="J0" reversible="true">
        <listOfReactants>
          <speciesReference species="A" stoichiometry="1" constant="true"/>
        </listOfReactants>
        <listOfProducts>
          <speciesReference species="B" stoichiometry="1" constant="true"/>
        </listOfProducts>
        <kineticLaw>
          <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply>
              <times/>
              <ci> k </ci>
              <ci> A </ci>
            </apply>
          </math>
        </kineticLaw>
      </reaction>
    </listOfReactions>
  </model>
</sbml>
```

**Comment by Niels86** [comment]
This example works perfectly fine for me. When I apply it to my own model however, I get a attribute error. It is the same model I send earlier that gave problems with the SS solver. Can you test if you can change kinetic parameters of that model?

To give the example of the code:

`from roadrunner import RoadRunner

r = RoadRunner(''model_niels.xml'')
print('r.PYK before = {}'.format(r.PYK))
r.k = 2
print('r.k after = {}'.format(r.PYK))`

PYK is a kinetic parameter for re07 in the model representing the enzyme concentration of Pyruvate Kinase.

**Comment by Niels86** [comment]
Was anyone able to reproduce the error using the previously shared model (model_niels.xml)?

**Comment by matthiaskoenig** [comment]
Hi Niels,
the problem is that all your parameters are local parameters to the reaction.
The parameters have to be promoted to global parameters first (see below). Only after promotion you have global parameters which you can set.

```
from __future__ import print_function

# loading model
# the problem is that all parameters are local parameters on the reactions (COPASI did this)
# you have to promote the localparameters
import tellurium as te
r = te.loads('niels_model.xml')
print('Before promotion:', r.getGlobalParameterIds(), '\n')

# get the parameter promotes SBML (local -> global)
sbml_str = r.getSBML()
sbmlp_str = r.getParamPromotedSBML(sbml_str)
r2 = te.loads(sbmlp_str)
print('After promotion:', r2.getGlobalParameterIds())
```

```
Before promotion: [] 

After promotion: ['re01_vmax_PTS_Glc', 're01_kmPYR_PTS_Glc', 're01_kmPEP_PTS_Glc', 're01_kmGLC_PTS_Glc', 're01_kmG6P_PTS_Glc', 're01_kiFBP_PTS_Glc', 're01_kaPi_Int_PTS_Glc', 're01_PTS_Glc', 're02_vmax_PGI', 're02_kmG6P_PGI', 're02_kmF6P_PGI', 're02_PGI', 're02_Keq_PGI', 're03_vmax_PFK', 're03_kmFBP_PFK', 're03_kmF6P_PFK', 're03_kmATP_PFK', 're03_kmADP_PFK', 're03_PFK', 're04_vmax_FBA', 're04_kmGAP_FBA', 're04_kmFBP_FBA', 're04_Keq_FBA', 're04_FBA', 're05_vmax_GAPDH', 're05_kmPi_Int_GAPDH', 're05_kmNAD_GAPDH', 're05_kmNADH_GAPDH', 're05_kmGAP_GAPDH', 're05_kmDGP_GAPDH', 're05_Keq_GAPDH', 're05_GAPDH', 're06_vmax_ENO', 're06_kmPEP_ENO', 're06_kmDGP_ENO', 're06_kmATP_ENO', 're06_kmADP_ENO', 're06_Keq_ENO', 're06_ENO', 're07_vmax_PYK', 're07_nPYK', 're07_kmPYR_PYK', 're07_kmPEP_PYK', 're07_kmATP_PYK', 're07_kmADP_PYK', 're07_kiPi_Int_PYK', 're07_kaFBP_PYK', 're07_PYK', 're08_vmax_LDH', 're08_kmPYR_LDH', 're08_kmNAD_LDH', 're08_kmNADH_LDH', 're08_kmLAC_LDH', 're08_kiPi_Int_LDH', 're08_kaFBP_LDH', 're08_LDH', 're09_vmax_PDH', 're09_kmPYR_PDH', 're09_kmNAD_PDH', 're09_kmNADH_PDH', 're09_kmCoA_PDH', 're09_kmAcCoA_PDH', 're09_kiGAP_PDH', 're09_PDH', 're09_Keq_PDH', 're10_vmax_PTA_ACK', 're10_kmCoA_PTA_ACK', 're10_kmAcCoA_PTA_ACK', 're10_kmATP_PTA_ACK', 're10_kmADP_PTA_ACK', 're10_kmACE_PTA_ACK', 're10_PTA_ACK', 're11_vmax_ATPase', 're11_nATPase', 're11_kmATP_ATPase', 're11_ATPase']

```

Now you can set the global parameter ids, but be aware that the naming changed! All global parameters have the reaction prefix.

The best
Matthias

@all this should be documented somewhere

**Comment by Niels86** [comment]
Thx, I tried this function  but used the file name instead of first using the getSBML, my mistake.
I also tried to save the file as level 2 SBML since in this version they don’t use local parameters, I am not sure why it did not work with that version of the model. 
Anyhow, thx again for all the help, it is very much appreciated!
