### ISSUE TITLE
Module __version__ attribute should just return version string

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#358]
Currently it returns a lot of other stuff that it shouldn't: `1.4.12; Compiler: gcc 4.8.2, C++ version: 199711; JIT Compiler: LLVM-3.3; Date: Nov 17 2016, 19:59:42; LibSBML Version: 5.13.0`

**Comment by 0u812** [comment]
This is for consistency with other Python packages.

**Comment by hsauro** [comment]
Except it's useful.

Herbert

**Comment by 0u812** [comment]
We have a module-level function `roadrunner.getVersionStr()` which returns the extra info above. I suggest we set `roadrunner.__version__ = roadrunner.getVersionStr(roadrunner.VERSIONSTR_BASIC) # returns '1.4.15'`

**Comment by 0u812** [comment]
Typo in last comment, should have been: `roadrunner.__version__ = roadrunner.getVersionStr(roadrunner.VERSIONSTR_BASIC) # returns '1.4.15'`

**Comment by hsauro** [comment]
I assume we still have a super version reporter at the tellurium level?
It's handy being able to see everything at once rather than going through
each library one at a time.

Herbert
