### ISSUE TITLE
Roadrunner Tester error

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#359]
Windows 32 bit binary for Roadrunner provided in release causes:

RuntimeError: error converting document to conserved moieties, at ??0ModelGeneratorContext@rrllvm@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z

When running Roadrunner testing function. This is caused by oscli.rrtest test.
Viewing the commit log, it seems like this might been fixed already. If so, will there be an updated binaries for Windows?

**Comment by 0u812** [comment]
I'll try to send it to you today or tomorrow

**Comment by 0u812** [comment]
Binary is [here](https://github.com/sys-bio/roadrunner/releases/download/1.4.16/roadrunner-1.4.16-vs12-llvm-3.5-win32.zip). It includes the fix for #360.
