### ISSUE TITLE
Roadrunner printing debug lines

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#361]
Roadrunner is printing messages that seems to be for debugging purposes.
```
CVODEIntegrator::resetSettings
resetSettings rel tol pre load config 1e-006
resetSettings rel tol 1e-006
```
These lines are from CVODEIntegrator::resetSettings() (https://github.com/sys-bio/roadrunner/blob/develop/source/CVODEIntegrator.cpp) ln 98, 112, and 115.
Are these necessary?

**Comment by 0u812** [comment]
Sorry, should be fixed now. Same download link.

**Comment by kirichoi** [comment]
Confirmed Fixed
