### ISSUE TITLE
Undesired behaviour when accessing model parameters

### ISSUE THREAD

**Issue by Niels86** [sys-bio/roadrunner#364]
Dear all,

I run in unwanted behaviour and errors when accessing model parameters.
Accessing model parameters directly  using the parameter name works. However, passing the name via variable as a string does not work and results in AttributeError. It get even stranger when I try to circumvent this behaviour by generating code string directly  and using the eval() function, not something I like to do but I need to get this issue quickly. Using eval() I can print the value of a parameter but I cannot change it. This is a problem for me since there is no automatic way to update parameters. Any suggestions on how to solve or circumvent this problem, I need to generate those results ASAP.
See the code below that will reproduce this error:

> ##Example of failed access to parameters
import tellurium as te
import roadrunner

r = te.loada("""
J1: A -> B; k1*A;
J2: B -> A; k2*B;
    
    A = 10; B = 0
    k1 = 1000.45;
    k2 = 0.67
""")

r.conservedMoietyAnalysis = True

#Accessing parameter in a way that works
print(r.k1)
variable = 'k1'
print(eval('r.'+str(variable)))
oldValue = r.k1
newValue = 2*oldValue
print('oldValue:{}'.format(oldValue),'newValue:{}'.format(newValue)) 
print(eval('r.'+str(variable)+' = '+str(newValue)))  # <-will give an error
print(r.variable) # <-will give an error

**Comment by matthiaskoenig** [comment]
Hi Niels,
it's a dictionary.
```
r[variable]
```
should work.

**Comment by Niels86** [comment]
Ok, great. that solves it!
