### ISSUE TITLE
RuntimeError: Damping factor has became to small to continue

### ISSUE THREAD

**Issue by Niels86** [sys-bio/roadrunner#365]
I got the following error when determining the SS for a number of mutants, any explanation what this error implies e.g. unstable behaviour around the SS or something:
 

> "RuntimeError: Damping factor has became to small to continue"?. 

COPASI and my own approximate SS solver (basically a long time-series simulation), do find a SS using the same compound concentrations and parameters. 
For this issue it is a bit harder to include a code example since it requires the model as well as the concentrations measured in a number of mutants.
As shown in the image for a long time series simulations, the model does reach a SS even though the solver gives an error:
![ss](https://cloud.githubusercontent.com/assets/2855112/23465762/8bbe251a-fe99-11e6-83b7-384c2d022382.png)

**Comment by matthiaskoenig** [comment]
Try to create a minimal example (model & code) which reproduces the problem. Otherwise it is impossible to debug this.

You can also set parameters on the steady state solver. I think you can set the damping factor there which could solve your problem.

**Comment by hsauro** [comment]
It means that is can't find the steady state.

Do you have exactly the same initial conditions you used with copasi?

One possibility is that copasi is dong an initial internal run for longer
than we do.

Kyle: I can't remember now but do we have a parameter that sets how much
time the presimulation lasts?

I assume there are no consevered moieties in the model?

Try different initial conditions.

If I remember right the algorithm that libroadrunner uses is a library
called nleq2 which historically has been a good library to use.

Herbert

**Comment by hsauro** [comment]
PS trying doing your own presimulation before handing over to the steady
state solver e.g.

r.simulate (0, 50, 20)
r.steadyState()

Herbert

**Comment by matthiaskoenig** [comment]
@hsauro 
I think it is nleq1 (somehow nleq2 is the older version ?)
see https://github.com/sys-bio/roadrunner/issues/311

The name of the solver must still be fixed, not clear which version used from the solver info.
```
import roadrunner
r = roadrunner.RoadRunner('niels_model.xml')
solver = r.getSteadyStateSolver()
print(solver.getName())
print(solver.settingsPyDictRepr())
```
```
nleq
'maximum_iterations': 100, 'minimum_damping': 1e-16, 'relative_tolerance': 0.0001
```

Like I mentioned, you can set the minimum_damping on the solver. If you make it smaller it should probably work.

**Comment by hsauro** [comment]
We should add the ability to set the presimulation time. If 0 no
presimulation is done.

I'll add to issues.

Herbert

**Comment by Niels86** [comment]
Thx, I will look into these options and let you know how it works out.

**Comment by Niels86** [comment]
Setting, the dampening factor to 1e-99 or 1e-9 did not work. I tried running first a simulation, r.simulate(0, 10000, 100) which also did not help. 
I will try to give the full example with model and parameter values later, luckily I can get around the problem by doing a long time series simulations and taking the value as SS.

**Comment by hsauro** [comment]
The only other thing I can think of is that the model has conserved
moieties but this would usually result in a jacobian singarity error.

Herbert

**Comment by Niels86** [comment]
The problem has resolved itself. The problem must have been a problem in the data or the way my script handled the data to be loaded in the model. It must have been a space in a parameter or a variable being of the wrong type, something I did not see when printing the values for debugging. 
After being more thorough in checking  and converting all data before loading it in the model the SS solver works as it should! 
Which means I could finally run my SS 110 mutant perturbation simulations, which took only a few milliseconds to run. Soon I can run all combinatorial simulations, something like 1000-10.000 simulations which will take approximately a minute to run :)

**Comment by hsauro** [comment]
Good to hear, I've had instances like that.

Herbert
