### ISSUE TITLE
Pip packages for Windows and Mac missing

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#370]
Hi all,
I am developing some python package which has a libroadrunner dependency.
https://github.com/matthiaskoenig/sbmlutils

Now Leandro reported that he can't install it on Win/Mac because the latest libroadrunner is not available for win/mac from pip.
https://pypi.python.org/pypi/libroadrunner#downloads

The installation of my package is done via
```
mkvirtualenv sbmlutils
pip install sbmlutils
```
But on windows and mac this results in 
```
Could not find a version that satisfies the requirement libroadrunner>=1.4.15 (from sbmlutils==0.1.5a1) (from versions: 1.4.11, 1.4.12)
No matching distribution found for libroadrunner>=1.4.15 (from sbmlutils==0.1.5a1)
```
Can you upload the latest win/mac builds to pip so I can support win/mac.

The best 
Matthias

**Comment by matthiaskoenig** [comment]
Hi Kyle,
any update on this issue? 

The mac and win packages for libroadrunner exist in the tellurium wheelhouse
https://github.com/sys-bio/wheelhouse
and should be uploaded on pypi.

Unfortunately, I cannot use the github wheelhouse for mac/win in my requirements.txt, because it is not an pypi index.
Could you upload the win/mac packages to pypi?

Matthias

**Comment by 0u812** [comment]
Sorry for the delay. Packages have been uploaded for Windows, Mac, and Linux 64-bit, roadrunner version 1.4.18.

**Comment by matthiaskoenig** [comment]
Hi Kyle,
thanks a lot.
I will close this as soon as I have the feedback from Leandro that things work for him on mac.
M

**Comment by matthiaskoenig** [comment]
works on mac
