### ISSUE TITLE
r.reset() does not reset the conserved totals

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#373]
reset() does not the conserved totals but it should.

Applies to 1.4.16 or roadrunner

Why is it bad? Because if getCC fails when computing coefficient with respect to conserved moiety, its is not possible to get back to the correct initial conditions using reset(). Of course one can reload the model but this means the conserved total identifier changes name and if the users used the original name they will have update the name to the new one.

reset() reinitializes the floating species back to their initial conditions, however if there are conserved cycles it should also reset the totals.

```python
import tellurium as te
import roadrunner
r = te.loada("""
     S1 -> S2; k1*S1;
     S2 -> S1; k2*S2;
     
     k1 = 0.5; k2 = 0.56;
     S1 = 10; S2 = 0;
""")

r.conservedMoietyAnalysis = True
r.steadyState()

#Get name of conserved total
pc = r.getGlobalParameterIds()[2]
r.setValue (pc, 60) # Change to 60
print r.S1, r.S2 # Show change
r.reset()
print r.S1, r.S2 # Show reseted floats
print r.getValue (pc)  # Should equal 10 but it stays at 30.
```

**Comment by kirichoi** [comment]
There's function such as resetAll() or resetToOrigin() for this purpose.

**Comment by kirichoi** [comment]
Or if you are talking about r.reset() not resetting S2 back to initial state due to conserved cycle that is potentially a valid issue.

**Comment by hsauro** [comment]
resetAll() will reset all parameters. reset() should leave the model in a
consistent state, if it doens't update the totals as well then the model is
invalid.

Herbert

**Comment by bouteill** [comment]
In LRR 1.4.18, using resetAll() or resetToOrigin() throws errors for me.

**Comment by kirichoi** [comment]
@bouteill: Hi, could you post the errors and the OS you are on?

**Comment by bouteill** [comment]
Win 10 - 64bits
Here is the error (same error returned when using resetAll() and resetToOrigin() ):
Traceback (most recent call last):
  File "E:/JM_DOCS/DROPBOX/Dropbox/Dropbox/2017-08-August/SHANE/PMCA-2006-Goldstein/test01_simulate_CaM_Effects.py", line 120, in <module>
    r.resetToOrigin()
  File "C:\Users\jmbouteiller\AppData\Local\conda\conda\envs\envt_for_LRR\lib\site-packages\roadrunner\roadrunner.py", line 2477, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, RoadRunner, name)
  File "C:\Users\jmbouteiller\AppData\Local\conda\conda\envs\envt_for_LRR\lib\site-packages\roadrunner\roadrunner.py", line 78, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "C:\Users\jmbouteiller\AppData\Local\conda\conda\envs\envt_for_LRR\lib\site-packages\roadrunner\roadrunner.py", line 73, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
Process finished with exit code 1

**Comment by kirichoi** [comment]
@bouteill I am moving the issue to https://github.com/sys-bio/roadrunner/issues/406 since it is not related to the original post.

**Comment by 0u812** [comment]
Hi Jean-Marie, I'm not sure if you're getting updates from the thread that Kiri moved your issue to, so I just wanted you to know I posted a workaround in the new thread here: https://github.com/sys-bio/roadrunner/issues/406

**Comment by bouteill** [comment]
Hi Kyle - was just out of touch for a couple of days - just caught up with the threads!

**Comment by kirichoi** [comment]
For the original issue, would resetting DEPENDENT_INITIAL_GLOBAL_PARAMETER work as a solution? Would that cause some other issues?

**Comment by kirichoi** [comment]
Fixed by PR https://github.com/sys-bio/roadrunner/pull/413
