### ISSUE TITLE
Problem with setting conserved total if below current total

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#374]
Run the model below.  This is a simpel conserved cycle S1 + S2. We print the values of S1 and S2 first which will be 5.0 and 5.0

We now set the cosnerved total to 4

When we print out the S1 and S2 immediately afterwards we get

5.0 and -1.0

What should have happened was either an error message or S1 was adjust so that S2 didn't go negative. Jarnac handles it ok so we are doing something wrong.

Total = Independent + Dependent
 10    = 5 + 5

If Total is changed to 4 this computation appears to be made resulting in -1 for the dependent.

Dependent = Total - Independent
-1 = 4 - 5

I think it should be: Dependent = 0 and Independent = 4

Need to somehow modify the way we update species when the total is changed.  Perhaps if Total is less than Independent, then set Dependent = 0 and compute New Independent = Total?

This is the reason why Neils was getting runtime errors, once the species went negative the numerics failed. 
```
import tellurium as te
import roadrunner

r = te.loada("""
     S1 -> S2; k1*S1;
     S2 -> S1; k2*S2;
     
     k1 = 0.5; k2 = 0.5;
     S1 = 10; S2 = 0;
""")

r.conservedMoietyAnalysis = True

r.steadyState()

# Get name of conserved total
pc = r.getGlobalParameterIds()[2]

print r.getValue (pc)
print 'Before = ', r.S1, r.S2
r.setValue (pc, 4)
print 'After = ', r.S1, r.S2
```

**Comment by 0u812** [comment]
Since a single dependent species can depend on multiple independent species, would it work to set all independent species (associated with that particular conserved moiety) to zero instead?

**Comment by hsauro** [comment]
Probably, but only if setting a species would cause negative
concentrations. If no negative concentrations occur then jsut do when we
currently do.

Herbert

**Comment by 0u812** [comment]
With the changes I just made, it now prints
```
('Before = ', 5.0, 5.0)
('After = ', 0.0, 4.0)
```
for the output, i.e. the independent species is zeroed out like we discussed above.
