### ISSUE TITLE
roadrunner Java bindings

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#377]
Hi all,

what is the status of the roadrunner java bindings at
https://github.com/sys-bio/roadrunner/tree/develop/wrappers/Java

I need to include libroadrunner in a java program. What is the easiest way to achieve this?
How can I build roadrunner with the java bindings?

Matthias

**Comment by 0u812** [comment]
Hi Matthias,
I haven't touched the Java bindings in several years (and they were never widely deployed in the first place), so they probably have a few bugs, but if you are planning on using them I can go through them and make sure everything is working. There are a couple of things to note:

* Matrices are handled using the [la4j](http://la4j.org/) library
* Named matrices are currently not supported (they relied on a special subclass that was implemented for numpy specifically)
* The CMake build system automatically creates a .jar which can be imported in a Java project, but the .jar contains arhitecture-specific binaries. Producing a portable .jar currently has to be done manually by combining the binaries produced on all three major platforms. I could write a script for this if you would be interested in deploying your project.

Please let me know if any of the above features are important to you, e.g. named matrices support or portability. If you plan on deploying your project, I could take care of making a .jar that can be run across all three major platforms, but if you don't think you will be deploying then it may not be necessary.

**Comment by 0u812** [comment]
Btw just to clarify, by "named matrices" I meant matrices with column names

**Comment by hsauro** [comment]
Are there matrices that still don't have named rows and columns? Fore
eample getConservationMatrix() doesn't have any column labels. eg:

r.getConservationMatrix()
Out[74]:  [[ 1, 1]]

but it should as it would be particularly useful in this case. This is in
version 1.4.16

Herbert

**Comment by matthiaskoenig** [comment]
Hi Kyle,
Named matrices are not important for now. What I am looking for is mainly the java bindings for linux 64 bit , but windows would also be nice.
It would be great if there could be an easy way to get them for instance similar to 
http://copasi.org/Download/
where the java bindings for the different OS are listed.

My problem right now is that I don't even know where to start to build the java bindings. Which cmake flags? How can I build for different distributions?
I only have to perform very simple time course simulation and steady state simulation, nothing very fancy. 
M

**Comment by 0u812** [comment]
Hi Matthas, adding the `-DBUILD_JAVA_INTERFACE=ON` option to your CMake config will build the Java bindings and create a jar file `<install-prefix>/java/roadrunner_jar.jar` with the roadrunner classes (e.g. `roadrunner/RoadRunner.class` is the main RoadRunner class, and you can import this from Java). However, I wrote this before I was familiar with the Java reverse-domain-name convention for packages. The classes should probably be under `org.libroadrunner` (they're currently just under `roadrunner`). Let me fix that and send you a minimal example.
