### ISSUE TITLE
Elasticities not computed correctly when conserved moieties is enabled

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#385]
When conserved moieties is enabled, dependent species are encoded as assignment rules. This causes problems for computing the elasticities because it causes them to be updated whenever the independent species are updated.

**Comment by 0u812** [comment]
There may be a slight performance penalty for my fix because it checks whether the dependent species have been updated.

**Comment by hsauro** [comment]
It's more important that it works.

Herbert
