### ISSUE TITLE
Gillespie method has bug in number of arguments

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#388]
This script gives the following error:

TypeError: unsupported operand type(s) for -: 'list' and 'int'

Looks like its expecting the number of points (on a grid I presume), but I don't want points on a grid. Is this a bug? Docs say I can use this syntax.

import tellurium as te

r = te.loada ('''
    $Xo -> S1; k1 * Xo;
    S1 -> S2; k2*S1;
    S2 -> $X1; k3*S2;

    Xo = 50; S1 = 0; S2 = 0;
    k1 = 0.2; k2 = 0.4; k3 = 2;
''')
m = r.gillespie (0, 30, ["time", "S1", "S2"])

**Comment by kirichoi** [comment]
I don't think this is a bug. The function will accept four positional arguments when presented in order. If you want to skip number of points, I believe you will have to specify selections by explicitly stating it, e.g. `selections=["time", "S1", "S2"]`. There might be a documentation error though.

**Comment by hsauro** [comment]
I tried adding selection= but it didn't recognized that.

I discovered that r.gillespie (0, 30) is ok.

What ever is broken should be fixed for the plos comp bio subission next
week

**Comment by kirichoi** [comment]
`selections` with s does work for my machine.

**Comment by hsauro** [comment]
Can you post the code so I can try.

H

**Comment by kirichoi** [comment]
This works on my machine.

```
import tellurium as te

r = te.loada ('''
    $Xo -> S1; k1 * Xo;
    S1 -> S2; k2*S1;
    S2 -> $X1; k3*S2;

    Xo = 50; S1 = 0; S2 = 0;
    k1 = 0.2; k2 = 0.4; k3 = 2;
''')
m = r.gillespie (0, 30, selections=["time", "S1", "S2"])
```

**Comment by hsauro** [comment]
What happens if you add number of points?

H

**Comment by kirichoi** [comment]
If you specify number of points, you can do something like this as well.

```
import tellurium as te

r = te.loada ('''
    $Xo -> S1; k1 * Xo;
    S1 -> S2; k2*S1;
    S2 -> $X1; k3*S2;

    Xo = 50; S1 = 0; S2 = 0;
    k1 = 0.2; k2 = 0.4; k3 = 2;
''')
m = r.gillespie (0, 30, 10, ["time", "S1", "S2"])
```

The output only returns the first 10 points though.

**Comment by hsauro** [comment]
That works, it just gets the output wrong, results are not on a grid.

Herbert
