### ISSUE TITLE
Type checking on simulate

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#395]
The simulate method calling signature is easy to type incorrectly, especially for novices. When invalid positional parameters are supplied, the user receives a very cryptic error message (see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tellurium-discuss/iQ5YM2u3B3g/y3sk-oyQBwAJ):
```
TypeError: unsupported operand type(s) for -: 'list' and 'int'
```

For this issue, check that numbers are passed to the numerical arguments and selections is a list.

**Comment by kirichoi** [comment]
Merge with Issue https://github.com/sys-bio/roadrunner/issues/401

**Comment by kirichoi** [comment]
Commit https://github.com/sys-bio/roadrunner/commit/6ecc495b5c5e191d4a07bf6af6e9cec9d68c9297 is not functional

**Comment by kirichoi** [comment]
We decided to allow novices to put selections as third positional argument for the sake of their sanity
