### ISSUE TITLE
What is wrong with this code, gives runtime error?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#396]
What is wrong with this code, it gives me  a runtime error:

```
RuntimeError: could not find dep species for cm with id _CSUM0, at ?getIndSpeciesIndexForConservedMoietyId@LLVMModelDataSymbols@rrllvm@@QEBAAEBV?$vector@IV?$allocator@I@std@@@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z
```

I am running:

```
[('tellurium', '1.3.7beta'),
 ('roadrunner',
  '1.4.21; Compiler: Microsoft Visual Studio Unknown Version, C++ version: 199711; JIT Compiler: LLVM-3.5; Date: Jun 26 2017, 16:37:01; LibSBML Version: 5.14.0'),
 ('antimony', '2.9.1'),
 ('snbw_viewer', 'No information for sbnw viewer'),
 ('libsbml', '5.15.0'),
 ('libsedml', '402'),
 ('phrasedml', '1.0.4'),
 ('pySBOL', '2.2.0')]
```

```python
import tellurium as te
import roadrunner

r = te.loada('''
      var AB, A, B
      A + B -> AB; k1*A*B - k2*AB;

      A = 0.001; B = 100; AB = 0;
      k1 = 0.4; k2 = 1;
''')

r.conservedMoietyAnalysis = True;

for i in range (82):
    r.steadyState()
    r._CSUM0 = r._CSUM0 + 0.5    

r._CSUM0 = 38
```

**Comment by 0u812** [comment]
There appear to be two conserved quantities in this model. The first, _CSUM0, is used to compute A, so `A = _CSUM0 - AB`. The second is used to compute B: `B = _CSUM1 - AB`. AB is the only independent variable. AB is thus involved in two conserved quantities, but the software appears to only be keeping track of one. When you try to change the value of `_CSUM0` it tries to change an independent variable to compensate. Unfortunately, the way it's written, it doesn't keep track of the correct independent variable (AB). I'll look into this, but just to make sure my assumptions are correct, can you confirm what the correct behavior is?

When a conserved quantity is changed, either the independent or dependent variable needs to change. I think it currently changes the independent variable and tries to keep the dependent variable constant. Is this correct?

**Comment by hsauro** [comment]
I think changing CSUM0 shouldn't change CSUM1 even though they are linked.

However, I am not sure what this has to do with the bug. If the for loop is
changed from 82 to 80 it does't crash.
