### ISSUE TITLE
Strange discontinuity in control coefficient calculation

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#397]
There is an unaccounted for discontinuity in the calculation below. It is obvious when the data is plotted over a wide range (See accompanying image).  The code below narrows it down to the specific parameter region. It happens when computing the control coefficient with respect to _CSUM0. This is the output from the script below. where we change CSUM0 and then compute control coefficient:

CSUM0 = 38.5, CC = 1.52135096764
CSUM0 = 39, C = 1.52710561149
CSUM0 = 39.5, CC = 1.57178081045
CSUM0 = 40, CC = 1.58281511042

Notice the jump between CSUM0 = 39 and CSUM0 = 39.5

This doesn't look right, maybe a bug?

import tellurium as te
import roadrunner
import pylab

r = te.loada('''
      var AB, A, B
      A + B -> AB; k1*A*B - k2*AB;

      A = 0.001; B = 100; AB = 0;
      k1 = 0.4; k2 = 1;
''')

r.conservedMoietyAnalysis = True;

print "A, B, AB = ", r.A, r.B, r.AB
print "_CSUM0 = ", r._CSUM0
print "_CSUM1 = ", r._CSUM1

r._CSUM0 = 38.5
r.steadyState()
print r.steadyState()
print "CSUM0 = 38.5:", r.getCC ("A", "_CSUM0")
print r.steadyState()
r._CSUM0 = 39
print "CSUM0 = 39:", r.getCC ("A", "_CSUM0")
print r.steadyState()
r._CSUM0 = 39.5
print "CSUM0 = 39.5:", r.getCC ("A", "_CSUM0")
print r.steadyState()
r._CSUM0 = 40
print "CSUM0 = 40:", r.getCC ("A", "_CSUM0")

![image](https://user-images.githubusercontent.com/1054990/30072162-54db811e-921e-11e7-81c3-9d7e02d7fab3.png)

**Comment by 0u812** [comment]
Fixed #422
