### ISSUE TITLE
Another example of discotninuties when computing control coefficients

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#398]
Here is another example of multiple discontinuties when computing control coefficients:

```
import tellurium as te
import roadrunner
import pylab

r = te.loada("""
      J1: $Xo -> X; kcat*(k1*Xo - k11*X);  
      J2: X -> $X1; k2*X/(X + Km);
      X + II -> XI; k3*X*II - k4*XI;

      Xo = 1; k1 = 0.1; k2 = 1;
      k3 = 3; k4 = 0.1; II = 3;
     Km = 0.001; k11 = 12; kcat = 1;
""")

r.conservedMoietyAnalysis = True;

r.Xo = 0.01;
xv = []; yv = []; yc = []
n = 400;
for i in range (n):
    r.steadyState()
    xv.append (r.Xo)
    yc.append (r.getCC ('XI', 'Xo'))
    yv.append (r.XI)
    r.Xo = r.Xo + 0.05

pylab.plot (xv, yv)
pylab.show()
pylab.plot (xv, yc)  
```

The resulting plot is shown below

![image](https://user-images.githubusercontent.com/1054990/30074214-884184fc-9225-11e7-86c7-ca4bf16acecc.png)

I also ran the same model on Jarnac and got no discontinuities, see plot below from Jarnac, must therefore be a problem with libRoadRunner.

![image](https://user-images.githubusercontent.com/1054990/30074250-ae44414e-9225-11e7-9b63-fdda8013cf95.png)

**Comment by 0u812** [comment]
Fixed #422
