### ISSUE TITLE
r.plot(linewidth=2) does not work

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#402]
Some examples in the readthedocs documentation shows plot calls such as:

r.plot(s, loc=None, show=False, color=color, linewidth=2.0)

When I tried:

r,plot (linewidth=2.0)

I get the error message:

plot() got an unexpected keyword argument 'linewidth'

**Comment by 0u812** [comment]
Moved to https://github.com/sys-bio/tellurium/issues/214
