### ISSUE TITLE
Code on readthedocs no longer works

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#404]
I think there are a bunch of examples on readthedocs that no longer work due to changes to the API, eg the following doesn't work because the plot command has apparently changed.

plot() got an unexpected keyword argument 'loc'

     import tellurium as te
     import numpy as np
     import matplotlib.pylab as plt

     # Load a model and carry out a simulation generating 100 points
     r = te.loada ('S1 -> S2; k1*S1; k1 = 0.1; S1 = 10')

     # get colormap
     # Colormap instances are used to convert data values (floats) from the interval [0, 1]
    cmap = plt.get_cmap('Blues')

     # The legend can be suppressed which is useful for plotting large
     # numbers of curves where a legend would get in the way

     k1_values = np.linspace(start=0.1, stop=1.5, num=15)
     max_k1 = max(k1_values)
     for k, value in enumerate(k1_values):
         r.reset()
         r.k1 = value
         s = r.simulate(0, 30, 100)

     color = cmap((value+max_k1)/(2*max_k1))
     # plot curves without legend and showing
     r.plot(s, loc=None, show=False, color=color, linewidth=2.0)

     # add legend for last curve, show everything and set labels, titels, ...
     r.plot(s, loc='upper right', show=True, color=color, linewidth=2.0,
         title="Parameter variation k1", xlabel="time", ylabel="concentration",
         xlim=[-1, 31], ylim=[-0.1, 11], grid=True)

     print('Reference Simulation: k1 = {}'.format(r.k1))
     print('Parameter variation: k1 = {}'.format(k1_values))

**Comment by 0u812** [comment]
I can take care of the plot command changes. @kirichoi do you know if the graphviz stuff can work on Windows, or is it not possible?

**Comment by hsauro** [comment]
I think the draw command should be removed from the *documentation* until
it works on all platforms, this is an issue for Matthias to deal with.

**Comment by 0u812** [comment]
The network visualization seems like an important feature that the reviewers might care about. It might be a good idea to try to get it working on Windows rather than remove it, or at least provide instructions for how users can install graphviz on that platform. Or, possibly modify the draw function to use my layout library instead.

**Comment by hsauro** [comment]
But is there time to do that?

Herbert

**Comment by kirichoi** [comment]
Draw feature on Windows should work. I might have not configured it correctly in the beta version I release few days ago. I will look into that.

**Comment by 0u812** [comment]
Thanks Kiri!

**Comment by kirichoi** [comment]
Graphviz is no longer an issue on Windows. Arguments not working is still an issue.

**Comment by 0u812** [comment]
It looks like the remaining problems are with the Tellurium plotting function (which now should support Plotly and Matplotlib). I have moved the issue to here: https://github.com/sys-bio/tellurium/issues/214
