### ISSUE TITLE
Code on readthedocs not working due to r.draw

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#405]
The follolwing code on readthedocs doesn't work due to:

1. Changes to the syntax of the plot command
2. No support for r.draw on windows.

        import tellurium as te

        r = te.loada('''
        model feedback()
        // Reactions:http://localhost:8888/notebooks/core/tellurium_export.ipynb#
        J0: $X0 -> S1; (VM1 * (X0 - S1/Keq1))/(1 + X0 + S1 +   S4^h);
        J1: S1 -> S2; (10 * S1 - 2 * S2) / (1 + S1 + S2);
        J2: S2 -> S3; (10 * S2 - 2 * S3) / (1 + S2 + S3);
        J3: S3 -> S4; (10 * S3 - 2 * S4) / (1 + S3 + S4);
        J4: S4 -> $X1; (V4 * S4) / (KS4 + S4);

        // Species initializations:
        S1 = 0; S2 = 0; S3 = 0;
        S4 = 0; X0 = 10; X1 = 0;

        // Variable initialization:
        VM1 = 10; Keq1 = 10; h = 10; V4 = 2.5; KS4 = 0.5;
        end''')

       # simulate using variable step size
       r.integrator.setValue('variable_step_size', True)
       s = r.simulate(0, 50)
       # draw the diagram
       r.draw(width=200)
       # and the plot
       r.plot(s, title="Feedback Oscillations", ylabel="concentration", alpha=0.9);

**Comment by kirichoi** [comment]
I might have not included graphviz with the beta version, which will be fixed. However, is graphviz available in other platforms by default? Otherwise, I think we need to put a note that you need graphviz installed first.

**Comment by kirichoi** [comment]
[New version](https://sourceforge.net/projects/pytellurium/files/Tellurium-2.0/2.0.0beta/Tellurium-2.0.0beta3-Python-2.7-win64-portable-setup-beta.exe/download) fixes the issue with not being able to use graphviz. There are other issues (plot function ignoring arguments), but this will be tracked on https://github.com/sys-bio/roadrunner/issues/404.
