### ISSUE TITLE
resetAll() or resetToOrigin() throws errors

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#406]
Moved from https://github.com/sys-bio/roadrunner/issues/373:

Reported by @bouteill
> In LRR 1.4.18, using resetAll() or resetToOrigin() throws errors for me.

> Win 10 - 64bits
Here is the error (same error returned when using resetAll() and resetToOrigin() ):
Traceback (most recent call last):
File "E:/JM_DOCS/DROPBOX/Dropbox/Dropbox/2017-08-August/SHANE/PMCA-2006-Goldstein/test01_simulate_CaM_Effects.py", line 120, in 
r.resetToOrigin()
File "C:\Users\jmbouteiller\AppData\Local\conda\conda\envs\envt_for_LRR\lib\site-packages\roadrunner\roadrunner.py", line 2477, in 
getattr = lambda self, name: _swig_getattr(self, RoadRunner, name)
File "C:\Users\jmbouteiller\AppData\Local\conda\conda\envs\envt_for_LRR\lib\site-packages\roadrunner\roadrunner.py", line 78, in _swig_getattr
return _swig_getattr_nondynamic(self, class_type, name, 0)
File "C:\Users\jmbouteiller\AppData\Local\conda\conda\envs\envt_for_LRR\lib\site-packages\roadrunner\roadrunner.py", line 73, in _swig_getattr_nondynamic
return object.getattr(self, name)
AttributeError: type object 'object' has no attribute 'getattr'
Process finished with exit code 1

**Comment by kirichoi** [comment]
@bouteill: Are you using Tellurium (and import Tellurium with the script you are running) btw? resetAll() and resetToOrigin() have actually became part of Tellurium functions. 

@0u812: We might have to update the roadrunner doc accordingly.

**Comment by 0u812** [comment]
Hi Jean-Marie, good to hear from you! As Kiri says, those functions were added in Tellurium, they are not part of the roadrunner package itself. It seems to be causing confusion, so we will move them over to the roadrunner package. As a workaround, you can use the following surrogates for these functions (this is what they do internally):

**resetToOrigin**:
```
import roadrunner
r = RoadRuner(...)
r.reset(roadrunner.SelectionRecord.ALL)
```
**resetAll**:
```
self.reset(roadrunner.SelectionRecord.TIME |
                   roadrunner.SelectionRecord.RATE |
                   roadrunner.SelectionRecord.FLOATING |
                   roadrunner.SelectionRecord.GLOBAL_PARAMETER)
```

**Comment by bouteill** [comment]
Hi Kyle (it's been a while), Hi Kiri,
Sorry for the confusion. This page ( https://sys-bio.github.io/roadrunner/python_docs/api_reference.html#RoadRunner.RoadRunner.reset) led me to believe that this was part of the RoadRunner package.   I am happy as long as there is a workaround.  
PS: Thank you very much for the workaround / responsiveness!

**Comment by 0u812** [comment]
Hi Jean-Marie! Glad to help. I added these functions to roadrunner itself, and I should have a new release ready via `pip` in a few days.
