### ISSUE TITLE
Model loading via https url not supported

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#409]
More and more services provide their SBML models via https.
Currently such models cannot be loaded with roadrunner.

Example: "https://www.ebi.ac.uk/biomodels-main/download?mid=BIOMD0000000409"
http works without problem: http://www.ebi.ac.uk/biomodels-main/download?mid=BIOMD0000000409

```
In [3]: r = roadrunner.RoadRunner("https://www.ebi.ac.uk/biomodels-main/download?mid=BIOMD0000
   ...: 000409")
Error: HTTPS transport not supported
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-77481c6c2fd3> in <module>()
----> 1 r = roadrunner.RoadRunner("https://www.ebi.ac.uk/biomodels-main/download?mid=BIOMD0000000409")

~/envs/tellurium-web/lib/python3.5/site-packages/roadrunner/roadrunner.py in _new_init(self, *args)
   3453 
   3454     def _new_init(self, *args):
-> 3455         RoadRunner._swig_init(self, *args)
   3456         RoadRunner._makeProperties(self)
   3457 

~/envs/tellurium-web/lib/python3.5/site-packages/roadrunner/roadrunner.py in __init__(self, *args)
   2520 
   2521     def __init__(self, *args):
-> 2522         this = _roadrunner.new_RoadRunner(*args)
   2523         try:
   2524             self.this.append(this)

RuntimeError: Could not open stream: HTTPS transport not supported

In [4]: r = roadrunner.RoadRunner("http://www.ebi.ac.uk/biomodels-main/download?mid=BIOMD00000
   ...: 00409")

In [5]: r
Out[5]: <roadrunner.RoadRunner() { this = 0x1921100 }>

**Comment by hsauro** [comment]
I thought this used to work, Kyle.Kiri, add a unit regression test for
this. I'll add it as an issue.

Herbert

**Comment by 0u812** [comment]
I think supporting this would require adding a crypto library to the dependencies. This could be tricky to get working on all platforms because I think openssl is difficult to build on windows. Also, all of our dependencies are currently built using cmake.

**Comment by doppioandante** [comment]
As a workaround you could do:
```python
from urllib.request import urlopen
with urlopen('https://www.ebi.ac.uk/biomodels-main/download?mid=BIOMD0000000409') as req:
   data = req.read()
```
and then feed data directly to roadrunner (I'm still studying it but I suppose you can do it?)

I don't know if it can be done on the generated python APIs, but the constructor could be wrapped inside a function that checks for https urls (via urllib.parse.urlparse).

**Comment by matthiaskoenig** [comment]
Just to inform: 
EBI and biomodels as part of them switched today completely to https, so no biomodels via http will be available in the near future. Everything redirected to https

**Comment by matthiaskoenig** [comment]
Thanks a lot. This is great.
