### ISSUE TITLE
r.getRatesOfChange() should return dependent and independent rates of change

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#419]
r.getRatesOfChange() only returns independent rates of change. Options:

1. Update r.getRatesOfChange to return independent and dependent rates of change

2. Add two new methods, getFullRatesOfChange, getReducedRatesOfChange. getRatesOfChange should default to getFulLRatesOfChange.

**Comment by kirichoi** [comment]
I think this is already fixed.
