### ISSUE TITLE
Proposal: Remove matplotlib as dependency?

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#423]
For Maciek, our inclusion of matplotlib as a dependency is inconvenient. I think it has to do with container size / performance for CC3D. He doesn't need the plotting functionality, so the matplotlib dependency is useless to him. I put this here because I wanted to poll people. Should we put the matplotlib imports inside the plot function and remove matplotlib as a dependency?

Reasons for:
* Smaller install

Reasons against:
* Users have to manually install tellurium or matplotlib if they want plotting

**Comment by matthiaskoenig** [comment]
I am good with removing. If one wants the plotting in roadrunner one can
easily install the pip package of matplotlib. Just provide a descreptive
warning

**Comment by hsauro** [comment]
I think that is ok. libroadrunner is really meant for developers who want
to use it in their own tools. The lack of matplotlib wouldn't be an
impediment for them. For end users we have the tellurium set.

Herbert

**Comment by kirichoi** [comment]
Same here. As long as there is an instructive warning and documentation update, I am fine with removing matplotlib dependency.
