### ISSUE TITLE
Unscaled Elasticity computation completely broken

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#429]
Here is example where the unscaled elasticity is completely wrong. Model uses first-order irreversible kinetcs so that the unscaled elasticity is just the value of the rate constant, that is 0.24. 

It seems to be using the concentration of the species as the elasticiity. The answer printed out below of 4.1666 is actually the steady state concentration of S1.

Herbert

import tellurium as te
import roadrunner

r = te.loada("""
     $Xo -> S1;  k1*Xo;
      J2: S1 -> S2;  k2*S1;
      S2 -> $X1; k3*S2;
     
      k1 = 0.1;
      k2 = 0.24;
      k3 = 0.14;
      Xo = 10
""")

r.steadyState()

print 'Unscaled: ', r.getuEE ('J2', 'k2'), ' Should be 0.24'
print 'Scaled: ', r.getEE ('J2', 'k2'), ' This is actually correct'

refJ = r.J2
refS1 = r.S1;
r.S1 = 1.05*r.S1;

print 'Numerical Estimate:', (refJ - r.J2)/(refS1 - r.S1)

Output:

Unscaled:  4.16666666667  Should be 0.24
Scaled:  1.0  This is actually correct
Numerical Estimate: 0.24

**Comment by kirichoi** [comment]
I am merging this issue with https://github.com/sys-bio/roadrunner/issues/428. The `getUnscaledElasticityMatrix` seems to work, so this is `getuEE` specific issue.

**Comment by hsauro** [comment]
Ok
