### ISSUE TITLE
RK4 and RK45 failing on specific model

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#436]
RK4 and RK45 cannot simulate the model referenced in https://github.com/sys-bio/roadrunner/issues/420.

**Comment by kirichoi** [comment]
I think this is due to RK4 and RK45 not implementing codes for events and rate rules. Not sure I have time to tackle this.

**Comment by hsauro** [comment]
At this point don't bother adding event support to rk4 and rk45

Herbert

**Comment by CiaranWelsh** [comment]
I think this is stale now so closing but please reopen if I'm wrong
