### ISSUE TITLE
Bizarre nleq behavior

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#437]
We already know that our nleq2 solver cannot find a solution for Matthias' model (from [this issue](https://github.com/sys-bio/roadrunner/issues/420)). However, when I call `steadyState()`, Python seemingly gets stuck in a loop. No crash, no errors, no exceptions (as expected) whatsoever.
This gets promptly resolved when I simulate for certain amount of time and run `steadyState()` which then returns an exception (as expected).

Following gets stuck:
```
import roadrunner

r = roadrunner.RoadRunner(r'jacobiantest.xml')
r.conservedMoietyAnalysis = True

r.steadyState()
```

Following does not (by returning an exception):
```
import roadrunner

r = roadrunner.RoadRunner(r'jacobiantest.xml')
r.conservedMoietyAnalysis = True

result = r.simulate(0, 100000)

r.steadyState()
```

~~What's even bizarre is that nleq2 actually converges to the solution when previously simulated to certain timepoints. For example, this actually works where I simply simulated to time 10000 instead of 100000:~~

```
import roadrunner

r = roadrunner.RoadRunner(r'jacobiantest.xml')
r.conservedMoietyAnalysis = True

result = r.simulate(0, 10000)

r.steadyState()
```
~~Here's the steady state solution:~~

~~[  5.31482484e-02   5.87574980e-03   7.26201417e-05   1.01947750e-01
   9.07628545e-05   1.36254761e-02   6.48623501e-03   4.48379151e-03
   4.83394808e-04   2.98134752e-01   1.29137488e-01   3.09631155e+00
   1.00000000e-01   3.00064508e-01   9.67610120e-04   1.80209546e-06
   4.34260167e-04   5.81340030e-02  **-2.36537466e+00**   1.17651274e-02
   1.49057254e-01   6.51612454e-05   1.00000000e-02   1.59919378e-01
   2.90000000e-01   4.50943134e-01   8.99354917e-02]~~

~~There's a negative concentration!~~ :confused:
~~The negative value corresponds to 'glyglc'. Other values are very close to the steady state solution. I don't think I have changed anything on the roadrunner side to cause this issue, so this must be some nleq2 specific stuff. Could someone confirm this by testing on roadrunner running on nleq1?~~

I am attaching a debug log when Python gets stuck. You see that [this function](https://github.com/sys-bio/roadrunner/blob/develop/source/rrNLEQInterface.cpp#L307) is having some issues. That particular function is feed into nleq2 as `fcn` argument.

[temp3.txt](https://github.com/sys-bio/roadrunner/files/1590114/temp3.txt)

**Comment by kirichoi** [comment]
BTW this is specific to Matthias' model.

**Comment by kirichoi** [comment]
UPDATE: Forget about nleq2 converging. Could not reproduce and probably an artifact. However, first issue is still true (Python gets stuck).

**Comment by hsauro** [comment]
You're going to have to invoke the debugger to find out where it gets stuck.

Herbert

**Comment by kirichoi** [comment]
Reduced priority due to hybrid approach implemented in steady state solver.

**Comment by luciansmith** [comment]
The current version of roadrunner returns an exception with Kiri's original program:

```
RuntimeError: Possible negative concentrations in solution (NLEQ)
```

So, I think this is now solved.
