### ISSUE TITLE
Selection of events

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#440]
Right now, when `model.keys()` are called, events will be listed as well as other available syntax, e.g. _E0, _E1, etc. There's actually nothing users can do using this keyword it seems, and maybe we should remove it from [this function](https://github.com/sys-bio/roadrunner/blob/develop/source/llvm/LLVMExecutableModel.cpp#L835).

Any thoughts?

**Comment by hsauro** [comment]
If you're sure about that then filter them out.

H
