### ISSUE TITLE
Following model gives an error when trying to get A

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#441]
import tellurium as te
import roadrunner

r = te.loada("""
      A -> B; k1*A     
      A = 50
""")

print r.A

RuntimeError: No sbml element exists for concentration selection '[A]'

I think r.A should default to returning the concentration of A. I am sure this used to work.

**Comment by kirichoi** [comment]
This still works but gives me error on missing `k1`.

**Comment by kirichoi** [comment]
Once `k1` is defined, it should work. What I do not understand is why you are not getting error on this. It is supposed to return something like:

`RuntimeError: Global parameter 'k1' missing value and missing init assignment and assignment rule!`
