### ISSUE TITLE
Gillespie gives wrong number of timepoints for one step with same start and end time

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#444]
Hi all,
when running a gillespie with same start and end time and one simulation step two rows should be produced (even if the step is zero). For `cvode` this 2 rows are returned, for `gillespie` only 1 row which is incorrect (and creates some problems when switching integrators).
```
r.reset()
r.setIntegrator('cvode')
s = r.simulate(start=0, end=0, steps=1)
print(s)

r.reset()
r.setIntegrator('gillespie')
s = r.simulate(start=0, end=0, steps=1)
print(s)
```

```
    time, [C], [A], [dummy_S], [D], [fba__A], [fba__C], [fba__B1], [fba__B2], ub_R1
 [[    0,  10,  10,         0,   0,        0,        0,         0,         0,     1],
  [    0,  10,  10,         0,   0,        0,        0,         0,         0,     1]]

    time, [C], [A], [dummy_S], [D], [fba__A], [fba__C], [fba__B1], [fba__B2], ub_R1
 [[    0,  10,  10,         0,   0,        0,        0,         0,         0,     1]]
```
Best Matthias

**Comment by hsauro** [comment]
What was the rational for producing two rows from cvode when timestart and
timeend were zero?

Herbert

**Comment by matthiaskoenig** [comment]
The reason is that the steps define the number of points, i.e. a step=1, should produce 2 points in the solution.

**Comment by matthiaskoenig** [comment]
Too add. I am basically using roadrunner as a lazy model calculator to get the values for things calculated with assignment rules or initial assignments. Basically I have to know values of objects before running the actual simulation.
I cannot run a simulation with steps=0 or points=1 in roadrunner because at least 2 points are expected in the output. If something like this would be possible would be great. 
Nonetheless the different integrators should behave consistently in the dimensions of data they create.

**Comment by kirichoi** [comment]
Actually this is not an issue with gillespie but issue in variable time steps in general. I will push out a fix so any solvers with variable_time_step enabled will return consistent output.
