### ISSUE TITLE
Python error when running  getFrequencyResponse

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#448]
When I try to call the getFrequencyResponse method I appear to get a Python binding error:

TypeError: in method 'RoadRunner_getFrequencyResponse', argument 5 of type 'string const &'

Try running this model:

import tellurium as te
import roadrunner

r = te.loada("""
   $Xo -> x; k1*Xo;
    x ->; k2*x;
    
    k1 = 0.1; k2 = 0.23;
    Xo = 1;
""")

m = r.simulate (0, 50, 100)
r.plot()

r.steadyState()
f = r.getFrequencyResponse(0.1, 4, 1000, 'Xo', 'x', True, False)

**Comment by kirichoi** [comment]
This is a weird one. I think it's a SWIG bug. Anyway, a workaround  is being pushed.
