### ISSUE TITLE
Improve documentation on getFrequencyResponse

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#449]
There is no documentation on the frequency response in the API or documentation. Only information is
```
Computes the frequency response.
```
It would be great if there could be more information, e.g., what method, what is the information one gets? This seems to be a very useful feature, but completely under-documentated. I would like to use this, but have no idea what this function is doing/computing.

Best Matthias

**Comment by hsauro** [comment]
This needs to be added for the next release. Are these docs in
libroadrunner or the python bindings?

Herbert

**Comment by matthiaskoenig** [comment]
I am interested in the docs in python. But this should normally not matter.
It is possible via Swig to export the C++ documentation (this is at least what libsbml is doing with the python bindings). So probably the best strategy to document the C++ API and export the docstrings to python.

**Comment by hsauro** [comment]
We'll get this sorted out.

Herbert
