### ISSUE TITLE
Improve documentation on libStructural

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#450]
`libStructural` is mentioned in the tellurium paper, but there is neither documentation nor examples available in roadrunner.
This is the first time I hear about structural analysis in libroadrunner. The documentation should mention this.
Best Matthias

**Comment by hsauro** [comment]
There and some docs on this but we only bring out a subset of the methods.
libStructural is mainly used internally by libRoadrunner. We released two
months ago a separate libstructural that is much better documented and all
methods are exposed to the Python bindings. I also added Metatool support
by refactoring metatool 4.x into a library.

See

https://www.biorxiv.org/content/early/2018/01/08/245068

Currnently under review at Biosystems.

Herbert

**Comment by matthiaskoenig** [comment]
Thanks this is great. Solves my issue.

**Comment by CiaranWelsh** [comment]
Since this issue is old and the issue seems resolved I'm closing. Please reopen if needed.
