### ISSUE TITLE
Gillespie still produces negative results

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#451]
I think this has been filed before, but I think it never got fixed. 
```
import tellurium as te
import roadrunner

r = te.loada("""
    J1: $Xo -> S1; k1*Xo - k2*S1;
    J2: S1 -> S2; k3*S1 - k4*S2;
    J3: S2 -> S3; k5*S2 - k6*S3;
    J4: S3 -> S4; k7*S3 - k8*S4;
    J5: S4 -> S5; k9*S4 - k10*S5;
    J6: S5 -> ; k11*S5;
    
    Xo = 10.0; S1 = 0.3; S2 = 0.1; 
    S3 = 0.2; S4 = 0.1; S5 = 0.2;
    k1 = 0.2; k2 = 0.3; k3 = 0.8;
    k4 = 0.24; k5 = 0.68; k6 = 0.35;
    k7 = 0.82; k8 = 0.47; k9 = 0.37;
    k10 = 0.22; k11 = 0.1;
""")
r.reset()
r.setIntegrator('gillespie')
s = r.simulate(start=0, end=1, steps=25)
r.plot()
print(s)
```
Output is sometimes:
```
        time, [S1], [S2], [S3], [S4], [S5]
 [[        0,  0.3,  0.1,  0.2,  0.1,  0.2],
  [ 0.487816,  1.3,  0.1,  0.2,  0.1,  0.2],
  [ 0.554092,  0.3,  1.1,  0.2,  0.1,  0.2],
  [ 0.740482,  0.3,  0.1,  1.2,  0.1,  0.2],
  [        1, -0.7,  1.1,  1.2,  0.1,  0.2]]
```
![image](https://user-images.githubusercontent.com/7672320/37856194-5fc34632-2eb0-11e8-9a77-6dced79eb1bf.png)

**Comment by hsauro** [comment]
This is an odd model, you can't have 0.1, 0.3 etc of a molecule as an
initial condition.

Also, the rate laws are odd, eg

k4*S2; for S1 -> S2

All the rate laws are like this where the rate is a function of the
product not substrate.

I think this is a model issue not a problem with gillepsie.

**Comment by kirichoi** [comment]
That's a valid point, especially the part where initial species are not provided as number of molecules. I will close the issue.

**Comment by hsauro** [comment]
I am sure you'd still get negative amounts if the initial conditions are
integer values.

**Comment by kirichoi** [comment]
Actually I don't based on my tests. Probably has some workaround for weird rate laws.
