### ISSUE TITLE
Change the behavior with steadyState()

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#457]
Currently, `steadyState` function will automatically run rough approximation routine at the start (before running NLEQ2) and full approximation routine at the end iff the solver fails to find a solution (as a last ditch effort to get some number).
Two things will change:

1) Initial approximation routine will be switchable via `start_with_approx` flag. Tolerance, maximum number of steps, and maximum time for this initial approximation routine will also be exposed via `start_with_approx_tolerance`, `start_with_approx_maximum_steps`, and `start_with_approx_time`.

2) Previously, these parameters were only accessible via `Config`. This will be changed and all of the parameters for approximation routine will be available in `steadyStateSolver` class. Thus, `steadyStateSolver` will have following settings:
```
('start_with_approx',
 'start_with_approx_tolerance',
 'start_with_approx_maximum_steps',
 'start_with_approx_time',
 'allow_approx',
 'approx_tolerance',
 'approx_maximum_steps',
 'approx_time',
 'maximum_iterations',
 'minimum_damping',
 'relative_tolerance',
 'broyden_method',
 'linearity')
```

**Comment by kirichoi** [comment]
Commits f2d3644bf534bae533f24beb08800e3da598856a to 8910b362888b690933495ab5772e71a05c0e0690 fix this issue. To test, I suggest using the model attached, which is a model that has a steady state but NLEQ2 fails to solve.

```
import roadrunner

r = roadrunner.RoadRunner(r'jacobiantest.xml')
r.conservedMoietyAnalysis = True

ss = r.steadyStateSolver
ss.start_with_approx= False
ss.allow_approx = False
r.steadyState()
```

[jacobiantest.zip](https://github.com/sys-bio/roadrunner/files/1976172/jacobiantest.zip)

**Comment by hsauro** [comment]
What is the difference between start_with_approx and allow_approx? I think
you'll need to find some different terminology, not sure if people would
know the difference.

How about

presimulation_flag
presimulation_endTime
presimulation_numberOfSteps, or is it points?

Do you need maximum steps? Wouldn't it be better to specify the number of
step/points or are they the same thing, if they are then
numberofpoints/steps would be more descriptive.
