### ISSUE TITLE
LLVM 3.5.2 will not compile on Visual Studio 2015 or greater without a patch

### ISSUE THREAD

**Issue by amberhu-uw** [sys-bio/roadrunner#460]
I can upload a fixed version of the LLVM 3.5.2 sources to the wiki, but there are literally only three lines that need to be changed. 

Math.h line 141: add `const` to the functor
Math.h line 389: add `const` to the functor
CostAllocator.h line 93: add `const` to the functor

**Comment by amberhu-uw** [comment]
Addressed by the wiki. Uploaded a patched version of LLVM

**Comment by luciansmith** [comment]
For the record: the new versions of the lines:
Math.h line 141:
      bool operator()(const Vector &A, const Vector &B) const {
Math.h line 389:
      bool operator()(const Matrix &A, const Matrix &B) const {
CostAllocator.h line 93:
      bool operator()(const PoolEntry* a, const PoolEntry* b) const {
