### ISSUE TITLE
Update the .deb file on Travis

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#463]
.deb file used on Travis for installing dependencies needs to be updated.

**Comment by kirichoi** [comment]
Is there any instruction on how to do this?

**Comment by crvineeth97** [comment]
I've made the .deb file with libSBML arrays support included. Could you check if it works on Travis?
[https://drive.google.com/open?id=1EP8-5UFwNxIdtM4tOI9hfWudRbhsgPaf](https://drive.google.com/open?id=1EP8-5UFwNxIdtM4tOI9hfWudRbhsgPaf)

**Comment by kirichoi** [comment]
Great! Is this using the most recent version of https://github.com/sys-bio/libroadrunner-deps with the support for libSBML-5.17.0-experimental?

**Comment by kirichoi** [comment]
Travis is failing, but I think this is due to some Ubuntu bug https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627

@crvineeth97 : Could you double check the deb?

**Comment by crvineeth97** [comment]
@kirichoi 
Travis uses Ubuntu 14.04. I've created another deb from a Ubuntu 14.04 VM. Can you please try that. 
https://drive.google.com/open?id=1rN4cpqSSZqIBGN2narOmzobD0T9KyMzK
Also may I please be provided access to the roadrunner-debs repo?

**Comment by kirichoi** [comment]
Deb seems to be working so far. I have given you the access to that repo as well.

**Comment by kirichoi** [comment]
Just noticed that some dependecies are missing? Please check https://travis-ci.org/sys-bio/roadrunner/builds/398353746?utm_source=github_status&utm_medium=notification

**Comment by crvineeth97** [comment]
The dependencies were there but were being addressed wrong. I've provided a quick but dirty fix for now and Travis seems to be working.

**Comment by kirichoi** [comment]
Yup that was it.
