### ISSUE TITLE
Multiple relational operators not working

### ISSUE THREAD

**Issue by amberhu-uw** [sys-bio/roadrunner#473]
When multiple relational operators are used, as in `1<=2<=1`, only the ends are evaluated, turning the whole expression into `1<=1`. I've just fixed this one, but I thought it would be good to make an issue for all of the libSBML test suite problems.

I've tested that it works in a release version with libSBML 5.16, but 5.17 might potentially cause problems, so I'll figure out how to properly test it with 5.17 and once I'm confident I'll submit the PR to l3v2.

EDIT: The fix for this (PR #474) will solve tests 1209-1216, not just 1212

**Comment by luciansmith** [comment]
Ah, that's actually good to know--I designed the tests assuming that a common failure mode would be only checking the first two arguments; not the first and last argument.  I'll put in some new tests that check against the problem you're seeing, too.  Thanks!

The issue that Kiri created for 'all the libSBML test suite problems' is https://github.com/sys-bio/roadrunner/issues/379 (though it was more focused on 'supporting l3v2'.)
