### ISSUE TITLE
Odd message from steady state solver

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#511]
I got this error message to ay:

Metabolic control analysis only valid for primitive reaction kinetics models. This model has events. Set Config.ALLOW_EVENTS_IN_STEADY_STATE_CALCULATIONS to true to override

What do we mean by primitive reaction kinetic models?  I think the message should be changed too:

"We cannot calculate the steady state of the model because it has events. If you want to override this behavior Set Config.ALLOW_EVENTS_IN_STEADY_STATE_CALCULATIONS to true to override"

Primitive sound like they are mass-action only or something like that.

**Comment by CiaranWelsh** [comment]
@hsauro Is this issue still relevant?

**Comment by luciansmith** [comment]
Looks like the message is now:

                    "The steady state cannot be calculated in a model with events, which this model has. To override set ALLOW_EVENTS_IN_STEADY_STATE_CALCULATIONS to True."
                    "To override, run 'roadrunner.Config.setValue(roadrunner.Config.ALLOW_EVENTS_IN_STEADY_STATE_CALCULATIONS, True)'.");

which seems good to me.
