### ISSUE TITLE
Missing nleq 1/2 headers

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#517]
Trying to build roadrunner against master branch of [libroadrunner-deps](https://github.com/sys-bio/libroadrunner-deps) results in missing headers `nleq2/nleq2.h` and `nleq1/nleq1.h`. I'm on commit 558b74e995d7719d3093488c258a8b6501c7d9f4 of libroadrunner-deps. Looks like some sort of sync issue. @kirichoi, do you know if master the correct branch for libroadrunner-deps?

**Comment by 0u812** [comment]
Instead of this, I just have `nleq/nleq1.h` in the includes.

**Comment by kirichoi** [comment]
If you check the master branch, you can see that it has both nleq1 and nleq2 folders and header files. Commit https://github.com/sys-bio/libroadrunner-deps/commit/9edbcc826a69682e3864b82fe65a8e7a6e39ec80 added these files back, and I haven't had any issue with that commit. Under include dir, you should have both nleq1 and nleq2 folder. I wonder if this is some caching issue?

**Comment by kirichoi** [comment]
I double checked with rebuilding everything from scratch and had no issues. Other possibility is incomplete CMakeList file which is configured properly for settings I am using and not for yours. Are you building static libs?

**Comment by 0u812** [comment]
Oops sorry looks like it was my bad.
