### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#518]
Just documenting that I had to recommit all the line endings, looks like some cr/lf got in somehow. It's not really a problem, just makes the diffs a mess. Windows users can use the [GitHub instructions](https://help.github.com/articles/dealing-with-line-endings/#platform-windows) for setting the correct line ending options to prevent cr/lf from getting committed.

**Comment by kirichoi** [comment]
Seems like they are some old files committed 5~6 years ago. I attest that git for Windows now defaults to crlf while checkout and lf while commit so new commits should not have this kind of issues anymore.

**Comment by 0u812** [comment]
Okay, sounds good. Just wanted to comment here so that people know it was unavoidable.
