### ISSUE TITLE
Document detailed release instructions

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#522]
We need documentation on how to release new versions of RoadRunner, including documentations on:

- [ ] How to build wheels for Windows, Mac, and Linux
- [ ] How to upload wheels to PyPI

**Comment by amberjhu** [comment]
Has there been any progress on this? I think @andrewbriand and @mengfy0718 will want to have this for the summer.

**Comment by CiaranWelsh** [comment]
Implemented with #843
