### ISSUE TITLE
Updated distrib support in roadrunner

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#530]
roadrunner should support latest SBML distrib as of libsbml-5.18.0 (distrib-v0.24)

This is a issue discussed in tellurium, but it is a roadrunner issue so open it here
https://github.com/sys-bio/tellurium/issues/391

I already encode my models with distrib, but lack the simulator to handle such models (only using `uniform`, `normal`, `lognormal` and `poisson` at the moment.

**Comment by luciansmith** [comment]
Went ahead and added support for all the 'distrib' distributions, plus truncation.  https://github.com/sys-bio/roadrunner/pull/561

**Comment by matthiaskoenig** [comment]
@luciansmith This is great news. Thanks so much, was waiting for this.
