### ISSUE TITLE
Get llvm-6 to build on Linux/Travis

### ISSUE THREAD

**Issue by amberjhu** [sys-bio/roadrunner#534]
Right now it is failing with some Poco linkage stuff. It may just be because we're using the wrong debs from libroadrunner-deps. May have to ask Kiri about this.

**Comment by amberjhu** [comment]
I think that the Poco error messages are because the debs are compiled not with c++11, based on [this](https://github.com/openframeworks/projectGenerator/issues/71).

The solution is either to generate new debs or to build from source on Travis. I think that the latter is better temporary fix since I don't know how to make the debs. I will need some help form @kirichoi or @0u812

**Comment by mengfy0718** [comment]
https://github.com/klee/klee/issues/336#issue-132380305

**Comment by faye-u** [comment]
We tried to change the ABI flag based on https://github.com/klee/klee/issues/336#issue-132380305.
It seemed to resolve the Poco Issues, but we got new errors popped up. Few undefined references occurred.

**Comment by 0u812** [comment]
We could switch the dist in .travis.yml to Xenial and I could build the .debs for that with c++11 enabled. I'll try to use gcc-4.8 if I can.

**Comment by andrewbriand** [comment]
I attempted to build the .debs with dpkg-buildpackage, with -std=c++11 added to the cmake c++ flags, on an Ubuntu subsystem with gcc 7.3.0. The packages seemed to build correctly but when I used them on Travis, I got the same errors as before with the original .debs. I will try again with gcc-4.8.

**Comment by andrewbriand** [comment]
I recompiled the .debs with gcc5.5 and the C++11 ABI enabled this time, and reenabled the ABI flag on travis, and the build now passes.

**Comment by amberjhu** [comment]
That's great! Can you merge the changes that fixed Travis back into `develop` and then rebase `llvm-6` so that it can build on Travis

**Comment by andrewbriand** [comment]
I merged `issue-534` on to `llvm-6` and `llvm-6` now passes on Travis.
