### ISSUE TITLE
Double check that all tests pass on LLVM 6

### ISSUE THREAD

**Issue by amberjhu** [sys-bio/roadrunner#536]
I'm not super familiar with the test suite, so even if I see all tests passing, I'm not sure if we're just missing one of the test suites. 

1. Figure out what all of the tests that need to be run are
2. Write them down on the wiki
3. Verify that we are passing all of them
4. If we are not passing some of them, make Github issues about them

Note: if there are a bunch of tests that we're not passing, we don't need to worry about fixing them for 1.5.4 just write down what they are and we'll get to them in a later release.

**Comment by amberjhu** [comment]
I checked the [history of the Suite_SBML_Tests.cpp](https://github.com/sys-bio/roadrunner/commits/llvm-6/wrappers/C/Testing/Suite_SBML_Tests.cpp) in llvm-6 and it looks like I never changed any of the tests, so if all the tests pass, then I think it's good

**Comment by CiaranWelsh** [comment]
We've done a lot with testing in the last year so I'm closing this issue.
