### ISSUE TITLE
What to do with master branch?

### ISSUE THREAD

**Issue by amberjhu** [sys-bio/roadrunner#543]
Usually develop is kind of like nightly releases and master is the stable branch. Master hasn't been updated in quite a while. Should we just merge develop into master every once in a while? Should we merge develop and then stop using it in favor of the master branch? I feel like it is confusing since it breaks convention.

**Comment by kirichoi** [comment]
Yeah I would like `master` to be the default branch as well. Tellurium already does this. All commits are made to `develop` branch and we merge it with `master` when we do releases. New releases will target `master` branch because `master` branch will be the default branch.

**Comment by fbergmann** [comment]
I recommend to use the [gitflow scheme](https://datasift.github.io/gitflow/IntroducingGitFlow.html) (also nicely supported by gitkraken)

**Comment by CiaranWelsh** [comment]
Closing as this has gone stale now.
