### ISSUE TITLE
Gradually uncomment tests

### ISSUE THREAD

**Issue by amberjhu** [sys-bio/roadrunner#545]
I just remembered from commit d97c53c09b27 that most of the newer tests and more importantly tests that are causing problems are commented out. We should probably just start picking tests to fix. I know there's a list of all the SBML suite tests we're not passing somewhere around here that @kirichoi made

**Comment by luciansmith** [comment]
https://github.com/sys-bio/roadrunner/issues/379

**Comment by CiaranWelsh** [comment]
Closing since we've done a lot for testing in the last year.
