### ISSUE TITLE
Fix testing framework so that test output is written to output file after every test

### ISSUE THREAD

**Issue by amberjhu** [sys-bio/roadrunner#547]
There may be a command line argument or something to fix this, but right now if you write output to a file with the argument `-o tests.out` it will only be written to at the *end* of the tests, meaning that if there is a segfault that causes the program to crash midway, the only way to check the output of the tests is to look at which test outputs were written to recently

**Comment by amberjhu** [comment]
Right now, roadrunner is using [UnitTest++](https://github.com/unittest-cpp/unittest-cpp), but it looks like we wrote our own main to wrap the tests. We can either dive into the documentation to figure out how to make this framework more verbose, or we could add a new testing framework like gtest or catch

**Comment by amberjhu** [comment]
@kirichoi @0u812 Do you know how we could get output about which tests are passing printed to the console, so that we can see roughly where a segfault occurs?

**Comment by 0u812** [comment]
There are a few different testing schemes if I recall: built-in unit tests, Python tests (that have to be run via Python) and the SBML Test Suite. This sounds like the first category, correct? Can you post the command used to run the tests?

**Comment by amberjhu** [comment]
I used this one that I put on the wiki Tests page:

```
./run_test_suite.exe -m ../../../source/roadrunner/models/sbml-test-suite/ -r out/tests.out -t out/
```

So, I guess it's the SBML Test Suite

**Comment by CiaranWelsh** [comment]
We use googletest now which takes care of the output for us.
