### ISSUE TITLE
Can't find names of columns from 'simulate' output

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#567]
Roadrunner's output from simulate gives you a numpy ndarray (a 'named array').  In theory, the way to get a list of the names of that array is with 'results.dtype.names' (cf https://stackoverflow.com/questions/7561017/get-the-column-names-of-a-python-numpy-ndarray).

However, in my hands, 'results.dtype.names' is 'None':

    rr = roadrunner.RoadRunner("BIOMD0000000021.xml") #or any file, really.
    results = rr.simulate(0, 100)
    print(results.dtype.names)

yields:

None

The names of the columns are *there*:

    print(str(results["time"]))

yields:

[  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]

Am I doing something wrong?  Is there some other way to get the names of the columns?

**Comment by hsauro** [comment]
Not sure, if you type result you should see the names, they must be stored
somewhere else.

**Comment by fbergmann** [comment]
I think you want `results.colnames`

**Comment by matthiaskoenig** [comment]
Yes, it is `results.colnames`.
Normally, I directly convert my results to pandas DataFrames, than you can access information via dot syntax.

```
import pandas as pd
results = pd.DataFrame(results, columns=results.colnames)
```
Than you can directly work with the results via `results.S1`, `results.time` and so on.

**Comment by hsauro** [comment]
That’s a useful tip.

**Comment by matthiaskoenig** [comment]
Closing this. See answer in discussion thread.
