### ISSUE TITLE
Can't find what optional arguments to 'simulate' are

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#568]
From the docs at:

https://sys-bio.github.io/roadrunner/python_docs/api_reference.html?highlight=simulate#RoadRunner.RoadRunner.simulate

it says that there are optional arguments to simulate, but only lists one of them ('steps').  Are the rest listed somewhere?  If so, can there be a link from the docs?

In related news, is there a way to call simulate with start, end, and list of selections *only*, i.e. no 'number of points'?

**Comment by luciansmith** [comment]
Found them:  the options are listed at 

https://sys-bio.github.io/roadrunner/python_docs/using_roadrunner.html

so I can indeed use the 'selections' keyword.  Having this list in the 'more detailed' simulate docs would be nice.

**Comment by hsauro** [comment]
The docs need some care and attention, but it’s something no one ever likes
to do.

I can’t do the docs musky because I’ve no idea how it works.

Not sure how to arrange the docs between tellurium and libroadrunner.

**Comment by luciansmith** [comment]
I could probably update the docs some myself, though I too don't know where to do so.  It does seem like it'd be nice to only have one place to update all the docs so they didn't have to be updated in several places when things change.

In the meantime, I'll file issues as I find them so when someone does fix them, they'll have a record.

**Comment by hsauro** [comment]
I've asked Kyle to tell where and how to do it.

**Comment by luciansmith** [comment]
None of the old doc links work any more since they've been moved.  I'm closing this; the actual python docstring lists the options, and the readthedocs documentation uses that string.
