### ISSUE TITLE
Bug in getCurrentSBML(), initialConcentrations incorrect

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#572]
Hi all,
I have some major problems with getCurrentSBML(). It seems like for more complex model incorrect initialConcentrations are written in the SBML. See a detailed bug example attached.

I am only loading a model in roadrunner and then getting the current SBML. When comparing the initialConcentrations these are different!

Basically for the attached example for instance the glucose concentration is changed from 5.0 to 14.6605. 

For 
```
import roadrunner
import libsbml

sbml_path = "body19_livertoy_flat.xml"
r = roadrunner.RoadRunner("body19_livertoy_flat.xml")  # type: roadrunner.RoadRunner
sbml_str = r.getCurrentSBML()

doc1 = libsbml.readSBMLFromFile(sbml_path)  # type: libsbml.SBMLDocument
doc2 = libsbml.readSBMLFromString(sbml_str)  # type: libsbml.SBMLDocument

docs = {
    "sbml": doc1,
    "roadrunner": doc2
}

for key, doc in docs.items():
    print(key)
    model = doc.getModel()  # type: libsbml.Model
    s = model.getSpecies("Ave_glc")  # type: libsbml.Species
    print(s)
    print("initial concentration: ", s.getInitialConcentration())
    print("initial amount: ", s.getInitialAmount())

    print("-" * 80)
```
I get 
```
<Species Ave_glc "glucose (venous blood)">
initial concentration:  5.0
initial amount:  nan
--------------------------------------------------------------------------------
roadrunner
<Species Ave_glc "glucose (venous blood)">
initial concentration:  14.6605
initial amount:  nan
--------------------------------------------------------------------------------
```
This is a major problem, because I cannot create any copies of models (currently the only way is via getCurrentSBML() which is affected by this bug).

[bug_example.zip](https://github.com/sys-bio/roadrunner/files/3778289/bug_example.zip)

Best Matthias

**Comment by luciansmith** [comment]
After the previous fix, we now get:

    sbml
    <tesbml.libsbml.Species; proxy of <Swig Object of type 'Species *' at 0x000001E25484B4B0> >
    initial concentration:  5.0
    initial amount:  nan
    --------------------------------------------------------------------------------
    roadrunner
    <tesbml.libsbml.Species; proxy of <Swig Object of type 'Species *' at 0x000001E25484B480> >
    initial concentration:  nan
    initial amount:  14.6605
    --------------------------------------------------------------------------------

Is that OK?  Or do you want the amount converted back into a concentration?

**Comment by matthiaskoenig** [comment]
This works for me. Thanks.
