### ISSUE TITLE
Using make model api produces incorrect units for model

### ISSUE THREAD

**Issue by Basie12** [sys-bio/roadrunner#584]
The following script produces bad SBML with respect to units:

Note that we have to load roadrunner with an empty xml file otherwise we can't produce any model.  See earlier bug issue.

import roadrunner
import tellurium as te
r = roadrunner.RoadRunner('empty.xml')

r.addCompartment('c1', 1.0, False)

r.addParameter('k1', 1.2, False)
r.addParameter('k2', 1.2, False)

# This line produces bad sbml, see below
# It seems to ignore the concentration flag. Also docs don't say what the options are.
r.addSpecies('S1', 'c1', 2.0, "concentration", False)
r.addSpecies('S2', 'c1', False)
r.addSpecies('S3', 'c1', False)

r.addReaction("r1", ["S1"], ["S2"], "S1 * k1", False)
r.addReaction("r2", ["S2"], ["S3"], "S2 * k2", True)

te.saveToFile("Sbml1st.xml", r.getSBML())

Resulting error message from validate sbml online page:

Error Line 8 Column 108: (SBML Validation Rule #10313) Unit identifier references (i.e the 'units' attribute on <Compartment>, the 'units' attribute on <Parameter>, and the 'substanceUnits' attribute on <Species>) must be the identifier of a <UnitDefinition> in the <Model>, or the identifier of a predefined unit in SBML. The subtanceUnits 'concentration' of the <species> with id 'S1' do not refer to a valid unit kind or the identifier of an existing <unitDefinition>. 

<species id="S1" compartment="c1" initialAmount="2" substanceUnits="concentration" hasOnlySubstanceUnits="true" boundaryCondition="false" constant="false"/>

**Comment by andrewbriand** [comment]
The substanceUnits flag of the addSpecies function simply sets the substanceUnits attribute of that species' representation in SBML. Its use case would be for modifying existing SBML models, unless we decide to add functions to allow users to define their own units through libroadrunner. 

I will add an exception that prevents users from specifying substanceUnits that are not in the model and try to clarify the documentation for this.

**Comment by hsauro** [comment]
Can you provide an example script that generates a working sbml model, we
can include it in the doc as an example We did one today that had 3
species, and 2 reactions. The first reaction had a rate law of k1*S1 and
the second one had a rate law of k2*S2/S1.

The second rate law should result in a listofmodifiers section in the
resulting sbml, it works when done from python but we noticed it don’t work
when calling the methods from the C api dll. I want to make sure this all
works before before we let the community know there is a new version.
