### ISSUE TITLE
Typo in docs, eg addSpecies, the boolean flag is incorrectly spelt

### ISSUE THREAD

**Issue by Basie12** [sys-bio/roadrunner#585]
See docs on addSpecies and other model making API

r.addSpecies("s1", "compartment", 0.1, "concentration", false) 

The Boolean flag should be False not false.

**Comment by hsauro** [comment]
Currently being fixed...

**Comment by luciansmith** [comment]
As far as I can tell, this was fixed; found one more false->False fix in the docs but that was it.
