### ISSUE TITLE
Precompiled llvm debug tar broken

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#594]
From https://github.com/sys-bio/roadrunner/wiki/Building-from-Source, there is a link to http://students.washington.edu/andrewhu/llvm-debug.tar.gz which is broken:  it seems to have been cut off and is smaller than it should have been.

I get the error:
[...]
llvm/bin/llvm-nm.exe
llvm/bin/llvm-objcopy.exe

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by CiaranWelsh** [comment]
I'm closing this since we have [downloadable](https://github.com/sys-bio/llvm-6.x/releases/tag/release%2F6.x) llvm-6 builds for the main OS's
