### ISSUE TITLE
libroadrunner's cmake ignores LIBSBML_INCLUDE_DIR

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#598]
When libroadrunner's CMake system looks for libsbml includes, it uses 'THIRD_PARTY_INSTALL_FOLDER'.  It has a user-defined variable LIBSBML_INCLUDE_DIR but doesn't actually use it; it instead uses THIRD_PARTY_INSTALL_FOLDER/include/.

(Also, it uses THIRD_PARTY_INSTALL_FOLDER/include/sbml/, which it shouldn't:  most (maybe all?) of the SBML includes are of the form "#include <sbml/file.h>" , which keeps things easier to keep track of.)

**Comment by CiaranWelsh** [comment]
@luciansmith Is this issue still relevant?

**Comment by luciansmith** [comment]
The build system was completely overhauled after I filed this; I think we're good now.
