### ISSUE TITLE
Support changing boundaryCondition for species (model change)

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#600]
A very common change I have to do in simulation experiments is changing the `boundaryCondition` flag of species. I.e. species should be treated as a boundary species for a certain part of the simulation and be clamped to constant value or a driving function for other parts of a simulation (`boundaryCondition=True`); or in other parts being floating species (`boundaryCondition=False`). A good example are hyperglycemic, euglycemic clamp experiments in which for a certain time the glucose concentrations are clamped to a certain value.

This is currently not possible with roadrunner and requires modification with libsbml and manual copying of concentrations and states between models.

E.g. having a model
```
S1 -> S2: k1*S1
```
I want to simulate the model for 100 steps, then set S1 constant to the value it has at the end of the first simulation and continue the simulation. For this I have to 
- run the model for 100 steps with simulate
- export the current state of the model as SBML
- load the model with libsbml and change the "boundaryCondition" flag on S1 and save the new model
- load the new model with roadrunner (model caching not working, very slow loading)
- set all final concentrations and state variables from the first model as initial conditions in the second model (no option to write model end state as initial state of a model); Also copy all the rest of the state manually, because the second model is a different SBML model then the first model so a cannot transfer the state.
- run the second model.

Similar if I wanted to say
- set S1 to `sin(time)` this would require to change the `boundaryCondition` flag to `true` of the model first, because a species with `boundaryCondition=False` occurring in reactions cannot be modified via assignment rules.

*Suggestion* 
Add a model change function:
```
r.setBoundaryCondition(species_id: str, flag: bool)
```
which allows to modify the boundary condition flag for species. This would move the species from the floating species to the boundary species and vice versa. This would simplify and speedup this common model change. Setting a species to a driving function is a very common thing occurring in experimental data and should be easy to do with roadrunner.

Best Matthias

**Comment by luciansmith** [comment]
This is done!  Looks like it was done as part of the general task of model editing.
