### ISSUE TITLE
Add Reaction or AssignmentRule with symbol "time" in formula fails

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#601]
Adding reactions which use symbol `time` fail.
To reproduce use a model and assign a kinetic law which depends on time.
```
r = RoadrunnerSBMLModel.load_roadrunner_model(MODEL_REPRESSILATOR)
r.addReaction("X_sin", [], ["X"], "2.0 + sin(time)")
```
results in 
```
Traceback (most recent call last):
  File "/home/mkoenig/git/sbmlsim/sbmlsim/examples/example_model_change.py", line 73, in <module>
    run_model_change_example1()
  File "/home/mkoenig/git/sbmlsim/sbmlsim/examples/example_model_change.py", line 16, in run_model_change_example1
    r.addReaction("X_sin", [], ["X"], "2.0 + sin(time)")
  File "/home/mkoenig/envs/sbmlsim/lib/python3.7/site-packages/roadrunner/roadrunner.py", line 4284, in addReaction
    self._addReaction(*args)
  File "/home/mkoenig/envs/sbmlsim/lib/python3.7/site-packages/roadrunner/roadrunner.py", line 3385, in _addReaction
    return _roadrunner.RoadRunner__addReaction(self, rid, reactants, products, kineticLaw, forceRegenerate)
RuntimeError: the symbol 'time' is not physically stored in the ModelData structure, it either does not exists or is defined by an assigment rule (hence it is not a terminal symbol), at virtual llvm::Value* rrllvm::ModelDataLoadSymbolResolver::loadSymbolValue(const string&, const llvm::ArrayRef<llvm::Value*>&)
```
Same problem with AssignmentRules.
```
r.addAssignmentRule("KM", "2.0 + sin(time)")
```
`time` is a valid symbol in formulas.

**Comment by hsauro** [comment]
Andrew, Steve, any comments on this?

Herbert

**Comment by luciansmith** [comment]
Matthias, do you happen to know if 'time in an assignment rule or kinetic law' is in the test suite somewhere?  If not, it should go in.  If you don't know offhand, I can do the search myself; just thought you might possibly know.

**Comment by hsauro** [comment]
Hi Herbert,

Sorry, but I don't have anything useful to add. I haven't actually run
roadrunner yet, but have been focusing on developing a build script that
will simplify compiling. So far, my script works on Mac, should work on
Linux, and works about halfway through on Windows. With luck, I can get the
second half to work on Windows tomorrow.

-Steve

**Comment by matthiaskoenig** [comment]
@luciansmith I have no idea if this is in the test suite, but most likely should be. Roadrunner is supporting assignment rules with `time` on loaded models, it just does not work when adding such assignment rules via the model change api after model loading.

**Comment by luciansmith** [comment]
Oh!  I had missed that the problem was only when adding something.  Thanks!

**Comment by hsauro** [comment]
That’s correct, so it might be to hard to fix it.

**Comment by evilnose** [comment]
resolved by https://github.com/sys-bio/roadrunner/commit/b0d54c23e52cf10652ed14e045db474b84763398
