### ISSUE TITLE
Build system doesn't allow you to not have bzip or zip

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#602]
bzip and zip are optional add-ins to libsbml; if they're present, they can be included, but they can be safely ignored.  It's possible to build libroadrunner-deps such that libsbml is built without either or both.  But it is not possible to build libroadrunner itself without one or both--it will complain and quit if either is absent.

**Comment by CiaranWelsh** [comment]
@luciansmith Is this issue still relevant?

**Comment by luciansmith** [comment]
It's probably still true, but I think it doesn't matter any more because we wrap up the libsbml build better than we used to, and don't rely on whether zip/bzip was gathered by our users.  I'll close it!
