### ISSUE TITLE
Consider changing 'getFloatingSpeciesInitialConditionIds' to 'getFloatingSpeciesInitialConcentrationIds' in C API

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#61]
The python API changes the name of the function to more accurately reflect what's happening under the hood.  Ideally, the same change could be made in the C API, but care would have to be taken to ensure that this didn't break SBW compatibility.

**Comment by 0u812** [comment]
Also need to update docs as well

**Comment by 0u812** [comment]
@luciansmith can you clarify what you mean by breaking SBW compatibility? Is something relying on the name `getFloatingSpeciesInitialConditionIds`?

**Comment by hsauro** [comment]
SBW compatibility is not so important now because the API has broken from
the SBW API anyway. However the current API doesn't suggest whether amounts
or concentrations are coming back or not.The new name would be more
precise. WE can keep the old one but deprecate it.

H

**Comment by luciansmith** [comment]
Man, I wish I could, but I don't remember.  Perhaps my impression was simply that SBW was using the C API, and we wouldn't want to break it?  But if, as Herbert says, the API already diverged, it probably doesn't matter any more.  I'm not even sure if I would keep and deprecate the old name--if some things have already changed, changing this too is probably not that big a deal.

**Comment by 0u812** [comment]
Okay, added `getFloatingSpeciesInitialConcentrationIds` and deprecated `getFloatingSpeciesInitialConditionIds`.
