### ISSUE TITLE
Bug in assignment rules?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#610]
There seems to be a bug in handling assignment rules when there is a single reaction, see script below:

      import tellurium as te

    r = te.loada("""
      // Bug: fails to update reaction rate if the species in the reaction rate
      // is computed from an assignment rule and there is only ONE reaction.
      // If there are two reactions it works
  
      # Inject sine wave into model
      Xo := sin (time*2) + 2;

      # The following works
      //v1x := k1*Xo
      //v1: Xo -> ; v1x
  
      # This doesn't work (but works on copasi)
      v1: Xo -> ; k1*Xo;  

      k1 = 1.0;
      """)

    #te.saveToFile ('c:\\tmp\\bug.xml', r.getSBML())
    m = r.simulate(0, 8, 100, ['time', 'v1', 'Xo'])
    r.plot ()

![image](https://user-images.githubusercontent.com/1054990/80400081-2616d780-886f-11ea-90e0-a2c91102f723.png)

Note v1 is flat, it shouldn't be, it should match Xo

**Comment by evilnose** [comment]
Hi, just to clarify: what should be the expected behavior when a variable is both in an assignment rule and a reaction? 

I'm asking because I tried to replicate this in SBML but I'm getting complaints that "Xo" cannot both be in an assignment rule and a reaction. I could also be missing something since it was not an exact replicate.

Gary.

**Comment by luciansmith** [comment]
Xo has to be a boundary species in that case.  In the SBML file, you set the species to be 'boundaryCondition=true'; in Antimony you write "$Xo" in the reaction.
[onerxn_asnt.zip](https://github.com/sys-bio/roadrunner/files/4562542/onerxn_asnt.zip)

**Comment by luciansmith** [comment]
Here are some simple models that demonstrate the problem.
[rxn_bug_vs_working.zip](https://github.com/sys-bio/roadrunner/files/4566609/rxn_bug_vs_working.zip)
