### ISSUE TITLE
libsbml.dll is not creating while building from source

### ISSUE THREAD

**Issue by debashish05** [sys-bio/roadrunner#614]
When we build libroadrunner-deps from source, no libsbml.dll file is creating in roadrunner/site-package/roadrunner/. It won't be any problem if we are working with roadrunner only. But when we work with rrplugins (auto2000 for bifurcation analysis) and try to import rrplugins, "from rrplugins import * ", It gives runtime error "can't find telplugins_c_api library".

To solve this issue I used libsbml.dll file from tellurium python version 3.6 last year. But since a new version of tellurium is released in December it's not working with the current version of libsml.dll in 3.7 version, by copying manually. I have attached the error while importing rrplugins.
![libsbmlerror](https://user-images.githubusercontent.com/28730065/81483601-feefdb00-925c-11ea-8a44-aabf2987c4e3.png)

**Comment by hsauro** [comment]
That looks like a dll import issue, ie there is a missing dll.

**Comment by debashish05** [comment]
Yes there is a missing dll

**Comment by debashish05** [comment]
Just noticed that libsbml.dll is creating under roadrunner/bin/ and it is working fine if we manually copy that libsbml.dll file to the location site-package/roadrunner. It is working fine with the tellurium version as well.

**Comment by luciansmith** [comment]
This can be fixed with CMake--I'll do that.

**Comment by luciansmith** [comment]
We still only create the static version of the libsbml library by default, but we've adjusted the plugins to use that, too.
