### ISSUE TITLE
Decide whether to warn or throw error when uninitialized parameter present

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#627]
In testing SBML test suite models, some of them have algebraic rules that determine the values of global variables.  Roadrunner is content to ignore the algebraic rules, but when it finds the variable, it panics.  In LLVMModelSymbols.cpp:

                Log(Logger::LOG_WARNING) << "Global parameter, \'"
                        << param->getId() << "\' missing value and missing init "
                        "assignment and assignment rule!, defaulting value to 0.0.";
                Log(Logger::LOG_WARNING) << "This probably is NOT what you want "
                        "with global parameter \'" << param->getId() << "\'.";
                value->setValue(0.0);
                std::stringstream ss;
                ss << "Global parameter '" << param->getId() << "' missing value and missing init assignment and assignment rule!";
                rr::UninitializedValue(ss.str());

First, it warns that there's a problem, and says that the value is going to be set to 0.  Then it throws an error (rr:UninitializedValue) instead, killing the simulation.

We should either warn that the value is going to be set to zero, or throw an error, but not both.

Herbert, do you have a preference on what we do here?

**Comment by luciansmith** [comment]
Herbert says:  definitely throw an error.

**Comment by evilnose** [comment]
Addressed in #655.
