### ISSUE TITLE
RRPlugins cmake not able to find LIBXML2_INCLUDE_DIR and have to explicitly provide the path

### ISSUE THREAD

**Issue by debashish05** [sys-bio/roadrunner#641]
While building rrplugins there is a cmake script that finds libxml2 (files https://github.com/sys-bio/rrplugins/blob/master/cmake/Modules/FindLibXml2.cmake). But it is unable to find the files since the include files are not copying in the install folder. The files are https://github.com/sys-bio/libroadrunner-deps/tree/master/third_party/dependencies/libsbml/include/libxml. And rrplugins is not able to find it in INSTALL_FOLDER/roadrunner/include. So we need to explicitly provide the include path in the cmake step to the source code of libroadrunner-deps/third_party/dependencies/libsbml/include. This will be problem in the later stage of my project.   

I am working on the integration of rrplugins and roadrunner. And need to fix the issue. Can someone verify the issue? I would like to resolve the issue. It will require modification of the cmake file in libroadrunner non-llvm dependency.

**Comment by luciansmith** [comment]
My feeling is that roadrunner shouldn't re-install libxml2 in its own install folder.  Instead, rrplugins should look in the roadrunner-deps install folder, and/or use the system installation (especially for non-Windows systems).  

In our current suggested setup, you would find the include path in INSTALL_FOLDER/roadrunner-deps/include/

**Comment by debashish05** [comment]
Actually roadrunner is not installing anything. Non-llvm dependency is installing. And roadrunner-deps install folder is same as the roadrunner. There is no folder called roadrunner-deps. There is roadrunner/includ/ which contains all 3rd party dependencies. I think I am missing something.

**Comment by CiaranWelsh** [comment]
Closing this for now as Lucian seems to have the plugins working. Please reopen if needed.
