### ISSUE TITLE
libroadrunner 2.0.0 crashes with old state files in python

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#654]
I just updated some workflows to libroadrunner 2.0.0 but see crashes with old state files in python.
I.e. if one uses a libroadrunner state file created with 1.6.1 version 2.0.0 crashes. 

``` 
Expected<T> must be checked before access or destruction.
Unchecked Expected<T> contained error:
The file was not recognized as a valid object file
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
There should be a check if the state file is supported and and error be raised, but not a complete crash of the python interpreter. This would allow me to check if a state file is incompatible with the current roadrunner version and invalidate it. But otherwise I am always at the risk that roadrunner crashes with my current state files.

To explain my workflows in more detail:
- when trying to load an SBML check if a state file exists for it (bashed on SBML file hash)
- if no state file exists create a new state file by loading in roadrunner and saving the state
There is no way to check if the state is working with a given roadrunner version at the moment (I can store this as part of the lookup, so no big issue here).

**Comment by matthiaskoenig** [comment]
Nothing to fix here. I found some workarounds using a combination of file hash and roadrunner version to ensure that state files are tagged with the roadrunner version.

**Comment by luciansmith** [comment]
It looks like this is due to an exit(1) call from LLVM.  This seems like a less than ideal feature of a library; I've now created our own fork of llvm so that we can change this and a couple other things that needed changing.

**Comment by luciansmith** [comment]
This is now fixed for linux and Windows, but still fails on MacOS.

**Comment by luciansmith** [comment]
Given that the exit from LLVM is now addressed and Matthias found a workaround anyway, I'm closing this; feel free to re-open if the issue persists.
