### ISSUE TITLE
Idea for SBMLFactory class in roadrunner tests. 

### ISSUE THREAD

**Issue by CiaranWelsh** [sys-bio/roadrunner#669]
I had a thought about how we could tidy up the dependency of tests on external files in roadrunner. At the moment we need to have lots of `*.xml` files which get used by various tests. This isn't necessarily a problem, but I can think of several reasons why is not optimal. The most obvious is that the tests depend on external files so if they get accidently deleted they will break. More subtly, over time I think it causes bloating of the code base with files that might not be used anymore but nobody wants to delete, in case they break some tests. 

An alternative idea is to set up a SBMLFactory like class. Currently I am using this approach in libOmexMeta. This is what it looks like: 

```
enum ModelType {
    rrSBML_1,
    rrSBML_2,
    };

/*
 * Abstract class implemented by all SBML models
 */
class SBMLModel {
public:
    SBMLModel() = default;

    virtual std::string str() = 0;

};

class SBML_1 : SBMLModel {
public:
    SBML_1() = default;

    std::string str() override {
        return "SBML string 1";
}

class SBML_2 : SBMLModel {
public:
    SBML_2() = default;

    std::string str() override {
        return "SBML string 2";
}

static std::string SBMLFactory(ModelType modelType) {
    if (modelType == rrSBML_1)
        return SBML_1().str();
    else if (modelType == rrSBML_2)
        return SBML_1().str();
    else {
        throw std::invalid_argument("ModelType is not a valid argument.");
    }
}

```

Implementing this might be a pain by hand but a relatively simple one use Python script.

**Comment by luciansmith** [comment]
I've actually often found it useful to have the files themselves available:  if I'm testing a new thing or if an old test breaks, having the file there means that I can use it directly in tellurium/antimony to check it out in other contexts.

**Comment by CiaranWelsh** [comment]
No problem, it was just an idea - I tend to try and have all data for tests inside code, rather than auxillary files - but I admit there could be pragmatic reasons not to. Feel free to close the issue if you think the "sbml-in-files" approach is better.

**Comment by luciansmith** [comment]
I appreciate the idea!  I'll leave it open a bit to ruminate on, and we might do something along these lines in the end after all.
