### ISSUE TITLE
Get Python tests working in Azure

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#715]
Since we moved away from Travis, the python tests have not been run, and they (of course) broke.  They are now fixed again, but they have to run in Azure.  Any platform would be fine; I don't think they need to run in all of them.

**Comment by luciansmith** [comment]
Nope, different tests failed on linux for me than windows, so we better run them everywhere.

**Comment by CiaranWelsh** [comment]
These are working as of e1be6c46234e3f8996cd56bc13f23741b2bc3868. However, on occasion one of the tests (I don't know which) fails, but clicking "rerun failed build" in azure usually fixes the issue. This has happened once on mac and once of linux. Therefore, I leave this issue open for the time being.
