### ISSUE TITLE
Update Azure's libroadrunner-deps

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#717]
I had to change libroadrunner-deps in order to get everything to work--if you can pull those changes into azure, I think that'll start working again, too.

**Comment by CiaranWelsh** [comment]
To clarify, do you mean that we need a release for the changes you have made in libroadrunner-deps?

**Comment by luciansmith** [comment]
In Azure, I think you use a precompiled version of libroadrunner-deps?  It's that precompiled thing that we need a new version of, and to have Azure point to that.

**Comment by CiaranWelsh** [comment]
Yes, we need to make another binary release of libroadrunner-deps, which is just a zip of the install tree. I'm in the process of working out how to automate this process on azure so we don't have to do it manually on each OS. However, I didn't get past the [build errors](https://github.com/sys-bio/libroadrunner-deps/issues/12) so I'm learning with a smaller toy project.

**Comment by CiaranWelsh** [comment]
As of e1be6c46234e3f8996cd56bc13f23741b2bc3868 we have a CI system that always uses the libroadrunner-deps build artifact directly from its own azure pipelines script.  Then means that whenever we push to the dependency project, we should also check to see if it breaks the main roadrunner project.
