### ISSUE TITLE
Unable to install lib roadrunner on MacOS (Big Sur V-11.2)

### ISSUE THREAD

**Issue by efm46** [sys-bio/roadrunner#729]
Hello,

I an writing to let you know I cannot install libroadrunner for my Mac. I just got this Mac to use for PyBNF, which calls on libroadrunner for SBML. 

I am using modern python (python3) and I had to use the following command to attempt to install libroadrunner,
command: sudo -H python3 -m pip install libroadrunner

However I get the following error: ERROR: Could not find a version that satisfies the requirement libroadrunner (from versions: none) ERROR: No matching distribution found for libroadrunner 

Is it something that I am doing wrong or do you guys not yet support the new Big Sur OS?

Thanks in advance, I appreciate it.

**Comment by efm46** [comment]
<img width="701" alt="Screen Shot 2021-02-05 at 11 03 07 AM" src="https://user-images.githubusercontent.com/67076934/107071867-99f0f380-67a2-11eb-992a-44a08cbb57c1.png">


Here is a screenshot of my terminal as well. Thanks!

**Comment by luciansmith** [comment]
Is Big Sur not backwards compatible any more?  If so, that would explain the problem--we've been releasing libroadrunner for MacOS 10.9, because that's been forward compatible with everything up until now.

Can you check to see if you can install numpy?  If not, then Big Sur is indeed the problem.  Because numpy also only provides macos10.9 binaries (as far as I can tell), we'll need to wait for a new Big Sur version of numpy, because libroadrunner relies on numpy.

If you can (and if the file that pip finds has a '10.9' in it), then something else is the problem.  I'm not entirely sure what 'from versions: none' might mean, but it's suspicious, at least...

**Comment by efm46** [comment]
Yea I'm not too sure. I went ahead and installed numpy using sudo, and it installed successfully. I'm not sure where it would say 10.9 exactly, but when it installed numpy it created this wheel (Created wheel for numpy: filename=numpy-1.20.0-cp38-cp38-macosx_10_14_6_arm64.whl).

I tried installing roadrunner again after installing numpy and I still got the same error.

**Comment by efm46** [comment]
Hello again,

I tried installing anaconda's distribution of python3 to make sure I had all the necessary packages. After installation of anaconda I was able to install libroadrunner. Thanks for the help!

**Comment by luciansmith** [comment]
I'm glad it worked!  And it looks like numpy has indeed created a macos10.14 version; maybe they're worried about Big Sur, too.  I'll keep an eye on it, but I'm glad to know it worked for you in the end.

**Comment by viktorashi** [comment]
> Hello again,
> 
> I tried installing anaconda's distribution of python3 to make sure I had all the necessary packages. After installation of anaconda I was able to install libroadrunner. Thanks for the help!

hello! I wanted to know how did you install it after installing conda? was it possible to just do pip install libroadrunner with the pip provided in your conda environment? Cuz i've installed conda just for this issue specifically and it still doesn't seem to be working?

**Comment by viktorashi** [comment]
also did you use miniconda or the full fledged one?

**Comment by luciansmith** [comment]
I would guess that the dependency issue is completely different now than it was in 2021--python loves to change things constantly and is rarely backwards compatible.  What version of MacOS do you have now, and what error message are you seeing?

**Comment by viktorashi** [comment]
> I would guess that the dependency issue is completely different now than it was in 2021--python loves to change things constantly and is rarely backwards compatible. What version of MacOS do you have now, and what error message are you seeing?

oops sorry didnt see you replied so quick. I have Sonoma 14.5 (23F79) and the error is like the one described in the issue above:

`ERROR: Could not find a version that satisfies the requirement libroadrunner (from versions: none)
ERROR: No matching distribution found for libroadrunner`
