### ISSUE TITLE
Support simulate with a vector of timepoints

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#732]
I often need simulation results at specific output points which are not equidistantly spaced. Main example are parameter fittings with data points at arbitrary time points.
To be able to calculate residuals I have to either
- run roadrunner with a high number of points and do an interpolation afterwards to get the simulation results at the requested timepoints. This can result in many timepoints and has the interpolation overhead
- do a repeated step-wise simulation which requires multiple starts and stops of the simulator and copying data between C and python in every step (which also has quite some overhead).

It would be great if one could just say
```
times = [0, 10.23, 14.5, 20, 25]
r.simulate(times=times)
```
This would results in minimal data copying between C and python and no Python interpolations would be required.
This would be an alternative to the points or steps and start, end arguments.
This could also be a separate function
```
r.simulate_times(times=times)
```
to not confuse users using the default syntax.
This would also have some nice features such as being able to do log-scans of the time axis easily.
E.g. `r.simulate(times=np.logspace(-3, 3, num=10)`

**Comment by matthiaskoenig** [comment]
@luciansmith Besides the speedups this would also simplify things for me in the SED-ML parameter fitting implementation. Let me know if you need more information or input on this issue.

**Comment by CiaranWelsh** [comment]
This is actually quite easy to implement. Consider the following: 

```
    OpenLinearFlux openLinearFlux; // data class. Contains a model. 

    RoadRunner rr(openLinearFlux.str()); // model is:  `-> S1 -> S2 ->` 

    // run normal simulation
    SimulateOptions opt;
    opt.start = 0;
    opt.duration = 20;
    opt.steps = 20;
    auto sim = rr.simulate(&opt);
    std::cout << *sim << std::endl;

    /**
     * Output:
     *  time,[S1],[S2]
     *  0,  0,0
     *  1,  0.951626,   0.0452795
     *  2,  1.81269,    0.164293
     *  3,  2.59182,    0.335876
     *  4,  3.2968,     0.543445
     *  5,  3.93469,    0.774091 // 3.93469,0.774091 (pasted from below)
     *  6,  4.51188,    1.01786
     *  7,  5.03415,    1.26713
     *  8,  5.50671,    1.51619
     *  9,  5.9343,     1.7608
     *  10, 6.32121,    1.99788 // 6.32121,1.99788
     *  11, 6.67129,    2.22531
     *  12, 6.98806,    2.44165
     *  13, 7.27468,    2.64605
     *  14, 7.53403,    2.83808
     *  15, 7.7687,     3.01764 // 7.7687,3.01764
     *  16, 7.98103,    3.18485
     *  17, 8.17316,    3.34004
     *  18, 8.34701,    3.48363
     *  19, 8.50431,    3.61617
     *  20, 8.64665,    3.73823 // 8.64665,3.73823
     */

    rr.reset(); // just to be sure. 

    CVODEIntegrator integrator(rr.getModel());

    std::vector<double> times({0, 5, 10, 15, 20});
    for (const auto& i : times){
        integrator.integrate(0, i);
        std::cout << rr.getFloatingSpeciesConcentrationsNamedArray() << std::endl;
    }

    /**
     * Outputs:
     *   S1,S2
     *   0,0
     *   
     *   S1,S2
     *   3.93469,0.774091
     *   
     *   S1,S2
     *   6.32121,1.99788
     *   
     *   S1,S2
     *   7.7687,3.01764
     *   
     *   S1,S2
     *   8.64665,3.73823
     *   
     *
     */
```

Which is nice since it only solves integrates `n` times for `n` time points (unless there's something more going on under the hood which I'm missing). 

So our options are: 
    1) Write an overload in `rrRoadrRunner::simulate(std::vector<double> times)` (or a new name, as suggested)
    2) Expose CVODEIntegrator to Python so we can do it there and give users more control - (should be just a matter of `%include "CVODEIntegrator.h` in roadrunner.i) 
    3) Both? 
    4) Something I haven't though of? Problems with this approach? 

Side note: might be good to write an overload of `simulate` in C++ that behaves more like the `Python` version anyway. Using the `SimulateOptions` is a bit clunky.

**Comment by hsauro** [comment]
Lucian said he'd implement this feature.

**Comment by CiaranWelsh** [comment]
No problem - thought I'd chime in since I used the above strategy for presimulation of steady states.

**Comment by matthiaskoenig** [comment]
This looks basically what I would expect from the underlying implementation. I.e. run one-step integrations from point to point.

**Comment by matthiaskoenig** [comment]
@luciansmith and @CiaranWelsh As mentioned above not complicated at all. I would need this for parameter fitting. It would be great if this could be supported.

**Comment by hsauro** [comment]
Agreed this is something we should do.

Once Ciaran has finished adding the time dependent sensitivity
functionality and Lucian is done with the sedml work we should return to
this and the pickley request.

**Comment by luciansmith** [comment]
This is now done with https://github.com/sys-bio/roadrunner/pull/827 !  There's a new 'times' argument for the 'simulate' function, that you can use instead of start/end/duration.

**Comment by matthiaskoenig** [comment]
@luciansmith This is amazing, makes so many things so much easier.
We finally need in person COMBINE or HARMONY again so I can invite you for dinner ;)
