### ISSUE TITLE
This sbml model causes the python kernel to restart

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#752]
If I try to load the following model (it has no parameters but does have reactions with parameters, therefore the sbml is not valid) it restarts my python kernel. Github Issues won't let me upload the file so here is the string.

All I do is: r = te.loadSBMLModel(sbmlstr)

<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns="http://www.sbml.org/sbml/level3/version2/core" level="3" version="2">
  <model>
    <listOfCompartments>
      <compartment id="c1" size="1" constant="false"/>
    </listOfCompartments>
    <listOfSpecies>
      <species id="S1" compartment="c1" initialConcentration="0.1" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
      <species id="S2" compartment="c1" initialConcentration="0.2" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
    </listOfSpecies>
    <listOfReactions>
      <reaction id="reaction2" reversible="false">
        <listOfReactants>
          <speciesReference species="S2" stoichiometry="1" constant="true"/>
        </listOfReactants>
        <listOfProducts>
          <speciesReference species="S1" stoichiometry="1" constant="true"/>
        </listOfProducts>
        <kineticLaw>
          <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply>
              <times/>
              <ci> k1 </ci>
              <ci> S2 </ci>
            </apply>
          </math>
        </kineticLaw>
      </reaction>
    </listOfReactions>
  </model>
</sbml>

**Comment by hsauro** [comment]
Update, nothing to do with parameters, there is something else wrogn with the XML file. Antimony reports:

antimony.getLastError()
Out[6]: 'Unable to read SBML string due to errors encountered when parsing the file.  Error(s) from libSBML:\n\nline 3: (01023 [Error]) XML declaration not permitted in this location.\n\n'

**Comment by hsauro** [comment]
Further investigation by Lucian reveals that there is was an empty ine at the start of the xml string which libsbml doesn't like. Resolution, we need to trap this error in roadrunner before it causes problems.

**Comment by CiaranWelsh** [comment]
Implemented in #768
