### ISSUE TITLE
Roadrunner must raise RuntimeError for csymbol delay (unsupported MathML symbols)

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#754]
Roadrunner gives incorrect results for SBML models with delays.
E.g. [BIOMD0000000024.zip](https://github.com/sys-bio/roadrunner/files/6373357/BIOMD0000000024.zip)

Despite not supporting delays numerical results are returned. The correct behavior would be to raise a RuntimeError that models with csymbol `delay` are not supported.

Copasi handles this better and raises errors
```
ERROR in 'BIOMD0000000024' Error while running the simulation: >EXCEPTION 2021-04-26T00:18:06<
  CTrajectoryMethod (25): Invalid state at time '1.000000'.
```

Even better would be to support delays ;) See my issue from 5 years ago
https://github.com/sys-bio/roadrunner/issues/303

**Comment by luciansmith** [comment]
Fixed with https://github.com/sys-bio/roadrunner/pull/845: we now throw on load of SBML models with delay.
