### ISSUE TITLE
access violation in bifurcation analysis

### ISSUE THREAD

**Issue by shoepfl** [sys-bio/roadrunner#773]
I tried to perfom a bifurcation analysis with rrplugins as described in the documentation of libroadrunner.

However I get the following error:
OSError: exception: access violation reading 0x0000000000000000

I also tried it with an example SBML file but gut the same error. I am working on an windows machine with anaconda but also tried it on jupyter hub on a linux cluster where the kernel was disrupted by executing the bifurcation analysis.
[Bifurcation_libroadrunner_error.txt](https://github.com/sys-bio/roadrunner/files/6499405/Bifurcation_libroadrunner_error.txt)

I attached the python script I try to execute - like mentioned it does not work for any SBML model.

I am very grateful for any advice.

**Comment by BenNordick** [comment]
This happens to me on every platform I have tried as long as there is more than one rate rule. Interestingly, adding a boundary species (even one that doesn't do anything) seems to work around the problem: I add a rate rule that turns the fake boundary species into one of my floating species, give this rate rule a constant rate of zero, and set the fake boundary species' concentration to zero.

**Comment by shoepfl** [comment]
Thank you for your response. I tried to add a boundary species as you described but sadly get still the same error. Do you have a minimal example for which i can test my system? Thank you in advance

**Comment by BenNordick** [comment]
I'm using the Tellurium library for Python with an [Antimony](https://tellurium.readthedocs.io/en/latest/antimony.html) model. With rrplugins 2.0.4 in Python 3.8.5 on 64-bit Ubuntu 20.04, this segfaults...

```python
import tellurium as te
import rrplugins

runner = te.loada('''
J1: -> X; k - X
J2: -> Y; X - Y

k = 2
''')

auto = rrplugins.Plugin('tel_auto2000')
auto.setProperty('SBML', runner.getSBML())
auto.setProperty('PrincipalContinuationParameter', 'k')
auto.setProperty('RL0', 0)
auto.setProperty('RL1', 5)
auto.execute()
```

...but changing the model string to include a boundary species works:

```
JF: $F -> X; 0
J1: -> X; k - X
J2: -> Y; X - Y

k = 2
$F = 0
```

**Comment by luciansmith** [comment]
Obviously, the program shouldn't crash in general, though I'm glad there's a workaround that seems to work at least some of the time.  I'm investigating now, and will let you know what I discover.

**Comment by shoepfl** [comment]
@BenNordick thank you very much - this works for me as well. I rewrote my model in Antimony and included the boundary species as you described and this worked around the problem. 

@luciansmith thank you for having a look into it

**Comment by luciansmith** [comment]
This is now fixed with https://github.com/sys-bio/roadrunner/pull/824/commits/4275c32a373a3dca3dfaa2fe03abeeb4d0dc988b

Also, I can report that the roadrunner bug was entirely due to there not being any boundary species in the model, so the workaround will work fine, and will not change the results of the analysis.  Thank you for the report!
