### ISSUE TITLE
Clean up new warnings

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#779]
There are a lot of new warnings when building roadrunner, mostly due to the Poco switch; it would be nice to get them all cleared out again.

**Comment by CiaranWelsh** [comment]
Many of the warnings are due to llvm6 being compiled on c++17, some might be Poco. I looked into one or two of them and they seemed benign.

**Comment by CiaranWelsh** [comment]
Just found `–DLLVM_ENABLE_WARNINGS=OFF` which might be a possibility to hide these warnings if we were so inclined.

**Comment by luciansmith** [comment]
The warnings turned out to be the same warnings as before, but the new llvm code added a few #includes that slipped through the cracks of my #pragma's turning them off.  Wrapped everything up nicely again, and now we're warning-free once more.  Which is good, because among the pages and pages of llvm warnings was a single actual warning that needed to be fixed.

https://github.com/sys-bio/roadrunner/pull/972
