### ISSUE TITLE
`getHasOnlySubstanceUnits` missing from Python interface

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#793]
Only the setHasOnlySubstanceUnits not the getHasOnlySubstanceUnits is exposed in python on the RoadRunner object. I think the getter is missing form the swig interface.
See also comments in https://github.com/sys-bio/roadrunner/pull/782

@luciansmith Would it be possible to fix this smaller issue in the Swig interface (i.e. expose the `getHasOnlySubstanceUnits` method)?  Then I could implement the `symbols` in SED-ML and reproduce your `concentration_amount.sedml` and `concentration_amount_b.sedml` SED-ML examples.

**Comment by CiaranWelsh** [comment]
Lucian only added this method recently, which means it won't be in the publically available Python API's until the next release - unless of course you get the most recent binaries/pip wheels from the [develop branch on azure](https://dev.azure.com/TheRoadrunnerProject/roadrunner/_build/results?buildId=770&view=artifacts&pathAsName=false&type=publishedArtifacts).

**Comment by matthiaskoenig** [comment]
Yes, I tried this with the latest azure develop builts, but only saw the setter not the getter.

**Comment by CiaranWelsh** [comment]
hmm that's odd, since I have the following in my branch - and this is content merged from develop: 

```
    # roadrunner.py
    .
    . 
    .
    def setHasOnlySubstanceUnits(self, sid: "std::string const &", hasOnlySubstanceUnits: "bool", forceRegenerate: "bool"=True) -> "void":
        r"""
        Set the hasOnlySubstanceUnits attribute for an existing species.
        :type sid: string
        :param sid:: the ID of a species
        :type hasOnlySubstanceUnits: boolean
        :param hasOnlySubstanceUnits:: the value of hasOnlySubstanceUnits attribute to be set
        :type forceRegenerate: boolean, optional
        :param forceRegenerate:: a boolean value to indicate if the model is regenerated
            					       after this function call
            						   default value is true to regenerate model after each call
                                    of editing function
            						   to save time for editing for multiple times, one could
            					       set this flag to true only in the last call of editing
        """
        return _roadrunner.RoadRunner_setHasOnlySubstanceUnits(self, sid, hasOnlySubstanceUnits, forceRegenerate)

    def getHasOnlySubstanceUnits(self, sid: "std::string const &") -> "bool":
        r"""
        Get the hasOnlySubstanceUnits attribute for an existing species.
        :type sid: string
        :param sid:: the ID of a species
        """
        return _roadrunner.RoadRunner_getHasOnlySubstanceUnits(self, sid)

    .
    .
    .
```

If you just sit tight for another few days, I'll be merging the sensitivity branch (cvodes-2) into develop which has the above - so presumably resolves this issue. 

Ciaran

**Comment by matthiaskoenig** [comment]
Sounds great. Thanks

**Comment by luciansmith** [comment]
It looks like this is working for me as well, now that everything is merged again.  Closing; will be in next release.
