### ISSUE TITLE
Issue on Mac OS numpy

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#796]
Mac OS  Big Sur
Installing Telluriumn 
Python had a newer numpy, asked to downgrade to a lower numpy

[('tellurium', '2.2.0'),
 ('roadrunner', '2.0.5'),
 ('rrplugins', '2.0.4'),
 ('antimony', '2.12.0'),
 ('libsbml', '5.18.0'),
 ('libsedml', '2.0.15'),
 ('phrasedml', '1.1.1')]

Traceback (most recent call last):
  File /var/folders/s2/28x1v8z176bgkg89mdzsr72r0000gn/T/ipykernel_21918/146626175.py", line 9, in <module>
RuntimeError: Object of type <class 'NamedArray'> appears to be C subclassed NumPy array, void scalar, or allocated in a non-standard way.NumPy reserves the right to change the size of these structures. Projects are required to take this into account by either recompiling against a specific NumPy version or padding the struct and enforcing a maximum NumPy version.

**Comment by luciansmith** [comment]
Yup, this is an old issue that has been fixed in the source, but hasn't been released yet.

**Comment by luciansmith** [comment]
I'm going to close this since we're about to release and this will work going forward.  Also, if anyone runs into this in the meantime, switch from 'libroadrunner' to 'libroadrunner-experimental' and that should also solve the problem.
