### ISSUE TITLE
Specifiy output list in timeSeriesSensitivities

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#802]
How does a user specify the variables it wants returned by timeSeriesSensitivities?

With simulate can can use something like

m = r.simulate (0, 10, 100, ['S1', 'S2'])

**Comment by CiaranWelsh** [comment]
Implemented with #835 

Syntax is now 
```
m.timeSeriesSensitivities(0, 10, 11, params=["k1"], species=["S1"], k=1)
```
