### ISSUE TITLE
How to plotting timeSeriesSensitivities data

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#803]
timeSeriesSensitivities returns a bunch of data:

time, sens, rownames, colnames = r.timeSeriesSensitivities(0, 10, 11)

what is the best way to plot this? Is there a helper function a user can use to plot the data, eg

plotts (['k1'], ['S1'])

or

plots (['k1'], ['J1'])

**Comment by CiaranWelsh** [comment]
Implemented with #835 

Syntax is 
```

m= RoadRunner(sbml)

time, sens, rownames, colnames = m.timeSeriesSensitivities(0, 10, 11)
fname = join(dirname(__file__), "OpenLinearFluxSensitivities.png")
roadrunner.plotTimeSeriesSens(time, sens, rownames, colnames, ncol=2, fname=fname)
print(f"Plot image saved to \"{fname}\"")
```
