### ISSUE TITLE
Links to Python documentation are broken

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/roadrunner#806]
The link in http://libroadrunner.org/documentation-2/ to http://sys-bio.github.io/roadrunner/python_docs/index.html (in "Advanced [Python interface] with equivalent functionality") is broken. It seems the docs have moved to https://sys-bio.github.io/roadrunner/docs-build/PythonAPIReference/api_reference.html.

In fact, there are several broken links to http://sys-bio.github.io/roadrunner/python_docs/. See https://github.com/sys-bio/roadrunner/search?q=python_docs&type=code.

**Comment by jonrkarr** [comment]
Links to C and C++ documentation are also broken
http://sys-bio.github.io/roadrunner/cpp_api_docs/
http://sys-bio.github.io/roadrunner/c_api_docs/

**Comment by luciansmith** [comment]
We revamped the documentation so it's now centralized, so these broken links are now gone.
