### ISSUE TITLE
Get plugin tests working on Mac/Linux

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#809]
Something about the way the libraries are linked causes the plugin tests to fail on mac and linux.  Some progress was made by stripping unnecessary libraries from being linked to the plugin libraries, but problems remain.

I believe the basic problem is that some support libraries (including poco and the plugins basic library that includes telConstants.h) are linked to both the plugins c api library as well as the individual plugins libraries (libtel_*).  On Windows, this is fine, but Linux and Mac get hopelessly confused as soon as the PluginManager loads in one of the plugin libraries.

I have not investigated whether this issue extends to the mac/linux python libraries, but the existing auto2000 plugin has been around and has been used for some time now with no reported problems of this nature, so it may be that the python environment helps, for some reason.

It may also be that Ciaran's recent change to how poco is built has somehow contributed to the problem.  Unfortunately, the plugins weren't being tested when he made the change, so it's difficult to tell if the change created the problem, exacerbated the problem, revealed the problem, or did not affect the problem at all.

**Comment by luciansmith** [comment]
Here's the result of running 'valgrind' on a stripped-down test where the only thing it does is create a PluginManager that looks in a single directory and loads the only plugin there, the 'hello' plugin:

[plugapi.log](https://github.com/sys-bio/roadrunner/files/7049542/plugapi.log)

(Also, the 'load' function in the PluginManager has has all of the logging functions commented out, so that we don't get a huge list of poco errors as well.)

**Comment by rheiland** [comment]
Is there any update to this issue? I am simply trying to understand how plugins work (on macOS) and am a little confused. For starters, I thought this link (https://github.com/sys-bio/roadrunner/releases) was supposed to provide binaries for various platforms. The current/latest (https://github.com/sys-bio/roadrunner/releases/tag/v2.2.4) seems to provide only source code - true? My current situation is:
```
M1P~/git/roadrunner/rrplugins$ cmake .
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at rrplugins/CMakeLists.txt:11 (install):
  install TARGETS given target "roadrunner_c_api" which does not exist.
```

**Comment by luciansmith** [comment]
Sadly, the short answer to your question is that plugins don't work on MacOS (nor Linux).  My best guess is that it has something to do with the way I'm trying to link things, but none of my tests or research have revealed why, much less why it would work on Windows but not anywhere else.  

The source code is indeed the only thing provided for Mac/Linux, since the binaries simply fail if you try to use them.  You should be able to build them, along with everything else, from the main directory with -DBUILD_RR_PLUGINS=ON  And I'm still building the binaries on azure, though not distributing them--if you'd like to see them fail yourself, you can get them from https://dev.azure.com/TheRoadrunnerProject/roadrunner/_build/results?buildId=1805&view=artifacts&pathAsName=false&type=publishedArtifacts (the wheel files in particular).

The issue is still on my radar, and I go back and poke at things every time I get a new idea, but so far nothing's worked.

**Comment by luciansmith** [comment]
Fixed the plugins a while back now, though it was an open issue for a long time.
