### ISSUE TITLE
`rr::ExecutableModel::set*Values(int,int const *,int,double const *)` methods don't work from Python

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/roadrunner#817]
The [Python API documentation](http://sys-bio.github.io/roadrunner/docs-build/PythonAPIReference/cls_ExecutableModel.html?highlight=setglobalparametervalues#RoadRunner.ExecutableModel.setGlobalParameterValues) shows methods for setting species concentrations, parameter values, etc. These functions don't work as illustrated from Python.

For example (copied from the documentation)
```python
import roadrunner
rr = roadrunner.RoadRunner()
rr.load('tests/fixtures/BIOMD0000000003_url.xml')
rr.model.setGlobalParameterValues([0], [1.5])
```

results in the following exception
```
NotImplementedError: Wrong number or type of arguments for overloaded function 'ExecutableModel_setGlobalParameterValues'.
  Possible C/C++ prototypes are:
    rr::ExecutableModel::setGlobalParameterValues(size_t,double const *)
    rr::ExecutableModel::setGlobalParameterValues(int,int const *,int,double const *)
```

Environment:
- libroadrunner: 2.0.5
- Python: 3.9.5

**Comment by hsauro** [comment]
I think I've seen something like this before. I've a feeling it's an error
in the docs.

Lucian, do you know what the correct arguments are?

**Comment by luciansmith** [comment]
Well, setting individual elements continues to work (as noted); we just need to figure out what broke setting element by vector.

**Comment by jonrkarr** [comment]
Eventually I figured out I can use dictionary-style attributes on executable model objects instead.

Setting individual elements doesn't work. I couldn't figure out how to satisfy the interface from Python. I tried a variety of things including using NumPy as the documentation suggests and the ctypes module.

Vector setting seemed like it probably works, but there's validation that prevents that from being usable in some cases (e.g., setting non-constant parameters).

**Comment by luciansmith** [comment]
Setting individual elements works by calling 'rr.setValue("S1", 5)'  You can also do rr["S1"] = 5 or even (when legal) rr.S1 = 5.

**Comment by jonrkarr** [comment]
Yes, that style of setting elements works.

**Comment by luciansmith** [comment]
What didn't work for you for 'setting individual elements'?  Those three methods are the ones I know of.

**Comment by jonrkarr** [comment]
For example, `setGlobalParameterValues` doesn't work with length-1 arrays.

**Comment by luciansmith** [comment]
Ah, OK.  So it's still the vector setting that's the problem.

**Comment by jonrkarr** [comment]
Sorry, if that was confusing. RoadRunner has yet another set of functions that I would think of a (dense) "vector" setting, where the values of all of the components (of a given type) can be set at once.

**Comment by luciansmith** [comment]
Got it:  so it's the plural functions setValues and set[TYPE]Values that both are currently broken, and don't work regardless of vector length.

**Comment by jonrkarr** [comment]
`set[TYPE]Values` didn't work for me. I didn't try `setValues`.

The alternative function signatures for dense array input seemed to work, with the caveat that they can't be used when some variables are read only.

**Comment by luciansmith** [comment]
This turned out to be an issue with a Swig update, I think.  At any rate, I got it to work again!

Also, FWIW, the version of these functions without the 'index' arguments seem to work in the current version, i.e. 'setGlobalParameters([1.3, 2.2, 5.0])'
