### ISSUE TITLE
addSpecies broken

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#820]
The 'addSpecies' function is broken though the 'addCompartment' is not:

```
r = te.loada("a=3")
r.addCompartment("comp", 1)
r.addSpecies("S1", "comp", 3.2)

**Comment by luciansmith** [comment]
@CiaranWelsh : This is broken in libroadrunner-experimental, but works in the (very old now) libroadrunner.  Could it have to do with Swig updates?

**Comment by CiaranWelsh** [comment]
That’s right - I believe @hsauro changed these to addSpeciesAmount and addSpeciesConcentrations.

**Comment by CiaranWelsh** [comment]
…though perhaps in this case it would be better to change it back to addSpecies (open closed principle) but add a keyword argument that defaults to concentrations for the sake of backwards compatibility?

**Comment by luciansmith** [comment]
Ah, that makes sense, and yes, now that I've been messing with the .i files I should be able to change it to that version.  Thanks!

**Comment by luciansmith** [comment]
Fixed with https://github.com/sys-bio/roadrunner/pull/822

(However, I didn't add any tests.  I'll make a separate issue for that.)
