### ISSUE TITLE
Add python tests for python-only functions.

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#823]
Anything wrapped in a non-standard way in roadrunner.i needs to be tested in Python.  This includes all the 'reset' functions and the 'edit the SBML model' functions at least, but probably also includes more.

We want to avoid the situation where 'addSpecies' used to work, but then broke because the underlying function was changed.

**Comment by CiaranWelsh** [comment]
I generally use either [python_api_tests.py](https://github.com/sys-bio/roadrunner/blob/develop/wrappers/Python/roadrunner/testing/python_api_tests.py) for this or have. been creating new dedicated Python test files such as [AutomaticMoietyConservationAnalysisTests.py](https://github.com/sys-bio/roadrunner/blob/develop/test/sundials-tests/SundialsSteadyStateTests/AutomaticMoietyConservationAnalysisTests.py) or [ForwardSensitivitySolverTests.py](https://github.com/sys-bio/roadrunner/blob/develop/test/sundials-tests/ForwardSensitivitySolverTests/ForwardSensitivitySolverTests.py). If you choose the latter, it's easy enough to add the new Python file to ctest (which automatically runs everything on the azure) [here](https://github.com/sys-bio/roadrunner/blob/develop/test/CMakeLists.txt#L321).

**Comment by luciansmith** [comment]
So, it turns out the problem here was more that the rrtests weren't being checked than that there weren't tests--both 'addSpecies' and 'resetAll' (and others) were being tested; we just didn't notice them failing before.  This is now fixed!
