### ISSUE TITLE
Azure tests don't notice failed python tests.

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#828]
If you look at 

https://dev.azure.com/TheRoadrunnerProject/255e6ce3-64bc-4a95-a8c8-2a25dc15a90e/_apis/build/builds/887/logs/112

you'll see that the 'resetAll' test failed, but Azure didn't notice, and marked the build as a success.

**Comment by CiaranWelsh** [comment]
I've resolved this by running the `tester.py` from a `unittest` wrapper. I force merged the fix into develop so that now the develop branch is correctly failing, and needs fixing.

**Comment by luciansmith** [comment]
Thank you!

I have the 'resetAll' tests fixed (in the wrong branch, but enh.) and just have one test left to fix.
