### ISSUE TITLE
Make new libroadrunner-experimental release

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#865]
Hi all,

could you make a new libroadrunner-experimental release
https://pypi.org/project/libroadrunner-experimental/
The last one is from end of July. I want to use/test many of the latest fixes/features which will be in the 2.1 release and would require these for my SED-ML support. 

The idea of the experimental release is to give early access to these features and allow feedback/testing before the actual release ;) 

Best Matthias

**Comment by luciansmith** [comment]
We haven't because every week we expect to release a new normal release ;-)

*Something's* coming soon; if we can't get a normal release out, we'll do an experimental.  Thanks!

**Comment by matthiaskoenig** [comment]
Thanks for the release ;) This fixes my issues.

But if there is a `libroadrunner` release there should also be a `libroadrunner-experimental` release. Otherwise depending projects have to switch their pip dependencies between the two depending on which is the newer version. I.e. all projects using the `libroadrunner-experimental` packages are still stuck at 2.0.10, but should be the newest version.

**Comment by CiaranWelsh** [comment]
Agreed. Generally the workflow should be develop --> experimental-release --> release which would mean the experimental-release is never left behind. At any rate, there's a new urgent bug to be fixed in the latest release anyway so we will fix this with that.
