### ISSUE TITLE
binomial distrib function extremly slow

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#886]
Hi all,
I did some distrib testing with roadrunner. Most of the things work very well.
Only the `binomial` functions are extremely slow (making the binomial distribution unusable and all models with it extremly slow).

While it takes 0.0632 sec to take 20 samples of all 20 distributions besides binomial (i.e. 20x20=400 random samples), it takes 15.0228 sec to take 2x20 = 40 samples from the binomial functions.
So it seems to be ~ 2000-2500 times slower to take a binomial sample instead of another random sample !?
```bash
['p_normal_1', 'p_normal_2', 'p_uniform', 'p_bernoulli', 'p_cauchy_1', 'p_cauchy_2', 'p_chisquare_1', 'p_chisquare_2', 'p_exponential_1', 'p_exponential_2', 'p_gamma_1', 'p_gamma_2', 'p_laplace_1', 'p_laplace_2', 'p_lognormal_1', 'p_lognormal_2', 'p_poisson_1', 'p_poisson_2', 'p_raleigh_1', 'p_raleigh_2']
func:'simulate_distrib_roadrunner' args:[('model_distrib.xml',), {'n_samples': 20}] took: 0.0632 sec

['p_binomial_1', 'p_binomial_2']
func:'simulate_distrib_roadrunner' args:[('model_binomial.xml',), {'n_samples': 20}] took: 15.0228 sec
```
Example models attached and code below:
```python
from pathlib import Path
import roadrunner
import numpy as np

def simulate_distrib_roadrunner(sbml_path: Path, n_samples: int):
    """Sample the initial values."""
    r: roadrunner.RoadRunner = roadrunner.RoadRunner(str(sbml_path))
    model: roadrunner.ExecutableModel = r.model
    r.selections = model.getGlobalParameterIds()
    print(r.selections)
    data = np.zeros(shape=(n_samples, len(r.selections)))

    # sample & simulate using roadrunner distrib support
    for k in range(n_samples):
        r.resetToOrigin()
        _s = r.simulate(start=0, end=1, steps=1)
        data[k, :] = _s[0, :]

    return data

n_samples = 20
# fast
data_distrib_roadrunner = simulate_distrib_roadrunner("model_distrib.xml", n_samples=n_samples)
# unusable slow
data_distrib_roadrunner = simulate_distrib_roadrunner("model_binomial.xml",n_samples=n_samples)
```
Here the models: [models.zip](https://github.com/sys-bio/roadrunner/files/7333403/models.zip)

**Comment by luciansmith** [comment]
The problem is the constrained version of your test.  There wasn't a way I found to natively select a constrained binomial, so instead I repeatedly sample from the binomial until I draw a result in the range provided.  If after a huge number of tries I still never drew one inside the range, I select the midpoint of the range and give up.

Currently this is reported as a debug message, but given this, I think it's probably wisest to report an actual error instead.  I could *throw* an error, but that seems a bit extreme?  Do you have an opinion?

The other truncated ranges behave the same way, but I think you gave them a more reasonable range to select from, so those tests didn't take as long to find results in the requested ranges.

**Comment by CiaranWelsh** [comment]
I’m quite unfamiliar with this part of roadrunner - and with distrib in general. How are they implemented? The reason I ask is because we already link numpy, it wouldn’t be hard to sample using numpy.random and let them do the heavy lifting.

**Comment by matthiaskoenig** [comment]
Hi Lucian, 
makes sense. I just put some numbers in there for testing without thinking about the statistics ;) Users do normally not see debug messages, this should be a warning. It this would be a clear warning message this would already solve my problem. I.e. if the constrained distributions take too long (do not find any values) in a reasonable time frame a warning should be provided along the lines of 
```
Sampling of constrained distribution `binomial` took too long. Please ensure reasonable constraints. Midpoint value is used.
```
This would the user allow to recheck the constraints.

**Comment by luciansmith** [comment]
OK, changed the debug message to an actual error message, and now you get multiple messages that look like this:

"Error: Unable to draw from truncated binomial distribution after 100000 tries.  Returning the midpoint between 0 and 2 instead."

Will that work?

**Comment by matthiaskoenig** [comment]
Thanks. Solves my issue.
