### ISSUE TITLE
Add support for distrib poisson distribution

### ISSUE THREAD

**Issue by AndySomogyi** [sys-bio/roadrunner#89]
@luciansmith, what other distributions does antimony support, I'll add those as well.

**Comment by luciansmith** [comment]
The whole list is:

     * normal(mean, stddev), truncatedNormal(mean, stddev, min, max)
     * uniform(min, max)
     * exponential(rate), truncatedExponential(rate, min, max)
     * gamma(shape, scale), truncatedGamma(shape, scale, min, max)
     * poisson(rate), truncatedPoisson(rate, min, max)

Here's a model that uses them all (and which should generate the SBML you need):

a = normal(mean, stddev);
b = truncatedNormal(mean, stddev, min, max);
c = uniform(min, max);
d = exponential(rate);
e = truncatedExponential(rate, min, max);
f = gamma(shape, scale);
g = truncatedGamma(shape, scale, min, max);
h = poisson(rate);
i = truncatedPoisson(rate, min, max);

mean = 1;
stddev = 2;
min = 3;
max = 4;
rate = 5;
shape = 6;
scale = 7;

**Comment by AndySomogyi** [comment]
Sounds good, just a question, what happens in antimony if you do something like 

```
normal = 1;
x = normal(1,2);
uniform = normal(2,3);
```

Are the distrib function names now keywords?

**Comment by luciansmith** [comment]
Right now, you get the error "Unable to use 'normal' as a function, as it
is used elsewhere as a Formula."  I could probably try to reserve the word
like I do with other functions, though.

**Comment by luciansmith** [comment]
(one note:  for all functions, both the min and max are inclusive, so it should be possible to return those values from the distribution.)

**Comment by luciansmith** [comment]
Now incorporated into develop with https://github.com/sys-bio/roadrunner/pull/561
