### ISSUE TITLE
rrplugins 2.1.2 causes Python to terminate in Linux with segmentation faults

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/roadrunner#895]
Noticed by @eagmon. This would have been automatically caught by automated submission to BioSimulators -- sys-bio/tellurium#530.

## Steps to reproduce

1. Launch Docker image
```
docker run -it --rm --entrypoint bash python:3.9-slim-buster
```

2. In Docker image
```
apt-get update -y
apt-get install -y --no-install-recommends libxml2 libncurses5
pip install "tellurium>=2.2.1"
python -c "import tellurium"
```

3. This results in this error
```
Error: ========== In attempt to load plugin: libtel_add_noise.so ===========
POCO Exception: Cannot load library: /usr/local/lib/python3.9/site-packages/rrplugins/libs/libtel_add_noise.so: undefined symbol: _ZN2rr9ExceptionD1Ev
```
```
double free or corruption (fasttop)
Aborted (core dumped)
```

The first part ("Error: ...") occurs when tellurium is imported. The second part ("double free ...") occurs when the Python shell terminates.

## Environment
- tellurium: 2.2.1
- roadrunner: 2.1.1
- Python: 3.9.7
- OS: Debian

**Comment by jonrkarr** [comment]
Even more minimal example
```
docker run -it --rm --entrypoint bash python:3.9-slim-buster
```

```
apt-get update -y
apt-get install -y --no-install-recommends libncurses5
pip install "rrplugins>=2.1.1"
python -c "import rrplugins"
```

```
Error: ========== In attempt to load plugin: libtel_add_noise.so ===========
POCO Exception: Cannot load library: /usr/local/lib/python3.9/site-packages/rrplugins/libs/libtel_add_noise.so: undefined symbol: _ZN2rr9ExceptionD1Ev

free(): double free detected in tcache 2
Aborted (core dumped)
```

## Environment
- rrplugins: 2.1.1
- Python: 3.9.7
- OS: Debian

**Comment by luciansmith** [comment]
I have a question about "This would have been automatically caught by automated submission to BioSimulators."  This isn't exactly true, since it's tellurium that would be submitted to biosimulators, and the problem was with tellurium's dependency, rrplugins.  But would there be a way to automate a roadrunner update so that it triggered a BioSimulators check with the constructed wheel files and/or some other local build system?

**Comment by jonrkarr** [comment]
I suspect what happened here is that tellurium's unit testing doesn't test the compiled wheels from a clean Python environment. The reason BioSimulators would have noticed this is simply because we're starting from a clean environment (which is similar to what users would experience).

This would have been noticed by the automated testing. The automated test suite would have built a new image starting from a clean environment. This would have resulted in pulling the latest versions of each dependency. Then the test suite would have tried to run simulations with this. This would have failed, just as it when @eagmon tried to use tellurium 2.2.1. This failure was quite noticeable because its triggered simply by importing tellurium (which imports rrplugins).

Tools can of course require specific versions of dependencies as needed (in which case we wouldn't be able to detect problems with new version of dependencies). As BioSimulators, we try to not to impose any additional constraints on dependencies beyond those already imposed by each tool.

For nearly all simulation tools, we actually have two layers of testing -- the common test suite, as well as a test suite for each tool. The later is conventional software unit testing. This issue likely would have been noticed at the first layer. As a result, we wouldn't have tried to run the common test suite. You're welcome to add tests to our tellurium testing layer if you like. This is substantially similar to how you're using Azure DevOps.

**Comment by jonrkarr** [comment]
For tools that have automated releases to BioSimulators, we have caught various errors immediately. Some examples:
- Missing dependencies for OpenCOR that prevent their distribution from working
- Regressions on SBML math support for GillesPy2
- Various issues with VCell/SED-ML
- Issues with BioNetGen parsing/validation

Except for VCell, where we don't have a separate second layer of testing, these have been caught at our first layer of testing.

**Comment by luciansmith** [comment]
So it sounds like the answer is 'no'--you would just test Tellurium itself, which has to pull libroadrunner and rrplugins from pypi, and wouldn't use local wheels.  I'll add some rrplugins tests to the roadrunner project itself, then (which needed to happen anyway; I was just curious).

Thank you for finding the problem!  I swear library linking is going to be the death of me yet...

**Comment by jonrkarr** [comment]
Our testing uses wheels from PyPI, same as most users would use. I suspect the origin of the issue comes from local vs PyPI wheels, or from a minimal Debian environment vs the environment you're using in Azure. For example, the Debian image I used has many fewer libraries than the default VM that GitHub actions uses.

From the standpoint of a simulation tools, our testing is probably best thought of as coarse end-to-end testing. Even though this doesn't directly test dependencies, this does find consequential issues, even with dependencies. Because the testing is coarse, this isn't great at pinpointing the origin of problems.

In fact, we have yet another layer of testing where we put all of the simulation tools in one environment. Even though we don't directly test dependencies, this reveals even more issues with dependencies shared across tools. (These issues are very hard to resolve.)

**Comment by luciansmith** [comment]
I finally sorted out the plugins linking problem a while back, so I'm closing this issue.  Thanks for flagging it!
