### ISSUE TITLE
C++ API Headers

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#90]
The develop branch seems to be no longer installing the C++ API headers. I don't know if this is part of a refactoring effort, but it was causing problems when trying to build [telPlugins](http://sys-bio.github.io/telPlugins/). I added the missing headers to the INSTALL target in db611c873b8be841c4dcf94be36f0f1a0d02a153. I was wondering if this will cause problems for anyone.

**Comment by AndySomogyi** [comment]
I was trying to clean it up, before it was installing *every single header*, and I was trying to get it to only install the public headers. 

Send me a PR and I’ll pull those changes in.

**Comment by 0u812** [comment]
I actually already pushed them in db611c873b8be841c4dcf94be36f0f1a0d02a153 because someone else in the lab needed them in a hurry. Unfortunately it's still installing every single header, but it's just meant to be a temp fix for not breaking telPlugins.

**Comment by AndySomogyi** [comment]
Thats fine, 

When I get a chance, I’ll get back to trying to clean it up.

**Comment by 0u812** [comment]
Great sounds good.
