### ISSUE TITLE
How to access results of a oneStep simulation?

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#909]
Hi all,
in early roadrunner versions the `oneStep` simulation returned a result with two rows, i.e. the initial values of the timeCourseSelections and after the step. In current version only a double of the new timestep is returned (see below). How can I access the results which were returned before by the method?
```
    def oneStep(self, currentTime: "double", stepSize: "double", reset: "bool"=True) -> "double":
        r"""

        RoadRunner.oneStep(startTime, stepSize)

        Carry out a one step integration of the model. The method takes two arguments,
        the current time and the step size to us in the integration. The method returns
        the new time which will be currentTime + StepSize::

            newTime = rr.oneStep (10, 0.5)

        """
        return _roadrunner.RoadRunner_oneStep(self, currentTime, stepSize, reset)
```
Also is this the desired behavior? It is very easy to calculate the new time point my self as `startTime + stepSize`, much more important are the simulation results which should be returned. I definitely prefer the earlier behavior of roadrunner.

Best Matthias

**Comment by hsauro** [comment]
I don't remember that onstep returning a result with two rows. I've alway
remembered it returning the new time. It was modeled on the original
C# roadrunner onestep.

It woun't be difficult to add an additional method, eg oneStepEx or or some
name that would do what you want.

**Comment by matthiaskoenig** [comment]
Probably I always used the `simulate` function with `step=1` instead.
So I just don't understand how to access the result of a `oneStep` simulation. Is this meant as a simulation without any results ore is there an additional method which is not exposed in the Python bindings?

**Comment by hsauro** [comment]
The idea is you access the results by using
getFloatingSpeciesConcentrations and any other method like that, eg:

import tellurium as te
import numpy as np
import matplotlib.pyplot as plt

r = te.loada ('''
     S1 -> S2; k1*S1
     S2 -> S3; k2*S2

     k1 = 0.1; k2 = 0.2;
     S1 = 10
''')

t = 0
result = np.concatenate ((np.array([t]),
r.getFloatingSpeciesConcentrations()))
for i in range (40):
    t = r.oneStep (t, 0.5)
    row = np.concatenate ((np.array([t]),
r.getFloatingSpeciesConcentrations()))
    result = np.vstack ((result, row))

plt.plot(result[:,0], result[:,1])
plt.plot(result[:,0], result[:,2])
plt.plot(result[:,0], result[:,3])

**Comment by luciansmith** [comment]
I can confirm that 'oneStep' has always returned a double, and not a two-row vector--that probably was indeed the result of calling simulate with steps=1.

It looks to me like the easiest way to get what you want is to call 'getSelectedValues()', which will return a vector of the values set by the selection vector; something like:

```
import tellurium as te
import roadrunner

r = te.loada("""
             S1 -> S2; S1
             S1 = 10
             S2 = 0

""")

results1 = r.simulate(0, 10, 11)
print(results1)


r.resetAll()
results2 = []
results2.append(r.getSelectedValues())
for t in range(10):
    r.oneStep(t, 1)
    results2.append(r.getSelectedValues())
    
print(results2)
```

results1 and results2 are pretty close to each other, though not identical.

**Comment by hsauro** [comment]
That’s a better way of doing that my example. The results should be the
same, or at least very close.

**Comment by matthiaskoenig** [comment]
Perfect. Thanks for the help. Solves my issue.
The `getSelectedValues` was what I missing.
