### ISSUE TITLE
Conserved Moiety Analysis

### ISSUE THREAD

**Issue by wcopeland** [sys-bio/roadrunner#92]
RoadRunner crashes when: (1) loading the SBML model provided below, (2) changing the "Conserved Moiety Analysis" flag is set to true, and (3) attempting to get or set a parameter value.

This issue is very repeatable and I have found that it affects at least Tellurium. Specifically, the kernel dies in Tellurium. Please fix soon.

<h3>Code</h3>
import roadrunner
rr = roadrunner.RoadRunner('myModel.xml")
rr.conservedMoietyAnalysis = True
print rr.Vm1

<h3>Model</h3>
http://pastebin.com/raw.php?i=GRa5bceP

<h3>Running version</h3>
1.3; Compiler: Microsoft Visual Studio 2010, C++ version: 199711; JIT Compiler: LLVM-3.3; Date: Jan 10 2015, 21:33:18'

**Comment by AndySomogyi** [comment]
There was a bug in the python code where sometimes a wrong object was referenced. This was resolved with 2ef3c84e18d1b51bc59dabb6d25d535876fbf793.
