### ISSUE TITLE
rr.getScaledFluxControlCoefficientMatrix() bug?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#93]
The method rr.getScaledFluxControlCoefficientMatrix() produces nan, nan for the following model, not sure if this is right or not. Needs checking.

import tellurium as te
from scipy import signal

rr = te.loada('''
J1: $Xo -> x; vo*(0.1 + k1*x^4/(k2+x^4));
x -> $w; k3*x;
// Initialization here
k1 = 0.9; k2 = 0.3;
k3 = 0.7; x = 0;
vo = 1;
''')

rr.x = 0.1
rr.steadyState();
print 'x = ', rr.x;
print rr.getCC ('J1', 'vo'), rr.getCC ('J1', 'k3')
print rr.getScaledConcentrationControlCoefficientMatrix()
print "Flux CC:"
print rr.getScaledFluxControlCoefficientMatrix()

rr.x = 0.9
rr.steadyState();
print 'x = ', rr.x;
print rr.getCC ('x', 'vo'), rr.getCC ('x', 'k3')
print rr.getCC ('J1', 'vo'), rr.getCC ('J1', 'k3')
print rr.getScaledConcentrationControlCoefficientMatrix()
print "Flux CC:"
print rr.getScaledFluxControlCoefficientMatrix()

rr.x = 10
rr.steadyState();
print 'x = ', rr.x;
print rr.getCC ('x', 'vo'), rr.getCC ('x', 'k3')
print rr.getCC ('J1', 'vo'), rr.getCC ('J1', 'k3')
print rr.getScaledConcentrationControlCoefficientMatrix()
print "Flux CC:"
print rr.getScaledFluxControlCoefficientMatrix()

**Comment by luciansmith** [comment]
J1: $Xo -> x; vo*(0.1 + k1*x^4/(k2+x^4));
x -> $w; k3*x;
// Initialization here
k1 = 0.9; k2 = 0.3;
k3 = 0.7; x = 0;
vo = 1;

The most recent version of Antimony shouldn't let you use this model:
 you're using 'vo' as a function in your kinetic law, but as a variable
later.  I'm guessing you meant:

J1: $Xo -> x; vo**(0.1 + k1**x^4/(k2+x^4));

(also, you left off the '*' between 'k1' and 'x'.

You also might want to define initial values for Xo, and w.

-Lucian

**Comment by hsauro** [comment]
Definitely meant vo*(0.1 + k1*x^4/(k2+x^4)); The reason was I need a parameter where the rate is a linear function of it. Its not an Antimony issue, it could be related to the model (it has positive feedback) or a bug. I ran it in Jarnac and got different answer, not nan. Maybe run it in COPASI? The model has three steady states hence the three different initial conditions in order to get to each steady state.

**Comment by luciansmith** [comment]
You can't have vo be both a function name and a parameter--you have to have
meant one or the other.  If you meant "vo times point one plus k1 times x
to the fourth divided by k2 plus x to the fourth", then you need the two
extra '*'s symbols.

-Lucian

**Comment by hsauro** [comment]
Oops I see now, I have a typo in the comment, its meant to be:

vo*(0.1 + k1x^4/(k2+x^4));

vo is meant to be a parameter, one where the rate is a linear function of the parameter. What does ** mean, I would have guessed to the power of?

**Comment by hsauro** [comment]
I just looked at the code again and realized its not getScaledFluxControlCoefficientMatrix()  that's the problem but getCC() with respect to the fluxes. I'm investigating further.

**Comment by hsauro** [comment]
Its definitely getCC, I'll scrub this issue and make another one.

**Comment by luciansmith** [comment]
I meant that you forgot two different asterisks in two different places:
 between the 'vo' and the '(', and between the 'k1' and the 'x' in the
middle.  'k1x' looks like a new variable.  So instead of:

vo(0.1 + k1x^4/(k2+x^4));
you want

vo*(0.1 + k1*x^4/(k2+x^4));
