### ISSUE TITLE
Stochastic test suite takes too long on manylinux.

### ISSUE THREAD

**Issue by CiaranWelsh** [sys-bio/roadrunner#939]
The problem is that Azure pipelines gives us a time limit, which is exceeded on manylinux builds (despite the tests passing if run manually). Currently running the tests on manylinux has been disabled but it'd good to find a better solution, like disable a few tests but only on this platform. 

I thought the problem might have been due to the fact that we build gcc in our dockerfile. This was required, since we use C++17. However I wasn't sure whether the appropriate optimizations were set so I rebuilt docker with these optimizations. This is the section of the dockerfile that we use for building gcc/g++. 
```
RUN wget http://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-11.1.0/gcc-11.1.0.tar.gz
RUN tar zxf gcc-11.1.0.tar.gz && yum -y install bzip2
RUN cd gcc-11.1.0 && ./contrib/download_prerequisites
RUN cd gcc-11.1.0 && mkdir build && cd build && ../configure --prefix=/usr/local/gcc-11.1.0 --disable-multilib
RUN cd gcc-11.1.0/build && make -j 12 CPPFLAGS=-O3 CXXFLAGS=-O3
RUN cd gcc-11.1.0/build && make install
RUN cd .. && rm -rf gcc-11.1.0
```
I think that `CPPFLAGS=-O3 CXXFLAGS=-O3` turns on the maximum compiler optimizations, but if I'm wrong I've pasted the code above to be corrected.

**Comment by CiaranWelsh** [comment]
I've also just noticed that the command we use to build on manylinux is: 
```
cmake -DLLVM_INSTALL_PREFIX=/install-llvm-13.x -DRR_DEPENDENCIES_INSTALL_PREFIX=/libroadrunner-deps/install-libroadrunner-deps -DCMAKE_INSTALL_PREFIX=$(INSTALL_DIRECTORY) -DBUILD_PYTHON=ON -DBUILD_RR_PLUGINS=ON -DBUILD_TESTS=ON -DPython_ROOT_DIR=$(PythonRoot) -DSWIG_EXECUTABLE=$(SwigExecutable) ..
cmake --build . --target install --config Release -j 12
```
So although we have the `--config Release` in the cmake build command, `-DCMAKE_BUILD_TYPE=Release` is omitted. This probably isn't the case, but we should add this in just to be sure we're not building in debug mode.

**Comment by CiaranWelsh** [comment]
Same as #929

**Comment by luciansmith** [comment]
Either we solved this in some other way at some point, or setting the build type to 'release' worked!  So, this is fine now.
