### ISSUE TITLE
Require single version of numpy

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#943]
Because a different version of numpy is the latest for Python 3.7 than 3.8 (3.7 has 1.21.5; 3.8 has 1.22), I had to make the 'requirements.txt' file list different versions for both.  This is not ideal, both because it makes the requriements.txt file difficult to maintain, but also could potentially introduce differences between rr on 3.7 and rr on 3.8 (or whatever happens to be different next time).

I think the problem stems from telling azure to get the latest version of numpy.  If instead we asked for a particular version, that's the version that all python versions would use.  We could then update that numpy version and requirements.txt at the same time.

**Comment by Scriptkiddi** [comment]
hey I was wondering why this would be the case? Shouldn't it be possible to just list 
```
numpy>=1.21.0;"
```
or am I missing something?

This change would make it easier to package libroadrunner (in my case for nixos). As the numpy version has no realation to the python version used.

**Comment by luciansmith** [comment]
The problem is that we build with the latest versions of the numpy binaries, and we have to build separate binaries for each version of Python.  This means that the 3.8 rr binaries were build with 1.22, and the 3.7 binaries were built with 1.21.  So if you're on 3.8 and have 1.21, it won't work, and conversely, if I set the requirements to 1.22 for 3.7, that doesn't exist.

I could change our build system to retrieve and build against the 1.21 binaries for Python 3.8, but that seemed a little fraught moving forward as versions change in the future.  Eventually we'll just drop 3.7 support, so we can always stick with the latest.

**Comment by luciansmith** [comment]
(However, if this would make an appreciable difference for nixos, I could look into it--it's why I filed the issue in the first place, after all.)
