### ISSUE TITLE
Add method getDependentFloatingSpeciesIds

### ISSUE THREAD

**Issue by wcopeland** [sys-bio/roadrunner#96]
Add method getDependentFloatingSpeciesIds

**Comment by 0u812** [comment]
Can you provide more info? Where does the method go? What are its parameters? What should it return? Ditto for the other one.

**Comment by hsauro** [comment]
True, I'll provide more info today.

Herbert

**Comment by 0u812** [comment]
Apparently, there is no way to get the IDs of the dependent floating species

**Comment by 0u812** [comment]
So it looks like Andy has his own meaning of *independent* floating species. He considers them independent when they don't have an SBML rule defining them. It has nothing to do with conserved moieties.

**Comment by hsauro** [comment]
In that case he was wrong. The literature uses independent species to
represent independent species in conserved cycles.

H

**Comment by 0u812** [comment]
Okay I was tempted to change the name of the methods `get(In)DependentFloatingSpeciesIds` but if there's literature consensus I will leave as-is.
